### ISSUE TITLE
Linkage Monitor gets grpc 1.24.0 somehow

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1001]
https://github.com/googleapis/google-cloud-java/pull/6554 https://source.cloud.google.com/results/invocations/ea286f59-77ec-44a5-aa92-3de1b99aac0e/log

```
...
BOM Coordinates: com.google.cloud:libraries-bom:2.7.1
...
Could not resolve version conflict among 
[
  io.grpc:grpc-alts:jar:1.24.1 -> io.grpc:grpc-core:jar:[1.24.1,1.24.1], 
  io.grpc:grpc-core:jar:1.24.1, 
  io.grpc:grpc-grpclb:jar:1.24.1 -> io.grpc:grpc-core:jar:[1.24.1,1.24.1], 
  io.grpc:grpc-netty:jar:1.24.1 -> io.grpc:grpc-core:jar:[1.24.1,1.24.1], 
  io.grpc:grpc-netty-shaded:jar:1.24.1 -> io.grpc:grpc-core:jar:[1.24.1,1.24.1], 
  io.grpc:grpc-okhttp:jar:1.24.1 -> io.grpc:grpc-core:jar:[1.24.1,1.24.1], 
  io.grpc:grpc-testing:jar:1.24.1 -> io.grpc:grpc-core:jar:[1.24.1,1.24.1], 
  com.google.cloud:google-cloud-bigtable:jar:1.6.0 -> io.grpc:grpc-core:jar:1.24.1, 
  com.google.cloud:google-cloud-datastore:jar:1.98.1-SNAPSHOT -> io.grpc:grpc-core:jar:1.24.1, 
  com.google.cloud:google-cloud-firestore:jar:1.28.1-SNAPSHOT -> io.grpc:grpc-core:jar:1.24.1, 
  com.google.cloud:google-cloud-firestore:jar:1.28.1-SNAPSHOT -> io.opencensus:opencensus-contrib-grpc-util:jar:0.24.0 -> io.grpc:grpc-core:jar:1.22.1, 
  io.grpc:grpc-all:jar:1.24.0 -> io.grpc:grpc-core:jar:[1.24.0,1.24.0],
  io.grpc:grpc-benchmarks:jar:1.24.0 -> io.grpc:grpc-core:jar:[1.24.0,1.24.0], 
  io.grpc:grpc-interop-testing:jar:1.24.0 -> io.grpc:grpc-core:jar:[1.24.0,1.24.0], 
  io.grpc:grpc-services:jar:1.24.0 -> io.grpc:grpc-core:jar:[1.24.0,1.24.0], 
  com.google.cloud:google-cloud-core-grpc:jar:1.91.3 -> io.grpc:grpc-core:jar:1.24.1
]
```

[com.google.cloud:libraries-bom:2.7.1](https://search.maven.org/artifact/com.google.cloud/libraries-bom/2.7.1/pom) declares `<io.grpc.version>1.24.1</io.grpc.version>`. Why did it get 1.24.0?

BOM import relationship?

After reading the snapshot BOM, it gets duplicate entries of gRPC libraries:

![image](https://user-images.githubusercontent.com/28604/67708006-db84d300-f991-11e9-9269-c533db48dcfd.png)
![image](https://user-images.githubusercontent.com/28604/67707976-cf991100-f991-11e9-9536-88630bf695ac.png)

Who is calling for grpc version 1.24.0 ?

It turned out that

- com.google.cloud:google-cloud-bom:0.116.1-alpha-SNAPSHOT ([link](https://github.com/googleapis/google-cloud-java/pull/6554/files#diff-3242b7a9bca08c5de4307e23dcaa2863R207))
  - importing [com.google.cloud:google-cloud-automl:0.114.0-beta](https://search.maven.org/artifact/com.google.cloud/google-cloud-automl/0.114.0-beta/jar)
    - importing [com.google.cloud:google-cloud-automl-parent:0.114.0-beta](https://search.maven.org/artifact/com.google.cloud/google-cloud-automl-parent/0.114.0-beta/pom)
      - importing `io.grpc:grpc-bom` with `<grpc.version>1.24.0</grpc.version>`

**Comment by chingor13** [comment]
Note that in the PR, we are moving from declaring all client deps to importing the bom from the split repo that contains all of those deps. We need to version bump as well because that's the version that has a bom.

**Comment by chingor13** [comment]
Ok, I'll release a new automl 0.115.0 with the 1.24.1 grpc

**Comment by suztomo** [comment]
Thank you.
