### ISSUE TITLE
Mockito 2.25.1 and byte-buddy-1.9.7

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1005]
Sub-problem of  #1004 .

```
Class org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher is not found
  referenced from org.mockito.internal.creation.bytebuddy.MockMethodAdvice (mockito-core-2.25.1.jar)
  referenced from org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator (mockito-core-2.25.1.jar)
Class net.bytebuddy.jar.asm.commons.ModuleHashesAttribute is not found
  referenced from net.bytebuddy.jar.asm.commons.ClassRemapper (byte-buddy-1.9.7.jar)
```

ModuleHashesAttribute should be fixed in byte-buddy 1.9.10 https://github.com/raphw/byte-buddy/issues/608 .

**Comment by elharo** [comment]
So this one is a true positive. Which project needs to update to 1.9.10? Please file this bug over there.

**Comment by suztomo** [comment]
It's grpc-java. Raised a PR: https://github.com/grpc/grpc-java/pull/6355

**Comment by suztomo** [comment]
The PR is merged. "org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher is not found" still stands in Mockito 2.28.2: https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1008
