### ISSUE TITLE
BOM release instructions should specify merging of release PR

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1011]
specifically whether and when to merge the release branch. Before rapid? After rapid? Before publication? After publication?

**Comment by suztomo** [comment]
Is this good enough already?
https://g3doc.corp.google.com/company/teams/cloud-java/tools/developers/releasing.md#increment-version-in-master

**Comment by elharo** [comment]
It's a Github process. We should probably put it in the Github release document.
