### ISSUE TITLE
A tool to detect a case where a BOM imports non-BOM artifacts

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1014]
There was a mistake where Google Libraries BOM would import a non-BOM artifact; google-cloud-bom imported google-cloud-automl instead of google-cloud-automl-bom. Luckily it was detected by Linkage Monitor with grpc linkage errors. Next time it happens without involving grpc, Linkage Monitor would not detect this kind of mistake.

Can we detect such case?

**Comment by suztomo** [comment]
# Option 1

Throw an exception if the effective BOM contains non-empty dependencies section. Most cases, non-BOM artifacts, such as [`com.google.cloud:google-cloud-automl:0.114.1-beta`](https://search.maven.org/artifact/com.google.cloud/google-cloud-automl/0.114.1-beta/jar), contain non-empty `dependencies` element, while a BOM does not have it.

**Comment by suztomo** [comment]
Another case for a "Google POM Linter": a project specifying conflicting version in `dependency.version` and `dependencyManagement.dependnecy.version` for a Maven artifact.

Such linter would be installed to BOM's project/repository.


Let's see how other issue similar to this happens. Not working on this right now.

**Comment by elharo** [comment]
This might be more usefully included as a warning in Maven itself or in tools such as m2e. I don't know how much traction we'd get with a standalone product.
