### ISSUE TITLE
JLBP-1 should discuss optional dependencies

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#104]
Not the same as scope in maven terms

**Comment by garrettjonesgoogle** [comment]
The description at https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html seems pretty useful. Do we really need to say anything on our own about it?

**Comment by elharo** [comment]
done https://jlbp.dev/JLBP-1.html
