### ISSUE TITLE
Add Linkage Monitor to google-cloud repositories

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1041]
https://search.maven.org/artifact/com.google.cloud/google-cloud-bom/0.121.0-alpha/pom

```
~/java-cloud-bom $ cat pom.xml |perl -nle 'print $1 if m/<artifactId>(.+-bom)</' |grep -v google-cloud-bom |sed -e 's/^/- /'
```

gives 47 BOMs used by google-cloud-bom:

- gax-bom https://github.com/googleapis/gax-java
- google-auth-library-bom https://github.com/googleapis/google-auth-library-java
- google-cloud-core-bom https://github.com/googleapis/java-core
- google-cloud-asset-bom https://github.com/googleapis/java-asset
- google-cloud-automl-bom https://github.com/googleapis/java-automl
- google-cloud-bigquerydatatransfer-bom https://github.com/googleapis/java-bigquerydatatransfer
- google-cloud-bigquerystorage-bom https://github.com/googleapis/java-bigquerystorage
- google-cloud-bigtable-bom https://github.com/googleapis/java-bigtable
- google-cloud-billingbudgets-bom https://github.com/googleapis/java-billingbudgets
- google-cloud-build-bom https://github.com/googleapis/java-cloudbuild
- google-cloud-container-bom https://github.com/googleapis/java-container
- google-cloud-containeranalysis-bom https://github.com/googleapis/java-containeranalysis
- google-cloud-datacatalog-bom https://github.com/googleapis/java-datacatalog
- google-cloud-datalabeling-bom https://github.com/googleapis/java-datalabeling
- google-cloud-dataproc-bom https://github.com/googleapis/java-dataproc
- google-cloud-dlp-bom https://github.com/googleapis/java-dlp
- google-cloud-dialogflow-bom https://github.com/googleapis/java-dialogflow
- google-cloud-errorreporting-bom https://github.com/googleapis/java-errorreporting
- google-cloud-firestore-bom https://github.com/googleapis/java-firestore
- google-cloud-gameservices-bom https://github.com/googleapis/java-gameservices
- google-cloud-iamcredentials-bom https://github.com/googleapis/java-iamcredentials
- google-cloud-irm-bom
- google-cloud-iot-bom
- google-cloud-kms-bom
- google-cloud-language-bom
- google-cloud-logging-bom
- google-cloud-monitoring-bom
- google-cloud-os-login-bom
- google-cloud-phishingprotection-bom
- google-cloud-pubsub-bom
- google-cloud-recaptchaenterprise-bom
- google-cloud-recommender-bom
- google-cloud-redis-bom
- google-cloud-scheduler-bom
- google-cloud-secretmanager-bom
- google-cloud-securitycenter-bom
- google-cloud-spanner-bom
- google-cloud-speech-bom
- google-cloud-talent-bom
- google-cloud-tasks-bom
- google-cloud-texttospeech-bom
- google-cloud-trace-bom
- google-cloud-translate-bom
- google-cloud-video-intelligence-bom
- google-cloud-vision-bom
- google-cloud-websecurityscanner-bom
- google-cloud-webrisk-bom

With #1154 fixed, these repositories above can run Linkage Monitor.

-----

https://github.com/googleapis/google-auth-library-java has two widely-used Maven artifacts:

- com.google.auth:google-auth-library-oauth2-http:0.18.0
- com.google.auth:google-auth-library-credentials:0.18.0

The two artifacts are not part of our BOM
https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/snapshot/artifact_details.html, and thus setting up Linkage Monitor does not check anything as of current implementation.

Still, there's pain for updating the BOM if there's incompatible change in these libraries. We may need to think how we can address such cases where the artifacts are not in BOM but play important role in artifact compatibility.

**Comment by suztomo** [comment]
Now these libraries are part of google-cloud-bom. It does not use property for the version:

https://search.maven.org/artifact/com.google.cloud/google-cloud-bom/0.121.0-alpha/pom
```
      <dependency>
        <groupId>com.google.auth</groupId>
        <artifactId>google-auth-library-bom</artifactId>
        <version>0.19.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

**Comment by suztomo** [comment]
47 repositories are many. How can we install Kokoro Linkage Monitor job configs and build configs?

## Can we share build config?

No, probably. In google-cloud-java projects, Kokoro build configs are maintained in GitHub repository, not in Google3.

## What needs to be done for each repository?

- Kokoro build config (`.kokoro/presubmit/linkage-monitor.cfg`) in GitHub
  https://github.com/googleapis/java-cloud-bom/blob/master/.kokoro/presubmit/linkage-monitor.cfg
  `TRAMPOLINE_BUILD_FILE` has different directory name per repository
- Shell script to run LinkageMonitor (`.kokoro/linkage-monitor.sh`) in GitHub
  https://github.com/googleapis/java-cloud-bom/blob/master/.kokoro/linkage-monitor.sh
  The same file for every repository.
- Kokoro job config in Google3.

**Comment by suztomo** [comment]
cl/292391265

**Comment by suztomo** [comment]
cl/292391265 has been submitted. It started working 

Remaining repositories:

repository name| build config? | kokoro job config? |
------------ | ------------- | --------- |
google-api-java-client|[Yes](https://github.com/googleapis/google-api-java-client/blob/master/.kokoro/presubmit/linkage-monitor.cfg)||
gax-java|[Not yet](https://github.com/googleapis/gax-java/tree/master/.kokoro/presubmit)||
google-oauth-java-client|[Yes](https://github.com/googleapis/google-oauth-java-client/blob/master/.kokoro/presubmit/linkage-monitor.cfg)||
api-common-java|[Not yet](https://github.com/googleapis/api-common-java/tree/master/.kokoro/presubmit)||

**Comment by suztomo** [comment]
For api-common-java, does this help to generate a POM?
https://docs.gradle.org/current/userguide/publishing_maven.html

**Comment by suztomo** [comment]
Api-common-java does not use `maven-publish` plugin. Therefore, it does not support `generatePomFileForPubNamePublication`.

**Comment by elharo** [comment]
done
