### ISSUE TITLE
aspectjweaver missing com.bea.jvm classes

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1047]
Is this valid linkage error?

```
suztomo@suxtomo24:~/beam6$ ./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-io-kafka :checkJavaLinkage |tee linkage.log

...

Class com.bea.jvm.ClassPreProcessor is not found;
  referenced by 1 class file
    org.aspectj.weaver.loadtime.JRockitAgent (aspectjweaver-1.8.9.jar)
Class com.bea.jvm.JVMFactory is not found;
  referenced by 1 class file
    org.aspectj.weaver.loadtime.JRockitAgent (aspectjweaver-1.8.9.jar)
Class com.bea.jvm.JVM is not found;
  referenced by 1 class file
    org.aspectj.weaver.loadtime.JRockitAgent (aspectjweaver-1.8.9.jar)
Class com.bea.jvm.ClassLibrary is not found;
  referenced by 1 class file
    org.aspectj.weaver.loadtime.JRockitAgent (aspectjweaver-1.8.9.jar)

```

Is this fixed in later release?
https://search.maven.org/artifact/org.aspectj/aspectjweaver/1.9.4/jar

# AspectJ

[What is AspectJ?](https://www.eclipse.org/aspectj/doc/released/faq.php#q:whatisaj)

> AspectJ(tm) is a simple and practical extension to the Java(tm) programming language that adds to Java aspect-oriented programming (AOP) capabilities. AOP allows developers to reap the benefits of modularity for concerns that cut across the natural units of modularity. In object-oriented programs like Java, the natural unit of modularity is the class. In AspectJ, aspects modularize concerns that affect more than one class.
> 
> You compile your program using the AspectJ compiler (perhaps using the supported development environments) and then run it, supplying a small (< 100K) runtime library.
> 
> The AspectJ technologies include a compiler (ajc), a debugger (ajdb), a documentation generator (ajdoc), a program structure browser (ajbrowser), and integration with Eclipse, Sun-ONE/Netbeans, GNU Emacs/XEmacs, JBuilder, and Ant.

Blog: http://andrewclement.blogspot.com/2017/10/aspectj-190rc1-released.html

## AspectJ Weaver

Weaver (Compiler) reads class files and their annotations. Adds bytecode to method invocation if necessary.

[How does the compiler/weaver work? Are there any white papers?](https://www.eclipse.org/aspectj/doc/released/faq.php#q:whitepapers)

## JRockitAgent

This class is intended to work with JRockit JVM.

[The comment](https://www.eclipse.org/aspectj/doc/next/weaver-api/org/aspectj/weaver/loadtime/JRockitAgent.html) tells how to use it.

> JRockit (tested with 7SP4 and 8.1) preprocessor Adapter based on JMAPI
> 
> JRockit has a low level API for hooking ClassPreProcessor, allowing the use of online weaving at full speed.
> ...
> The command line will look like: "%JAVA_COMMAND%" -Xmanagement:class=org.aspectj.weaver.loadtime.JRockitAgent -cp ... 

### What is JRockit JVM?

https://www.oracle.com/technetwork/middleware/jrockit/overview/index.html

> The Oracle JRockit JVM is the industry's highest performing Java Virtual Machine now built into Oracle Fusion Middleware. 

# Repository

https://git.eclipse.org/c/aspectj/org.aspectj.git

```
suztomo@suxtomo24:~$ git clone https://git.eclipse.org/r/aspectj/org.aspectj
Cloning into 'org.aspectj'...
remote: Total 118505 (delta 0), reused 118505 (delta 0)
Receiving objects: 100% (118505/118505), 634.12 MiB | 15.75 MiB/s, done.
Resolving deltas: 100% (62327/62327), done.
suztomo@suxtomo24:~$ cd org.aspectj/
suztomo@suxtomo24:~/org.aspectj$ ls
ajbrowser  asm            bcel-builder  installer  mvnw.cmd               org.eclipse.jdt.core  runtime                       testing-client   util
ajde       aspectjrt      bridge        lib        org.aspectj.ajdt.core  pom.xml               shadows.org.eclipse.jdt.core  testing-drivers  weaver
ajde.core  aspectjtools   build         loadtime   org.aspectj.lib        README.md             taskdefs                      testing-util
ajdoc      aspectjweaver  docs          mvnw       org.aspectj.matcher    run-all-junit-tests   testing                       tests
suztomo@suxtomo24:~/org.aspectj$ find . -name JRockitAgent.java
./loadtime/src/main/java/org/aspectj/weaver/loadtime/JRockitAgent.java
```

Apart from the problem, I filed a bug report on wrong information in pom.xml: https://bugs.eclipse.org/bugs/show_bug.cgi?id=553716

**Comment by suztomo** [comment]
aspectjweaver 1.9.4 also has the references to the classes.

```
suztomo@suxtomo24:~/Downloads$ javap -v -cp aspectjweaver-1.9.4.jar org.aspectj.weaver.loadtime.JRockitAgent |grep com.bea.jvm.ClassPreProcessor
public class org.aspectj.weaver.loadtime.JRockitAgent implements com.bea.jvm.ClassPreProcessor
   #7 = InterfaceMethodref #55.#56        // com/bea/jvm/ClassLibrary.setClassPreProcessor:(Lcom/bea/jvm/ClassPreProcessor;)V
  #17 = Class              #67            // com/bea/jvm/ClassPreProcessor
  #56 = NameAndType        #76:#77        // setClassPreProcessor:(Lcom/bea/jvm/ClassPreProcessor;)V
  #67 = Utf8               com/bea/jvm/ClassPreProcessor
  #77 = Utf8               (Lcom/bea/jvm/ClassPreProcessor;)V
        26: invokeinterface #7,  2            // InterfaceMethod com/bea/jvm/ClassLibrary.setClassPreProcessor:(Lcom/bea/jvm/ClassPreProcessor;)V

```

**Comment by suztomo** [comment]
The `org.aspectj.weaver.loadtime.JRockitAgent` is in loadtime directory of aspectj repository. The `com.bea.jvm.JVMFactory` and `ClassLibrary` exists in the repository's [lib/ext/jrockit/jrockit.jar](https://git.eclipse.org/c/aspectj/org.aspectj.git/tree/lib/ext/jrockit).

```
		<dependency>
			<groupId>jrockit</groupId>
			<artifactId>jrockit</artifactId>
			<version>1.0</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/../lib/ext/jrockit/jrockit.jar</systemPath>
		</dependency>
```

[Aspectjweaver/aspectjweaver-assembly.xml](https://git.eclipse.org/c/aspectj/org.aspectj.git/tree/aspectjweaver/aspectjweaver-assembly.xml) assembles class files in `../loadtime/target/classes` into aspectjweaver.

The pom.xml used in its release is different from the actual build file: https://git.eclipse.org/c/aspectj/org.aspectj.git/tree/build/usedForMavenUpload_release/aspectjweaver.pom

**Comment by suztomo** [comment]
Because the missing classes (`com.bea.jvm.ClassPreProcessor` for example) exist only in JRockit JVM, it's a case for whitelisting.

**Comment by kriegaex** [comment]
FYI, There will be no more system dependencies with ugly local paths anymore in the upcoming AspectJ 1.9.7, I factored them all out of the build. So in the future this problem should no longer occur in general.

With regard to JRockit in particular, I completely removed it because it is stone age legacy stuff. Therefore, this one will not bother you anymore either way.

**Comment by suztomo** [comment]
@kriegaex Such cleanup helps diagnosing output from this static analysis tool.  Thank you!

**Comment by elharo** [comment]
Obsolete
