### ISSUE TITLE
Protobuf-lite errors in BOM

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1056]
![image](https://user-images.githubusercontent.com/28604/70176630-cabd3080-16a6-11ea-8ca0-1e3ee2e9a862.png)

# protobuf-java-3.11.0.jar
2 target classes causing linkage errors referenced from 2 source classes.

(protobuf-lite-3.0.1.jar) com.google.protobuf.CodedOutputStream$NioEncoder's method writeMessage(int arg1, com.google.protobuf.MessageLite arg2, com.google.protobuf.Schema arg3) is not implemented in the class, referenced from 1 class ▶

(protobuf-lite-3.0.1.jar) com.google.protobuf.CodedOutputStream$NioEncoder's method writeMessageNoTag(com.google.protobuf.MessageLite arg1, com.google.protobuf.Schema arg2) is not implemented in the class, referenced from 1 class ▶

The following paths to the jar file from the BOM are found in the dependency tree:

com.google.protobuf:protobuf-java:3.11.0 (compile)
com.google.protobuf:protobuf-java-util:3.11.0 (compile) / com.google.protobuf:protobuf-java:3.11.0 (compile)

This error seems a genuine error.

![image](https://user-images.githubusercontent.com/28604/70183743-512c3f00-16b4-11ea-85cf-4d973f391d11.png)

# protobuf-lite (old. Latest: 3.0.1)

https://github.com/protocolbuffers/protobuf/blob/javalite/java/lite.md

# protobuf-javalite (new. Latest: 3.11.1)

https://github.com/protocolbuffers/protobuf/blob/master/java/lite.md

Should gRPC use protobuf-javalite?

**Comment by suztomo** [comment]
Dependency Paths to com.google.protobuf:protobuf-lite:3.0.1

https://gist.github.com/suztomo/1f7030940448dc08bb60e7508e9074a2

**Comment by suztomo** [comment]
gRPC 1.26 is going to have protobuf-**javalite** dependency (https://github.com/grpc/grpc-java/issues/6474#issuecomment-561347198 ), rather than old protobuf-lite.

**Comment by suztomo** [comment]
Will grpc-java 1.26's protobuf-javalite dependency remove this linkage errors from the dashboard?

That might not the case. The error from `CodedOutputStream$NioEncoder` will continue to appear from protobuf-lite in somewhere in the dependnecy tree, because `protobuf-javalite` is different Maven artifact than `protobuf-lite` (in terms of groupID and artifactID) and `protobuf-javalite` does not have `CodedOutputStream$NioEncoder` class.

**Comment by suztomo** [comment]
This is false positive.

- protobuf-lite's `CodedOutputStream.NioEncoder` has private access and only accessed by protobuf-lite's `CodedOutputStream`.
- The Linkage Checker's class path has protobuf-**java**'s `CodedOutputStream` before protobuf-lite's. Protobuf-java's `CodedOutputStream` does not have a reference to `CodedOutputStream.NioEncoder`.
- So protobuf-lite's `CodedOutputStream` and `CodedOutputStream.NioEncoder` are never used.

**Comment by suztomo** [comment]
Proposal: suppress linkage errors when the all of the conditions below are met:
- The problematic class (`CodedOutputStream$NioEncoder` in this case) is private
- The problematic class is an inner class
- In the class path, the outer class (`CodedOutputStream` in this case)'s JAR file (`protobuf-java-3.11.1.jar` in this case) is different from the inner class's JAR file (`protobuf-lite-3.0.1.jar` in this case).

**Comment by suztomo** [comment]
```
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf-lite</artifactId>
      <version>1.25.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>protobuf-lite</artifactId>
          <groupId>com.google.protobuf</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by elharo** [comment]
This is a false positive because the analyzer does not respect exclusions. It needs to.

**Comment by suztomo** [comment]
https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/799

**Comment by suztomo** [comment]
I'll try to fix this by DependencyGraphBuilder to respect exclusions elements.

**Comment by suztomo** [comment]
Be careful of revisiting nodes with different exclusions.
