### ISSUE TITLE
Dashboard to show dependency path of the JAR file containing class files in symbol problems

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1060]
Currently the JAR file of symbol problem's class is not easy to locate. In the example of #1056, the dashboard does not show the dependency path of `protobuf-lite-3.0.1.jar`:

![image](https://user-images.githubusercontent.com/28604/70279314-36c19680-1784-11ea-879c-fe086a185db3.png)

Shall we show the dependency path of JAR file containing symbol problem's class?

**Comment by elharo** [comment]
Seems reasonable. Perhaps start with a mockup of what this would look like. E.g. what HTML are we adding?

**Comment by suztomo** [comment]
@elharo a mockup below. What do you think?

![image](https://user-images.githubusercontent.com/28604/70335460-51901b80-1815-11ea-948c-59342fcd9532.png)

**Comment by suztomo** [comment]
Memo:
artifact path 

The following paths have protobuf-java-3.11.0:
