### ISSUE TITLE
libraries-bom is missing grpc-api

### ISSUE THREAD

**Issue by igorbernstein2** [GoogleCloudPlatform/cloud-opensource-java#1074]
Also, why not just import the grpc-bom instead of trying to list of the modules?

**Comment by elharo** [comment]
we tried, it didn't work. As I recall there were some modules in there we needed to exclude.

**Comment by igorbernstein2** [comment]
I'm a bit confused: you tried to add grpc-api? or import grpc-bom?
I can understand if you can't import grpc-bom.  But don't understand why grpc-api can't be part of the libraries-bom? From what I understand grpc-api is the smallest dependency (other the grpc-context) you can have on grpc.
Every grpc client will have a direct dependency on grpc-api (it contains ClientCall & ManagedChannel).

**Comment by elharo** [comment]
You're right. we'll need to look at grpc-api. grpc-bom definitely did not work for reasons I don't immediately recall

**Comment by suztomo** [comment]
Here are issues of importing grpc-bom:
- grpc-bom 1.24 had this problem https://github.com/grpc/grpc-java/issues/6219. Now fixed.
- `io.grpc:grpc-benchmarks` and `io.grpc:grpc-interop-testing` have errors from our tool's analysis. They are not for users. https://github.com/grpc/grpc-java/issues/6354.

We should add `grpc-api`.

@elharo There are other artifacts: `grpc-services` and `grpc-protobuf-lite`. They are in [grpc-bom:1.25](https://search.maven.org/artifact/io.grpc/grpc-protobuf-lite/1.25.0/jar), but not in [our BOM](https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/snapshot/artifact_details.html).

**Comment by elharo** [comment]
we definitely don't want protobuf-lite; not sure about grpc-services

**Comment by suztomo** [comment]
Grpc-services artifact is also for users. It has [HealthStatusManager class](https://github.com/grpc/grpc-java/blob/master/services/src/main/java/io/grpc/services/HealthStatusManager.java), which can check the health of gRPC services. I could not find a documentation but this issue (https://github.com/grpc/grpc-java/issues/3366) explains what is it for.

I'll create a PR for grpc-api and grpc-services.

**Comment by suztomo** [comment]
Released version 3.2.0
