### ISSUE TITLE
install renovabot to cloud-opensource-java

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1088]
It's free. https://dependabot.com/

**Comment by suztomo** [comment]
Or renovate-bot.

**Comment by elharo** [comment]
There might be security and policy issues preventing this. Do you know of any other google repos that use it?

**Comment by suztomo** [comment]
https://github.com/googleapis/google-cloud-java/pull/7075 renovate-bot is used by Yoshi team.

Also guideline on the 3rd-party GitHub app: go/github-docs/services

**Comment by suztomo** [comment]
Renovate to exclude example directory:
https://docs.renovatebot.com/configuration-options/#ignorepaths

**Comment by suztomo** [comment]
It started working. As of now not touching BOM because we want two humans involved when updating BOM content.
