### ISSUE TITLE
Proposal: Dependency section in component.ftl

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#111]
This proposal is to have dependency tree shown in component page. This will help to understand problem of version mismatch.

As the `DependencyTreeFormatter.formatDependencyPaths(dependencyPathList)` is already there. Integrating it to component.ftl is simple and won't cause additional network communication.

Example implementation:

<img width="960" alt="screen shot 2018-10-03 at 09 58 34" src="https://user-images.githubusercontent.com/28604/46415493-5f1eb280-c6f3-11e8-900c-9128cadb5bb2.png">

@elharo What do you think?

**Comment by elharo** [comment]
That's a very good idea. We might want to think about how we can use HTML to improve the formatting, but certainly dumping it into a pre element is good enough for a first pass. 

We may have higher priority items to focus on, but this shouldn't take long either. Let's chat about it.
