### ISSUE TITLE
Test cases with BCEL for Static Linkage Checker

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#113]
As preparation for #110 . As discussed with Elliottte, first let's write test cases where we can get enough information from class files, using [BCEL JavaClass](https://commons.apache.org/proper/commons-bcel/manual/bcel-api.html).

- Get list of method signatures from a class file (target)
- Get constant pool information (source)

**Comment by suztomo** [comment]
First test cases to be committed tomorrow. Memo for discussion later:

- method call for ones defined in super class
-- We may need to build tree of class hierarchy to resolve methods
- how to get inner classes via BCEL JavaClass
- one method may have multiple signatures

**Comment by garrettjonesgoogle** [comment]
Note: you can't quite say that "one method may have multiple signatures", because that's not really one method. I think you might mean "there may be multiple methods with the same method name, distinguished by their signatures (or more specifically, their parameter lists)."

**Comment by suztomo** [comment]
Right. Updated source code comment on this.

**Comment by suztomo** [comment]
Updated comment
