### ISSUE TITLE
Linkage Checker: configure maven-compiler-plugin to fail on errorprone's warnings

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1133]
We'll pay more attention to errorprone if the build fails on its warnings. Shall we do that?

**Comment by elharo** [comment]
What warnings is it producing now? Are they accurate and significant?

**Comment by suztomo** [comment]
No warnings in the master as of now. Last week I noticed that unused imports and unused variables, which I fixed. I hope the errorprone compiler could have detected earlier.

**Comment by elharo** [comment]
Is there a system property or Maven property that could set this on a per-developer basis? I'd prefer not to have it in the CI.

**Comment by suztomo** [comment]
I want the warnings (such as unused imports) fail in CI. GitHub UI tells only whether a build succeeds or not. It does not tell a PR adds new warnings.

**Comment by elharo** [comment]
I really don't want that unless the warnings are more important than unused imports. If it's not potentially a genuine bug, it's not worth slowing down velocity for this. Minor issues like this can be cleaned up whenever convenient.

**Comment by suztomo** [comment]
Okay.

**Comment by suztomo** [comment]
Somehow I only see these errorprone warnings in IntelliJ:

![image](https://user-images.githubusercontent.com/28604/72584922-f6dceb80-38b9-11ea-9819-7df9b2915389.png)
