### ISSUE TITLE
Linkage Checker is slow when analyzing beam-sdks-java-extensions-sql-zetasql

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1145]
I'm feeling it's doing something unexpected and unnecessary.

![image](https://user-images.githubusercontent.com/28604/73004745-d50dc800-3dd5-11ea-9b6f-b02415e4e634.png)

```
./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-extensions-sql-zetasql :checkJavaLinkage
```

**Comment by suztomo** [comment]
![image](https://user-images.githubusercontent.com/28604/73098844-38702680-3eb8-11ea-93a2-065e49ef937d.png)

**Comment by elharo** [comment]
By any chance is a repo other than maven central serving these artifacts? If so, it might simply be slow. 

Otherwise, is it possible we're downloading the same artifacts many times? If so we need to figure out how to not do that. 

From the profile it seems unlikely any purely algorithmic changes would have a major effect. It looks like we're spending 3/4 of the time loading artifacts from the remote repo.

**Comment by suztomo** [comment]
I think visiting 1 million (1,115,000) dependency nodes in the graph is the problem. Although they contain duplicate Maven artifacts, their dependency paths from the root are unique. Each visit incurs (1) in-memory cache hit, (2) Maven local repo filesystem access, (3) Maven central network access, and/or (4) other remote repository network access.

Given the fact that I had run Linkage Check for beam-sdks-java-extensions-sql-zetasql before the profiling, I expect (1) and (2) were common.



Another (irrelevant) optimization: these JAR files are not needed until they are selected into the class path. This will help when the JAR files are not in local Maven repository.

**Comment by suztomo** [comment]
Can DependencyGraphBuilder.levelOrder not to put duplicate (groupId + artifactId) into queue?

**Comment by suztomo** [comment]
Cutting duplicate versionless coordinates brings down the execution time 3 minutes (from 18 minutes). branch: prune.

This contradicts dependency convergence in dashboard.

**Comment by suztomo** [comment]
To check whether there's any unexpected network connections.

**Comment by suztomo** [comment]
Test case for the slowness: https://github.com/GoogleCloudPlatform/cloud-opensource-java/commit/182370f6cb680edda5e7828585c6ae1758f425e1

**Comment by suztomo** [comment]
Question: Is it possible to tell Maven repository system not to perform dependency mediation?

Background: In `DependencyGraphBuilder.resolveCompileTimeDependencies`, Maven's `RepositorySystem.collectDependencies` preforms dependency mediation to remove duplicate. We want the duplicate for dependency convergence as well as to show multiple dependency paths to an artifact. That's why DependencyGraphBuilder recursively call resolveCompileTimeDependencies in dependency tree.

**Comment by suztomo** [comment]
It seems that's good direction. DefaultDependencyCollector.collectDependencies temporarily has the dependency graph with duplicate. The dependency graph below shows protobuf-java artifact appearing in different part in the graph:

![image](https://user-images.githubusercontent.com/28604/73880795-1fa72f80-482d-11ea-8a12-02c04eb20665.png)

These duplicate is removed by `transformer.transformGraph( node, context )`:

![image](https://user-images.githubusercontent.com/28604/73880927-63019e00-482d-11ea-9b8f-a8ba3d96f7db.png)

**Comment by suztomo** [comment]
The transformer is ChainedDependencyGraphTransformer, which applies ConflictResolver and JavaDependencyContextRefiner to the dependency graph.

**Comment by suztomo** [comment]
Once this is done, confirm whether this solves the OutOfMemoryError in https://gist.github.com/iemejia/863f5c112b77be1053e73d01f1ec9f0f

**Comment by suztomo** [comment]
With current master (aa48adec), the linkage check for beam-sdks-java-extensions-sql-zetasql finishes in 4.5 minutes. 

```
suztomo@suxtomo24:~/beam6$ ./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-extensions-sql-zetasql :checkJavaLinkage
...
BUILD SUCCESSFUL in 4m 22s
903 actionable tasks: 160 executed, 743 up-to-date
```

Test case above for the slowness (182370f) takes only 1 minutes 5 seconds. Compared to previous result (11 minutes 38 seconds), it's 10x speedup.
