### ISSUE TITLE
New class: JarDumper with listExternalConstantPoolMethodref

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#115]
JarDumper will be responsible to list all Methodref entries that point to external classes to its containing classes.

Example scenario with jar file and class files:

<img width="623" alt="screen shot 2018-10-05 at 11 08 52" src="https://user-images.githubusercontent.com/28604/46543532-1865bf80-c88f-11e8-9240-b6aa0267f7fa.png">

`JarDumper.listExternalConstantPoolMethodref(A.jar)` is to return a list containing `MethodRef(class=Z, method=bar, signature: "()F")` because class Z is external to A.jar.

The returned list does not contain `Methodref` with `foo` on class Y, because class Y is in A.jar.

**Comment by garrettjonesgoogle** [comment]
The concept sounds correct.

Naming: I might recommend `JarDumper.listExternalMethodReferences`. Also, other names here would change as per naming in https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/114 .

I don't have a better name than `JarDumper` but I suspect we might come up with a more targeted name later.

**Comment by suztomo** [comment]
Thank you!
