### ISSUE TITLE
Is there a way to detect invalid class cast statically?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1158]
Is it feasible to statically find this kind of invalid class casts?
https://github.com/googleapis/java-core/issues/123

**Comment by elharo** [comment]
This feels like a question for something like errorprone or spotbugs, not the linkage checker. @suztomo can we close this?

**Comment by suztomo** [comment]
Right. Linkage Checker cannot detect that.
