### ISSUE TITLE
Linkage Checker reporting problem in shadowed classes?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1159]
https://gist.github.com/suztomo/92c42ffdd8e7f6a02500b53ee5dc8d9b says:

```
(weld-osgi-bundle-1.1.0.Final.jar) com.google.common.collect.EmptyImmutableMultiset's method size() is not implemented in the class;
  referenced by 1 class file
    com.google.common.collect.ImmutableMultiset (guava-25.1-jre.jar)
```

In weld-osgi-bundle-1.1.0.Final.jar, com.google.common.collect.EmptyImmutableMultiset extends `com.google.common.collect.ImmutableMultiset<Object>` which implements `public int size() {  return this.size;  }`. Linkage Checker should not complain the missing method.

Other factors

weld-osgi-bundle-1.1.0 has `public class ImmutableMultiset<E> extends ImmutableCollection<E> implements Multiset<E>`. This implements size method.

Guava 28.0-jre has `public abstract class com.google.common.collect.ImmutableMultiset<E> extends ImmutableMultisetGwtSerializationDependencies<E>
    implements Multiset<E>`. This does not implement `size()` method. https://guava.dev/releases/28.0-jre/api/docs/com/google/common/collect/ImmutableMultiset.html

As long as weld-osgi-bundle-1.1.0 comes before Guava 28 in the class path, weld's `com.google.common.collect.ImmutableMultiset` should be always picked up and thus Linkage Checker should not report the error from Guava's `com.google.common.collect.ImmutableMultiset`.

**Comment by elharo** [comment]
So the issue is that the same class appears in multiple jars? Can you edit the above to use fully package qualified names? That might make this clearer.

**Comment by suztomo** [comment]
Added package name.

**Comment by suztomo** [comment]
Somehow the following test does not fail? Investigating further.

```
  @Test
  public void testFindSymbolProblems_shadowedAbstractClass()
      throws IOException, RepositoryException {
    ImmutableList<Path> jars =
        resolvePaths(
            "org.jboss.weld:weld-osgi-bundle:1.1.0.Final",
            "com.google.guava:guava:25.1-jre");

    LinkageChecker linkageChecker = LinkageChecker.create(jars, jars);

    ImmutableMultiset<SymbolProblem> problems = linkageChecker.findSymbolProblems().keys();
    System.out.println(problems);
    Truth.assertThat(problems).comparingElementsUsing(
        Correspondence.transforming((SymbolProblem problem) -> problem.getSymbol().getClassBinaryName(),
            "has problem on class")
        ).doesNotContain("com.google.common.collect.EmptyImmutableMultiset");
  }
```

branch weld-guava

**Comment by elharo** [comment]
Is the problem split packages?

**Comment by suztomo** [comment]
> Somehow the following test does not fail.

Having guava first reproduces the problem.

It turned out that `com.google.common.collect.EmptyImmutableMultiset` is not present in latest Guava releases and thus the one in weld-osgi-bundle was not shadowed. Linkage Checker is working as expected here.
