### ISSUE TITLE
Bom members as HTML table for multiple bom versions

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1161]
Similar to https://issues.apache.org/jira/browse/BEAM-8963. We want the table published as a website to look up which version of libraries-bom contains a specific artifact, for example, google-cloud-core:1.92.0.

**Comment by elharo** [comment]
More generically we want users to easily be able to determine what the BOM covers and map version of the BOM to versions of the libraries. Perhaps this becomes part of or subsumes the dashboard.

**Comment by elharo** [comment]
Step 1: Figure out which GCP project we store the dashboard files in, and document this where we can find it.

**Comment by suztomo** [comment]
I cannot find "cloud-opensource-java-dashboard" bucket in gcp-dev-tools, cloud-tools-for-java, or gcloud-for-eclipse-testing project. I guess it's a project that I don't have access.

**Comment by elharo** [comment]
see #158

**Comment by suztomo** [comment]
I checked the issue 158, no mention about GCP project. It seems that there was no configuration change in GCP console needed.

**Comment by elharo** [comment]
The dashboard for individual versions are archived and published. E.g.

https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/3.3.0/index.html

We still might want to link to this from somewhere.

**Comment by elharo** [comment]
#656 is related

**Comment by elharo** [comment]
being worked on in a different repo by @stephaniewang
