### ISSUE TITLE
Linkage Checker Gradle plugin

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1184]
(not yet starting)

Reference: Java ecosystem report.
![image](https://user-images.githubusercontent.com/28604/73869869-144a0900-4819-11ea-96cf-22b65d106803.png)

https://snyk.io/blog/jvm-ecosystem-report-2020/

Note:
Libraries built by Gradle, such as Apache Beam, may be used by many Maven users.

**Comment by elharo** [comment]
done: https://plugins.gradle.org/plugin/com.google.cloud.tools.linkagechecker
