### ISSUE TITLE
Can we remove resolveCompileDependencies in DependencyGraphBuilder.levelOrder?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1188]
DependencyGraphBuilder.levelOrder calls `resolveCompileDependencies`. This makes things complex.

Can we remove this?

LevelOrder calls resolveCompileDependencies because we want to have duplicate nodes in resulting dependency graph. Normal Maven dependency graph does not allow duplicate on artifactId and groupId. If we can control Maven resolver to skip its dependency mediation, we don't need to call resolveCompileDependencies.

This will solve 1 million method calls in #1145 .

Trying with a new type of session that gives the full dependency graph.
```
  /**
   * Opens a new Maven repository session for full dependency graph resolution.
   *
   * <p>Compared with Maven's normal dependency graph, full dependency graph includes provided-
   * scope dependencies and optional dependencies even if they are transitive dependencies.
   */
  static RepositorySystemSession newSessionWithFullDependency(RepositorySystem system) {
    DefaultRepositorySystemSession session = createDefaultRepositorySystemSession(system);

    // This combination of DependencySelector comes from the default specified in
    // `MavenRepositorySystemUtils.newSession`.
    // LinkageChecker needs to include 'provided' scope and optional scope
    DependencySelector dependencySelector =
        new AndDependencySelector(
            // ScopeDependencySelector takes exclusions. 'Provided' scope is not here to avoid
            // false positive in LinkageChecker.
            new ScopeDependencySelector("test"),
            // OptionalDependencySelector is omitted
            new ExclusionDependencySelector(),
            new FilteringZipDependencySelector());
    session.setDependencySelector(dependencySelector);

    session.setDependencyGraphTransformer(
        new ChainedDependencyGraphTransformer(
            new CycleBreakerGraphTransformer(),
            new JavaDependencyContextRefiner()
        )
    );

    session.setReadOnly();
    return session;
  }
```

**Comment by elharo** [comment]
not sure; I'm working on improving this method now. Maybe we can remove it completely

**Comment by suztomo** [comment]
Experimenting the session.

![image](https://user-images.githubusercontent.com/28604/73971603-2d23ee80-48ed-11ea-9954-b91ae6915319.png)

**Comment by suztomo** [comment]
Still the graph is slightly different.

https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/snapshot/io.grpc_grpc-alts_1.27.0.html#dependency-convergence

![image](https://user-images.githubusercontent.com/28604/73973680-0b2c6b00-48f1-11ea-9c77-9ac075a3d494.png)

**Comment by suztomo** [comment]
The graph does not have the node before the transformer.

**Comment by suztomo** [comment]
It turned out that grpc-alts:1.27.0 depends on google-auth-library-oauth2-http with exclusion of guava:

![image](https://user-images.githubusercontent.com/28604/74061864-fa482c00-49ba-11ea-9daa-58a111ba2523.png)

Therefore, opencensus-contrib-http-util not declaring guava is expected.

Why does the dashboard show the node? It should respect the exclusion element to build dependency graph.

**Comment by elharo** [comment]
search for "exclusion" in the code base. I think I saw a comment about this today, probably in DependencyGraphBuilder.

**Comment by suztomo** [comment]
It seems that our graph resolution logic in levelOrder forgets the effect of exclusion elements applied in 2 level above.

![image](https://user-images.githubusercontent.com/28604/74068075-ad6b5200-49c8-11ea-82ab-5190d364a0f4.png)

**Comment by suztomo** [comment]
The dependency graph in branch zetasql-slowness does not alter the scope written in POMs. Good.

![image](https://user-images.githubusercontent.com/28604/74360435-0fde9c80-4d93-11ea-96e7-b4d2ad4d9cb1.png)


But it throws ArtifactDescriptorException for oracle  artifacts.

**Comment by suztomo** [comment]
Should DependencyGraphBuilder be responsible to resolve artifacts?

![image](https://user-images.githubusercontent.com/28604/74362628-06efca00-4d97-11ea-8059-dbbaeee1390a.png)
