### ISSUE TITLE
JarDumper.resolveMethodReferences(jarFiles, methodReferences)

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#119]
JarDumper to be able to resolve list of method references (`FullyQualifiedMethodSignature`) given list of jar files.

The code would look like this:

```
ResolveResult result = JarDumper.resolveMethodReferences(jarFiles, methodReferences)
```

where

```
class ResolveResult {
   Map<FullyQualifiedMethodSignature, ResolvedLocation> resolvedLocations,
   List<FullyQualifiedMethodSignature> unresolved,
}

class ResolvedLocation {
   String jarFile,
   String classFile
}
```

**Comment by suztomo** [comment]
@garrettjonesgoogle  @elharo I think this is next item to implement. I appreciate if you have any input.

**Comment by garrettjonesgoogle** [comment]
What would the `resolvedLocations` part of the output be used for?

Is `JarDumper` going to contain the bulk of the logic for the static linkage checker? Should it just be called `StaticLinkageChecker`?

**Comment by elharo** [comment]
This seems to assume two passes over the classpath, one to collect the list of methods defined and one to collected the list of methods called. It might be worth doing this in one pass.

**Comment by elharo** [comment]
True files should probably be Path objects. I'm not sure jarFile and classFile are files though. If they're not these variables should be renamed.

**Comment by elharo** [comment]
So is anything is unresolved we have a linkage error? If so do we need the resolvedLocations or can we return a list of unresolved references instead?

**Comment by suztomo** [comment]
> What would the `resolvedLocations` part of the output be used for?

For debugging.

> Should it just be called StaticLinkageChecker?

Good. That sounds better name.

**Comment by garrettjonesgoogle** [comment]
>> What would the resolvedLocations part of the output be used for?

> [suztomo@] For debugging.

`resolvedLocations` sounds somewhat expensive to collect (in terms of memory); it will be much larger than the `unresolved` list. I'd prefer not to carry the baggage around for the purpose of debugging, and figure out another way to debug this. (Maybe we could have an overload of this method for debugging which could return it.)

> [elharo@] This seems to assume two passes over the classpath, one to collect the list of methods defined and one to collected the list of methods called. It might be worth doing this in one pass.

Wouldn't it be simpler to do this in two passes? It seems more complex to do a single pass and manage references correctly. Attempting a single pass seems like it might be premature optimization.

**Comment by suztomo** [comment]
Talked with @elharo , we'll go for 2 paths for now. ResolvedLocation is not needed.
