### ISSUE TITLE
Flaky test testConfigureAdditionalMavenRepositories_notToUseMavenCentral

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1196]
Debugging suggests there might be come caching going on in the static `system` field when run locally. 

```
  private static final RepositorySystem system = RepositoryUtility.newRepositorySystem();
```

[ERROR] Failures: 
[ERROR]   DependencyGraphBuilderTest.testConfigureAdditionalMavenRepositories_notToUseMavenCentral:208 The dependency resolution should fail if Maven Central is not used
[INFO] 
[ERROR] Tests run: 164, Failures: 1, Errors: 0, Skipped: 0

**Comment by suztomo** [comment]
That one often causes problem to me as well. The test expects Maven resolution fails for an artifact that's not available in android repository. However, sometimes the artifact is in our Maven local repository (~/.m2/repository ) and thus the test fails.

**Comment by suztomo** [comment]
After running `rm -rf ~/.m2/repository/com/google/guava/guava/28.2-jre/`, the test succeeds.

However, cloud-opensource-java uses Guava 28.2-jre, thus this is not just the Maven local artifact. There should be other factors making the test fail.
