### ISSUE TITLE
Shall we include gcsio in our BOM

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1205]
Java libraries published from GoogleCloudDataproc/bigdata-interop.

**Comment by elharo** [comment]
It doesn't look very up to date with its own dependencies and they release infrequently. Unless there's customer demand here or this becomes better supported I'm inclined to say no.

**Comment by suztomo** [comment]
Background: I started thinking to apply libraries BOM to Beam to control Google-related dependencies. Gcsio is part of Beam ([BeamModulePlugin.groovy](https://github.com/apache/beam/blob/b95410d/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L430)) but it's not in the BOM.
