### ISSUE TITLE
Document BOM usage for Scala Build Tool

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1248]
We have a high priority customer need for this one.

**Comment by elharo** [comment]
Looks like the answer might be SBT can't do that:

 https://github.com/sbt/sbt/issues/4531

**Comment by elharo** [comment]
updated the wiki

**Comment by suztomo** [comment]
Thank you. https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM#sbt
