### ISSUE TITLE
Failing tests in java 11

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1267]
This might indicate a real problem in our code or the libraries we test or both when running in Java 11:

[ERROR] Failures: 
[ERROR]   LinkageCheckerTest.testFindSymbolProblems_shouldSuppressJvmCIPackage:912 Missing classes from jdk.vm.ci should not be reported
expected to be empty
but was: [Class sun.text.normalizer.UCharacterProperty is not accessible, Class sun.misc.JavaUtilZipFileAccess is not found, Class sun.misc.SharedSecrets is not found, Class sun.misc.PerfCounter is not found, Class sun.util.logging.LoggingSupport is not found]

**Comment by suztomo** [comment]
My guess is “Class sun.text.normalizer.UCharacterProperty is not accessible” is true positive in JDK.

**Comment by suztomo** [comment]
Java 11 build now succeeds as part of pull request checks.
