### ISSUE TITLE
Exclusion file: support Artifact matcher

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1271]
Exclusion file: support Artifact matcher.

Annotated JAR (https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1179) is needed before starting implementing this.

**Comment by elharo** [comment]
Why is this needed? Do we really want to exclude every linkage error from an entire artifact? It seems to me if an artifact is that broken, it shouldn't be in the classpath.

**Comment by suztomo** [comment]
I want this because we cannot fully control JARs in class path. Example is the OOM in beam-hcatalog problem.

**Comment by elharo** [comment]
Can you elaborate on that? How does this help? Under what circumstances should we exclude a complete artifact from checking?

**Comment by suztomo** [comment]
For example, Linkage Check for beam-runners-google-cloud-dataflow-java has ~9000 lines.

https://gist.github.com/suztomo/39caad6347b98f2ef70078649dc70bde

Setting exclusion rules at artifact-level would result in smaller exclusion rules than when setting exclusion rules at class- or package-level.

**Comment by suztomo** [comment]
Closing this for now as we don't find the need so far.
