### ISSUE TITLE
Why does Beam use grpc-google-cloud-pubsub-v1 ?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1279]
Followup of the previous meeting in January 21, 2020:

> Why does Beam use these libraries? “Proto-” ones make sense. Not “grpc-” (This should not be needed). Tomo to check why.

As per Jeff, `com.google.api.grpc:grpc-google-cloud-pubsub-v1` should not be needed in users' code (such as Beam).

# BeamModulePlugin

[BeamModulePlugin](https://github.com/apache/beam/blob/ed8d604/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy) is a Gradle plugin for Beam project and defines library versions in the project.

```
        grpc_google_cloud_pubsub_v1                 : "com.google.api.grpc:grpc-google-cloud-pubsub-v1:$generated_grpc_ga_version",
```
where `def generated_grpc_ga_version = "1.83.0"`. This is the only usage of "grpc-" prefixed artifact in com.google.api.grpc group.

For libraries prefixed with "google-api-services-", BeamModulePlugin defines 6 of them:

```
        google_api_services_bigquery                : "com.google.apis:google-api-services-bigquery:v2-rev20191211-$google_clients_version",
        google_api_services_clouddebugger           : "com.google.apis:google-api-services-clouddebugger:v2-rev20191003-$google_clients_version",
        google_api_services_cloudresourcemanager    : "com.google.apis:google-api-services-cloudresourcemanager:v1-rev20191206-$google_clients_version",
        google_api_services_dataflow                : "com.google.apis:google-api-services-dataflow:v1b3-rev20190927-$google_clients_version",
        google_api_services_pubsub                  : "com.google.apis:google-api-services-pubsub:v1-rev20191111-$google_clients_version",
        google_api_services_storage                 : "com.google.apis:google-api-services-storage:v1-rev20191011-$google_clients_version",
```

# grpc-google-cloud-pubsub-v1

This defines PublisherGrpc and SubscriberGrpc classes in com.google.pubsub.v1 package.

## Usage

Beam's [PubsubGrpcClient](https://github.com/apache/beam/blob/784d18b7ac89f87dd7fbf2861ee877f5b6070276/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubGrpcClient.java#L196
) uses these 2 classes.

```

  /** Return a stub for making a publish request with a timeout. */
  private PublisherBlockingStub publisherStub() throws IOException {
    if (cachedPublisherStub == null) {
      cachedPublisherStub = PublisherGrpc.newBlockingStub(newChannel());
    }
    return cachedPublisherStub.withDeadlineAfter(timeoutSec, TimeUnit.SECONDS);
  }

  /** Return a stub for making a subscribe request with a timeout. */
  private SubscriberBlockingStub subscriberStub() throws IOException {
    if (cachedSubscriberStub == null) {
      cachedSubscriberStub = SubscriberGrpc.newBlockingStub(newChannel());
    }
    return cachedSubscriberStub.withDeadlineAfter(timeoutSec, TimeUnit.SECONDS);
  }
```

The return value (stub) is used in publishing messages to a topic:

```
  @Override
  public int publish(TopicPath topic, List<OutgoingMessage> outgoingMessages) throws IOException {
    PublishRequest.Builder request = PublishRequest.newBuilder().setTopic(topic.getPath());
    for (OutgoingMessage outgoingMessage : outgoingMessages) {
      PubsubMessage.Builder message = outgoingMessage.message().toBuilder();

      if (timestampAttribute != null) {
        message.putAttributes(
            timestampAttribute, String.valueOf(outgoingMessage.timestampMsSinceEpoch()));
      }

      if (idAttribute != null && !Strings.isNullOrEmpty(outgoingMessage.recordId())) {
        message.putAttributes(idAttribute, outgoingMessage.recordId());
      }

      request.addMessages(message);
    }

    PublishResponse response = publisherStub().publish(request.build());
    return response.getMessageIdsCount();
  }
```

# google-api-services-bigquery

Among other classes, this artifact defines classes in `com.google.api.services.bigquery.model`.

## Usage

Among many other places, [BigQueryTableSource](https://github.com/apache/beam/blob/56d17fb/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryTableSource.java#L70) uses `com.google.api.services.bigquery.model.Table` to get table size.

```
import com.google.api.services.bigquery.model.Table;
import com.google.api.services.bigquery.model.TableReference;

...
      Table table = bqServices.getDatasetService(bqOptions).getTable(tableRef);
      Long numBytes = table.getNumBytes();
      if (table.getStreamingBuffer() != null
          && table.getStreamingBuffer().getEstimatedBytes() != null) {
        numBytes += table.getStreamingBuffer().getEstimatedBytes().longValue();
      }

      tableSizeBytes.compareAndSet(null, numBytes);
```

**Comment by suztomo** [comment]
@chingor13 Few months ago, you mentioned that users don't need to use "grpc-" prefixed libraries. Do you see unnecessary usage of these libraries above?

**Comment by chingor13** [comment]
The grpc- libraries contain classes that are generated from the grpc protoc plugin. They _can_ be used to interact with our services if you want the bare-metal grpc experience - you must set up all the channel configs, authentication, etc.

The google-cloud- libraries use an alternate service implementation that leverages gax which simplifies all the authentication and configuration.

**Comment by suztomo** [comment]
Thanks. I guess Beam needs special way to interacts with Google Cloud services as the pubsub gRPC interaction happens in Dataflow environment. Not taking further action.
