### ISSUE TITLE
exclusion files: reason element

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1288]
As per Elliotte in https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1287/files/a307b484bac633a92458ed8cf2d3aab12956d81c#r391851656

> The benefit of using elements and being flexible in what's allowed is that it enables people to fill needs we didn't plan for. It's the eXtensible part of XML. We don't show these today. Tomorrow, who knows? It didn't occur to me when you designed this format that we might want documentation like this, bit now I can see the need.

I think there are two topics here: reason element (v.s. XML comment), and reason element having HTML elements.

# Reason element

# Allowing "reason" elements to have HTML elements

**Comment by suztomo** [comment]
@elharo Would you elaborate how `reason` element would be used?

**Comment by elharo** [comment]
No idea how it will be processed, but hiding useful information in comments is a markup failure. Not every use case is known up front. Design for flexibility.

**Comment by suztomo** [comment]
@elharo We can start implementing this issue when we know how we want to process the elements.

**Comment by suztomo** [comment]
- Element tag name. `<reason>`?
- whether the comment element is to be a child of LinkageError, Source, and/or Target. 
- whether they are optional, one-or-more, or exactly one. Whether they allow HTML elements in them.
- adding the new element into the exclusion rule schema (`linkage-checker-exclusion-relax-ng.xml`) for the new element
