### ISSUE TITLE
Upper Bounds for Every Library at Once

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#129]
We hope to advertise that the libraries included in cloud-oss-bom work together. To make this happen, we need an upper bound check that includes all the libraries in the dashboard/BOM at once. Right now, for instance, there are libraries that are green but import Guava 19.0 because they don't import anything that uses Guava 20.0.

To do this we need to collect maximum dependency version for each library and pick the latest across the set.

**Comment by garrettjonesgoogle** [comment]
I think we should actually remove the "Suggested Dependency Updates" that is derived purely from a per-project analysis, and instead make suggested updates based on the upper bounds of every library at once (basically, suggest the highest found throughout the whole set).
