### ISSUE TITLE
Investigate gRPC 1.28 Linkage Errors

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1296]
Followup of 
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1286#issuecomment-598196225

```
Class io.reactivex.internal.schedulers.NonBlockingThread is not found
Class reactor.core.scheduler.NonBlocking is not found
Class com.sun.jna.Native is not found
Class com.sun.jna.Structure is not found
Class com.sun.jna.platform.win32.WinNT$HANDLE is not found
Class com.sun.jna.ptr.IntByReference is not found
Class com.sun.jna.platform.win32.Kernel32 is not found
Class com.sun.jna.platform.win32.Win32Exception is not found
Class com.sun.jna.Platform is not found
...
```

Todo: find piece of  source code that protects users from NoClassDefFoundError. Very likely it's BlockHound's code using reflection or try-catch surrounding to find the existence of classes.

# Dashboard

Errors in grpc-netty

<img width="760" alt="Screen Shot 2020-03-19 at 10 16 07" src="https://user-images.githubusercontent.com/28604/77076816-bccbbb00-69ca-11ea-89a6-aa7718d1c879.png">

<img width="832" alt="Screen Shot 2020-03-19 at 10 19 41" src="https://user-images.githubusercontent.com/28604/77077127-31065e80-69cb-11ea-98a3-4bf385e46fc0.png">

Gist: https://gist.github.com/suztomo/bbfa68b4259e9fbd7484b900db90d09e

```
Dependency path 'io.grpc:grpc-netty > io.netty:netty-common > io.projectreactor.tools:blockhound' exists in all 80 dependency paths. Example path:
 io.grpc:grpc-netty:1.28.0 (compile)
 / io.netty:netty-codec-http2:4.1.45.Final (compile)
 / io.netty:netty-common:4.1.45.Final (compile)
 / io.projectreactor.tools:blockhound:1.0.1.RELEASE (compile, optional)
```

##  Classes to examine

The following 3 classes are the sources of the references.

- `reactor.blockhound.integration.RxJava2Integration`

- `reactor.blockhound.integration.ReactorIntegration`

- `reactor.blockhound.shaded.net.bytebuddy.agent.VirtualMachine`

**Comment by suztomo** [comment]
# reactor.blockhound.integration.RxJava2Integration

This implements ClassNotFoundException guard:

```
@AutoService(BlockHoundIntegration.class)
public class RxJava2Integration implements BlockHoundIntegration {

    @Override
    public void applyTo(BlockHound.Builder builder) {
        try {
            Class.forName("io.reactivex.Flowable");
        }
        catch (ClassNotFoundException ignored) {
            return;
        }

        builder.nonBlockingThreadPredicate(current -> current.or(NonBlockingThread.class::isInstance));
    }
}
```

**Comment by suztomo** [comment]
# reactor.blockhound.integration.ReactorIntegration

This implements ClassNotFoundException guard:

```
@AutoService(BlockHoundIntegration.class)
public class ReactorIntegration implements BlockHoundIntegration {

    @Override
    public void applyTo(BlockHound.Builder builder) {
        try {
            Class.forName("reactor.core.publisher.Flux");
        }
        catch (ClassNotFoundException ignored) {
            return;
        }
```

**Comment by suztomo** [comment]
# reactor.blockhound.shaded.net.bytebuddy.agent.VirtualMachine


<img width="1204" alt="Screen Shot 2020-03-19 at 10 40 50" src="https://user-images.githubusercontent.com/28604/77079267-213c4980-69ce-11ea-9f2f-45e445d0bafc.png">

```
        /**
         * Attaches to the supplied process id using the default JNA implementation.
         *
         * @param processId The process id.
         * @return A suitable virtual machine implementation.
         * @throws IOException If an IO exception occurs during establishing the connection.
         */
        public static VirtualMachine attach(String processId) throws IOException {
            if (Platform.isWindows()) {
                return attach(processId, new Connection.ForJnaWindowsNamedPipe.Factory());
            } else if (Platform.isSolaris()) {
                return attach(processId, new Connection.ForJnaSolarisDoor.Factory(15, 100, TimeUnit.MILLISECONDS));
            } else {
                return attach(processId, Connection.ForJnaPosixSocket.Factory.withDefaultTemporaryFolder(15, 100, TimeUnit.MILLISECONDS));
            }
        }
```

**Comment by suztomo** [comment]
Doesn't Linkage Checker whitelist classes that catch ClassNotFound?

**Comment by elharo** [comment]
Possibly, if it's done right and it looks like this might be. It's too much for a comment but a detailed write-up, probably in the repo, explaining the case could be linked to.

**Comment by suztomo** [comment]
> Doesn't Linkage Checker whitelist classes that catch ClassNotFound?

No, `ClassDumper.ERRORS_CAUGHT_IN_SOURCE` does not have ClassNotFoundException. Adding ClassNotFoundException to the whitelist solves the first two. But `reactor.blockhound.shaded.net.bytebuddy.agent.VirtualMachine` still stands.

The inner class `reactor.blockhound.shaded.net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaSolarisDoor$Factory`  has invalid reference. We already have the logic to check its outer classes for try-catch for ClassNotFoundException. However, the classes do not have the try-catch. It is `reactor.blockhound.shaded.net.bytebuddy.agent.VirtualMachine$Resolver` that has the try catch. The `VirtualMachine$Resolver` is in the same Java source file, but not an outer class of `VirtualMachine$ForHotSpot$Connection$ForJnaSolarisDoor$Factory`

**Comment by suztomo** [comment]
@elharo I'm thinking to add these findings to a comment in a test case.

**Comment by suztomo** [comment]
@elharo The three source classes check ClassNotFoundException to see whether certain classes are available or not. May I help further to clarify the concern on these BlockHound linkage errors?

**Comment by elharo** [comment]
What seems to be left now are various references to classes in  com.sun.jna.platform from the single class `reactor.blockhound.shaded.net.bytebuddy.agent.VirtualMachine`

Class com.sun.jna.platform.win32.Win32Exception is not found referenced from [ClassFile{jar=/home/elharo/.m2/repository/io/projectreactor/tools/blockhound/1.0.1.RELEASE/blockhound-1.0.1.RELEASE.jar, className=reactor.blockhound.shaded.net.bytebuddy.agent.VirtualMachine}]


Four possibilities I see:

1. True positive
2. Blockhound does not use net.bytebuddy.agent.VirtualMachine and should not include it in the shaded jar.
3. `net.bytebuddy.agent.VirtualMachine` guards against the non-presence of JNA
4. Our code is defective and does not look in the right place for JNA classes, but the regular Java runtime does.

**Comment by elharo** [comment]
decision: add to exclusion file. It is guarded
