### ISSUE TITLE
avoid Guava ClassPath.from in ClassPathEntry

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1320]
Here's what we do:

```
    // Leveraging Google Guava reflection as BCEL doesn't have API to list classes in a jar file
    com.google.common.reflect.ClassPath classPath =
        com.google.common.reflect.ClassPath.from(classLoaderFromJar);
```

Could we read the jar file directly instead without loading the classes? It's just a zip file. That might miss inner classes though.

**Comment by suztomo** [comment]
If reading JAR files is simpler than Guava's API, this is a nice enhancement.

**Comment by elharo** [comment]
I don't know if it's simpler in code, but it should very much be simpler at runtime and possibly faster since it doesn't have to perform class loading.

**Comment by elharo** [comment]
Inner classes are compiled to outer classes in the byte code. That is, every class is a zip entry. It might require some decoding of the class names but it should be possible.

**Comment by suztomo** [comment]
Right, even if it gets a bit longer, as long as reading JAR files is noticeably faster than Guava's API then that's a nice idea.

Is this idea to solve the beam-hcatalog OOM problem (#1256 )?

**Comment by elharo** [comment]
Not specifically, though that would be a nice outcome. 

My main concern here is the risk of classpath pollution between different chunks of code.

**Comment by suztomo** [comment]
>  classpath pollution between different chunks of code.

What is that in our case with Guava's ClassPath?

**Comment by suztomo** [comment]
Memo: the stacktrace of #1256 shows the OOM happened before calling LinkageChecker. It's before reading the content of JAR files. Therefore, avoiding Guava's ClassPath will not solve the OOM problem.
