### ISSUE TITLE
Enforcer Rule Integration Test?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1345]
How can we ensure the enforcer rule works fine as part of precommit checks?

# Consideration

The check needs to pick up right version of linkage-checker-enforcer-rule.

The check needs to have the enforcer rule plugin to read the XML configuration to detect errors to detect errors like https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1343.

# Options

## Directories for Integration Tests

- `enforcer-rules/integration-test/project-with-exclusion-file/pom.xml`
- `enforcer-rules/integration-test/project-with-report-only-reachable/pom.xml`
...

and a shell script to `cd` these directories and run `mvn verify`?

## Maven's way to run integration tests

https://cwiki.apache.org/confluence/display/MAVEN/Creating+a+Maven+Integration+Test. This requires `AbstractMavenIntegrationTestCase` in Maven's [core-integrating-testing module](https://github.com/apache/maven-integration-testing/blob/master/core-it-support/maven-it-helper/src/main/java/org/apache/maven/it/AbstractMavenIntegrationTestCase.java). As we're not testing Maven itself, the class might not be suitable for our use case.

## Maven checkstyle-plugin's tests

Checkstyle plugin is good candidate to follow the testing setup.

https://github.com/apache/maven-checkstyle-plugin/tree/master/src/it/MCHECKSTYLE-338

```
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>@pom.version@</version>
```

<img width="400" alt="Checkstyle test has verify.groovy" src="https://user-images.githubusercontent.com/28604/79601090-3d5b0580-80b6-11ea-98e7-f63c7bf61019.png">

It has "run-its" profile to execute [maven-invoker-plugin](http://maven.apache.org/plugins/maven-invoker-plugin/):

```
  <profiles>
    <profile>
      <id>run-its</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-invoker-plugin</artifactId>
            <configuration>
              <goals>
                <goal>clean</goal>
                <goal>site</goal>
...
```

> The Invoker Plugin is used to run a set of Maven projects. The plugin can determine whether each project execution is successful, and optionally can verify the output generated from a given project execution.

This plugin is in particular handy to perform integration tests for other Maven plugins. The Invoker Plugin can be employed to run a set of test projects that have been designed to assert certain features of the plugin under test.

**Comment by elharo** [comment]
We might be able to copy how the Maven Project runs integration tests for the various plugins. See https://cwiki.apache.org/confluence/display/MAVEN/Creating+a+Maven+Integration+Test

**Comment by suztomo** [comment]
Thank you. Added to the options.
