### ISSUE TITLE
Show the two branches of the dependency tree from a linkage error

### ISSUE THREAD

**Issue by marquiswang** [GoogleCloudPlatform/cloud-opensource-java#1368]
When a linkage error is reported, it can be sometimes very difficult to tell where the conflict is coming from:

For example, I get this:
```
(org.apache.ant:ant:1.7.1) org.apache.tools.ant.IntrospectionHelper$CreateNestedCreator's method store(Object arg1, Object arg2) is not implemented in the class;
  referenced by 1 class file
    org.apache.tools.ant.IntrospectionHelper$NestedCreator (ant:ant:1.6.2)
```

But when I run `mvn dependency:tree -Dverbose`, I can't find any references to ant:ant:1.6.2. It's not entirely clear to me why the dependency tree doesn't show this, but I suspect it's due to https://issues.apache.org/jira/browse/MENFORCER-277. Regardless, if this rule logged the dependency branches that would eliminate the need to run dependency:tree at all.

**Comment by suztomo** [comment]
Thank you for posting the question. The dependency tree used by the Linkage Checker is slightly different from the one used by Maven. For example, Linkage Checker's dependency tree includes optional or provided dependencies of transitive dependencies, while Maven does not include the in the tree.

https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java#L69

Created https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1369 .

**Comment by marquiswang** [comment]
Thanks @suztomo! This will be real helpful. I've already set reportOnlyReachable but I have a few errors left that I'm not sure where they've come from.

**Comment by suztomo** [comment]
@marquiswang We released [Linkage Checker Enforcer Rule version 1.4.0](https://search.maven.org/artifact/com.google.cloud.tools/linkage-checker-enforcer-rules/1.4.0/jar) that outputs path to problematic artifacts. Would you try this version?

We also fixed a bug related to reportOnlyReachable. You might not observe the previous errors with the option.

**Comment by marquiswang** [comment]
@suztomo 
Sorry for the delay, the github notification about your response got marked as spam.

This works amazing, thanks.

My problem right now is that for some dependencies (logback and spring are common offenders, the optional dependencies conflict with each other (see below). Why do you consider optional dependencies anyways? Aren't they guaranteed to not cause a linkage error unless the dependency is added non-optionally somewhere as well?

```
(org.codehaus.groovy:groovy-all:2.4.0) groovy.servlet.ServletBinding$ServletOutput$1's method isReady() is not implemented in the class;
  referenced by 1 class file
    javax.servlet.ServletOutputStream (javax.servlet:javax.servlet-api:3.1.0)
```

```
[ERROR] Problematic artifacts in the dependency tree:
org.codehaus.groovy:groovy-all:2.4.0 is at:
  internal:dependency:jar:master-SNAPSHOT / ch.qos.logback:logback-classic:1.2.3 (runtime) / org.codehaus.groovy:groovy-all:2.4.0 (compile, optional)
javax.servlet:javax.servlet-api:3.1.0 is at:
  internal:dependency:jar:master-SNAPSHOT / ch.qos.logback:logback-classic:1.2.3 (runtime) / javax.servlet:javax.servlet-api:3.1.0 (compile, optional)
```

**Comment by suztomo** [comment]
Linkage Checker includes optional dependencies because it captures more potential errors. Your understanding on optional dependency is accurate; as long as the artifact is not in class path, you don't have to worry about the linkage errors reported there.

**Comment by marquiswang** [comment]
Yeah, I figured as much. However, I would like to be able to automatically fail my build if there are linkage errors, so it is difficult to ignore these false positives. Is there an option that I'm not seeing to ignore optional dependencies? If not, can this be added?

**Comment by suztomo** [comment]
As of now, there's no option to ignore linkage errors based on the optional flag.

To suppress known linkage errors, you can use exclusion file: 
```
 <exclusionFilterFile>linkage-checker-exclusion-rules.xml</exclusionFilterFile>
```
https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/Linkage-Checker-Enforcer-Rule

I'll get back to you after we discuss the feasibility of ignoring optional dependencies.

**Comment by elharo** [comment]
It's not necessarily true that you can ignore optional dependencies. It depends on why they're marked optional and whether the optional dependencies might be properly guarded. They're not always.

For instance, I recently encountered a linkage error in Apache Maven as a result of the very widely used jdom:jdom:1.0 declaring jaxen and saxpath to be optional. However those two artifacts are linked to from the core JDOM code and there are no guards at all. The JDOM thinking was that if you didn't call certain methods or use certain packages, you didn't need them. True enough, but the same could be said for any linkage error.

JDOM shipped a library that has linkage errors out of the box unless you add the optional dependencies to your own project.

**Comment by suztomo** [comment]
@marquiswang says there's a case (not always) where linkage errors reported on optional dependencies cause _false_ positive.

@elharo says there's a case where linkage errors reported on optional dependencies cause _true_ positive.

Two statements are not contradicting to each other.

**Comment by elharo** [comment]
Which is what makes this tricky. Optional (and provided) dependencies are a mess and not incredibly well thought out in Maven, IMHO. I'm not sure what either of us is claiming is a true or a false positive. It seems more subtle than that.

I think @marquiswang's case is that if the optional dependency isn't included in the project, then there's no linkage error but if it is included there is. A specific example of such a project, i.e. a reproducible test case, would be helpful here.

I'm claiming that in the case of jdom:jdom:1.0 if the optional dependency isn't included in the project, then there is a linkage error but if it is included there isn't. 

Linkage errors are a function of classpaths. There's no ambiguity of this type about whether a classpath has linkage errors or not, because classpaths don't have optional elements. The question is purely about how the classpath is formed from the Maven POMs.

**Comment by marquiswang** [comment]
I definitely agree with @elharo that optional dependencies are a mess.

As I understand it, optional dependencies are intended to be used with runtime guards to make sure that code using the dependency is never called unless the dependency is on the classpath. Thus, I see two classes of bugs that can happen with optional dependencies:

1. A dependency was declared optional, but the runtime guard is missing or broken, causing a runtime exception when the code that uses the dependency was called. This sounds like what you described with the jdom dependency. I don't think that the linkage checker can catch this at all, since the problem isn't that the dependency is incompatible with the usage, but that the dependency is missing entirely.

2. A dependency was declared optional, and is correctly guarded against, but it is incompatible with another dependency. This will cause an error when this dependency is activated by adding it as non-optional. If we ignore optional dependencies, the linkage checker will correctly catch this when it is a problem, because there will be a duplicate non-optional dependency to look at.

Do you guys think there's anything that I'm missing?

**Comment by suztomo** [comment]
> The question is purely about how the classpath is formed from the Maven POMs.

Yes, mostly. Simply omitting optional dependencies would generate another set of linkage errors. For example, there would be linkage errors for the missing classes that would otherwise exist in the optional dependencies. We need to take care of them too.


@marquiswang I think "1. " is accurate. For "2. ", would you elaborate a bit on this? >  If we ignore optional dependencies, the linkage checker will correctly catch this when it is a problem, because there will be a duplicate non-optional dependency to look at.


There are 2 project styles:
- A library project that cannot know runtime class path. It does not know whether optional dependencies are available at runtime. (Elliotte's jdom case)
- A runtime (or "non-library"?) project that declares runtime class path. It knows which optional dependencies are selected or not.

**Comment by marquiswang** [comment]
For the below, I'm ignoring errors where one jar assumes that the classpath will contain an optional dependency, but it is missing. Any jar that includes an optional dependency has an appropriate runtime guard against calling that dependency if it isn't actually included. The easiest way is to do a check:
```
try {
 Class.forName( "my.optional.depedency.Foo" );
} catch( ClassNotFoundException e ) {
 // Avoid using Foo
}
```

As I said in (1) I don't think this is something that we can check for programmatically. 

From this, we can conclude that all code that references an optional dependency is dead code unless that dependency is also included as a non-optional dependency somewhere else in the dependency tree. Therefore, I think it should be safe to ignore optional dependencies entirely unless there is also a non-optional dependency on the same jar.

Does that make sense?

I guess this is also assuming there are no other jars with the same fully-qualified class name.

**Comment by elharo** [comment]
We can and do check to see if there's a runtime guard before reporting a linkage error. 
We do not assume that a jar that includes an optional dependency has an appropriate runtime guard against calling that dependency.

**Comment by suztomo** [comment]
That's an interesting idea > because Java code usually references classes in optional dependencies though the try-catch guard, omitting optional dependencies is not going to increase additional linkage errors for missing classes.

(Linkage Checker indeed suppresses linkage errors on classes that has try-catch for ClassNotFoundException)

**Comment by marquiswang** [comment]
I say that it is impossible to check for runtime guards because they can be more subtle than a simple try-catch. A library could use a try-catch to set a boolean field, then use that one elsewhere rather than doing the try-catch again. Or any number of other workarounds. I'm not actually familiar with how logback, spring, or other fairly common libraries use optional dependencies, but I think it is irrelevant.

My point is that:

1. An optional dependency that isn't called at runtime will not cause a linkage error and can be safely ignored.
2. An optional dependency that is called at runtime but isn't depended on somewhere else in the dependency tree is going to fail because of the missing jar, not because of a binary incompatibility, so the linkage checker can't detect this anyways.
3. An optional dependency that is called at runtime and is depended on somewhere else in the dependency tree is thus the only time we need to worry about an optional dependency.
