### ISSUE TITLE
Automation to push staging repo to Maven Central

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1388]
Current Rapid pipeline uses curl. Maven plugin to publish artifacts has option to publish automatically.

**Comment by elharo** [comment]
Is there a way we can configure Rapid to publish automatically?

**Comment by elharo** [comment]
This is the script that uploads the jar file:

https://cs.corp.google.com/piper///depot/google3/cloud/java/tools/common/release_publish.sh?q=cloud/java/tools/common/release_publish.sh&sq=package:piper+file://depot/google3+-file:google3/experimental&g=0&l=1

**Comment by elharo** [comment]
code looks like this:

```
# Usage: UploadJAR <session ID> <file>
# Uploads the bundled JAR file to the Nexus Staging Repository.
UploadJAR() {
  curl 'https://oss.sonatype.org/service/local/staging/bundle_upload' \
    -H "Cookie: NXSESSIONID=$1" -H 'Content-Type: multipart/form-data' \
    --compressed -F "file=@$2" --fail
}
```
how do we modify that to release?

**Comment by elharo** [comment]
can't find anything in the REST API about this:

https://help.sonatype.com/repomanager3/rest-and-integration-api

Perhaps spelunk through the maven-deploy-plugin code?

**Comment by elharo** [comment]
or rather mvn nexus-staging:release

**Comment by elharo** [comment]
see here for an example of auto releasing using that plugin:

https://github.com/googleapis/java-shared-config/blob/master/.kokoro/release/stage.sh

**Comment by elharo** [comment]
Here's that plugin including a source jar:

https://repo1.maven.org/maven2/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.8/

**Comment by elharo** [comment]
ant tasks might fit into our workflow a little better:

https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment#ConfiguringYourProjectforDeployment-DeploymentwiththeNexusStagingAntTasks

**Comment by elharo** [comment]
perhaps relevant: https://github.com/jenkinsci/artifact-promotion-plugin

**Comment by suztomo** [comment]
Jeff has told me this is his script:
https://source.corp.google.com/piper///depot/google3/apiserving/libgen/tools/maven_deploy.py;l=577 (undocumented sonatype API).
