### ISSUE TITLE
Linkage Checker rule reporting not accessible field for project of packaging `war`

### ISSUE THREAD

**Issue by pzygielo** [GoogleCloudPlatform/cloud-opensource-java#1401]
I'm troubled with Linkage Checker rule reporting not accessible field for project of packaging `war`.
[Example project](https://github.com/pzrep/LinkageChecker-and-servlet/) (with rule enabled in [enable_LC_rule](https://github.com/pzrep/LinkageChecker-and-servlet/tree/enable_LC_rule) branch) has two almost identical modules, with the only difference in packaging (and artifactId):
```
$ diff --recursive webapp asjar
diff --recursive webapp/pom.xml asjar/pom.xml
9,10c9,10
<   <artifactId>webapp</artifactId>
<   <packaging>war</packaging>
---
>   <artifactId>asjar</artifactId>
>   <packaging>jar</packaging>
```
Having the same enforcer configuration the `asjar` module verifies successfully, while the `webapp` reports following:
```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-on-verify) @ webapp ---
[ERROR] Linkage Checker rule found 1 error. Linkage error report:
(com.github.pzrep.LinkageChecker-and-servlet:webapp:1-SNAPSHOT) pzrep.ReportServlet's field inv is not accessible;
  referenced by 1 class file
    pzrep.ReportServlet (com.github.pzrep.LinkageChecker-and-servlet:webapp:1-SNAPSHOT)

[ERROR] Problematic artifacts in the dependency tree:
com.github.pzrep.LinkageChecker-and-servlet:webapp:1-SNAPSHOT is at:
  com.github.pzrep.LinkageChecker-and-servlet:webapp:war:1-SNAPSHOT

[WARNING] Rule 0: com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule failed with message:
Failed while checking class path. See above error report.
```
Interestingly - when fields are [made public](https://github.com/pzrep/LinkageChecker-and-servlet/tree/public), LC no longer complains.

**Comment by suztomo** [comment]
Thank you for reporting the issue. Linkage Checker is supposed to  pass the field access from within the same class.

I’ll look into this.

**Comment by suztomo** [comment]
I'm able to reproduce the issue (thank you for the example project with the branch).

Note for myself:

Linkage Checker unexpectedly recognizes `WEB-INF.classes.pzrep.ReportServlet` and `pzrep.ReportServlet` different classes.

<img width="1437" alt="Screen Shot 2020-05-13 at 10 55 51" src="https://user-images.githubusercontent.com/28604/81828987-6b423700-9508-11ea-8204-ad03ff661d30.png">

I think I implemented a logic to avoid this somewhere. Digging further.

**Comment by pzygielo** [comment]
Thank you for investigating this, @suztomo.

**Comment by suztomo** [comment]
@pzygielo We released Linkage Checker enforcer rule version 1.4.1 to resolve this issue. It should be available in few hours in Maven Central. Would you check whether the version solves the 'war' packaging problem?

**Comment by pzygielo** [comment]
@suztomo I've checked 1.4.1, and it no longer reports violation for war. Thank you for fast fix and release.

**Comment by suztomo** [comment]
Thank you for confirmation.
