### ISSUE TITLE
Release script should create PR

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1428]
The release script pushes a branch to Github. It should also create the PR at the same time rather than requiring us to do that in the UI.

**Comment by suztomo** [comment]
GitHub CLI (https://github.com/cli/cli) should work for such tasks.

**Comment by elharo** [comment]
I was able to create a PR from the cmmand line using gh and

```
 gh pr create -a suztomo -f
```

Caveats:

1. gh has to be manually installed first.
2. I still had to authenticate in a web browser.

**Comment by suztomo** [comment]
Nice.
