### ISSUE TITLE
Gradle plugin: how should the Gradle plugin build dependency graph?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1454]
Question: how should Gradle plugin build dependency graph?

As of now

- The BOM Dashboard uses our DependencyGraphBuilder
- LinkageCheckerMain uses our DependencyGraphBuilder
- LinkageCheckerEnforcerRule
  - It uses Maven's ProjectDependenciesResolver for non-BOM project
    It takes dependencyManagement into account.
  - It uses our DependencyGraphBuilder for BOM project

What about a Gradle project?

If we can perfectly implement Gradle's dependency graph, we can use DependencyGraphBuilder.

**Comment by elharo** [comment]
@suztomo subsumed by #2007 ?

**Comment by suztomo** [comment]
This issue was to take notes when I was building the Gradle plugin. It's done.
