### ISSUE TITLE
Optional handling

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1464]
Use [OptionalDependencySelector](https://maven.apache.org/components/resolver-archives/resolver-LATEST/maven-resolver-util/apidocs/org/eclipse/aether/util/graph/selector/OptionalDependencySelector.html) to more closely match Maven's classpath.

**Comment by elharo** [comment]
Not immediately  clear what to do when we're passed a list of dependencies or artifacts, as for a BOM. Do we resolve no optional dependencies or every optional dependency that's a direct dependency of an artifact in the list?

**Comment by suztomo** [comment]
For list of artifacts, we want to ensure that we can use them without dependency conflicts. So how about checking a dependency tree with an empty root that has the list of artifacts as dependencies? (This is what current Linkage Checker / DependencyGraphBuilder does)
