### ISSUE TITLE
Identify Difference of Dependency Graphs between Gradle and Maven

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1487]
# Maven picks the closest while Gradle picks the latest 

# Gradle does not respect Maven's scope?

Gradle reads Maven's scopes and adds the dependencies to corresponding configuration (classpath) if necessary.

Questions
- Does Gradle include provided-scope transitive dependencies?
  Ben observed it does https://github.com/mesos/mesos-rxjava/blob/master/pom.xml#L141-L151
- I don't see it includes provided-scope dependencies. https://github.com/suztomo/gradle-behaviors/tree/master/gradle-and-provided-scope
- I see it includes runtime-scope dependencies to runtimeClasspath: https://github.com/suztomo/gradle-behaviors/tree/master/gradle-and-runtime-scope, but not compileClasspath. What's the rule of this behavior?

# Gradle does not respect profiles in pom.xml

- Tested with google-cloud-firestore:1.32.0, which relies on Maven profiles to add dependencies. https://github.com/suztomo/gradle-behaviors/tree/master/gradle-and-java9-profile. Gradle ignores Maven profiles.

**Comment by elharo** [comment]
subsumed in https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/2007
