### ISSUE TITLE
LinkageError class

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1520]
Before this change, the result of LinkageChecker.findSymbolProblems is `Multimap<SymbolProblem, ClassFile>`. This is a representation of many-to-many relationship between class and (missing) symbols. However, the absence of a exact class that represents a linkage error makes our code difficult to follow.

Therefore, this issue creates a class that represent LinkageError:
- Target symbol
- Source class
- reason
- annotation (nullable)

Note that we may have to change the counting of linkage errors in the dashboard. Or renaming it to count problematic symbols.

**Comment by elharo** [comment]
We might want to handle classpaths and classpath entries first. Instead of source class there would be a classpath entry.

**Comment by suztomo** [comment]
@elharo I created a proposal of the refactoring. Would you check this? go/jdd-linkage-error-class

**Comment by suztomo** [comment]
LinkageProblem class has been created.
