### ISSUE TITLE
Enhancement MethodSymbol.toString() on clarity and return type

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1541]
Current: `com.google.common.base.Verify's method verify(boolean, String, Object)`

New

- 1:  `void com.google.common.base.Verify#verify(boolean, String, Object)`
- 2: `com.google.common.base.Verify's method void verify(boolean, String, Object)`
- 3: `com.google.common.base.Verify#verify(boolean, String, Object) (return type: void)`

# Return Type

As of now, MethodSymbol's toString does not show the return value of the method symbol. As JVM looks up method by its descriptor which includes return value type, the information seems important. Yet I haven't seen NoSuchMethodError that originated by the return value type change.

https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/116#issuecomment-451583384

# Usage

The MethodSymbol.toString is used in output of LinkageProblems:

```
(com.google.guava:guava:20.0) com.google.common.base.Verify's method verify(boolean, String, Object) is not found;
  referenced by 3 class files
    io.grpc.internal.ServiceConfigInterceptor (io.grpc:grpc-core:1.17.1)
    io.grpc.internal.JndiResourceResolverFactory (io.grpc:grpc-core:1.17.1)
    io.grpc.internal.DnsNameResolver (io.grpc:grpc-core:1.17.1)
```

**Comment by elharo** [comment]
I'm not sure how much this matters. Java can't overload methods based on return value types.

**Comment by suztomo** [comment]
@elharo That may explain why we see not many NoSuchMethoErrors due to return type. People don't often change return type of a function over different versions of a library.

**Comment by suztomo** [comment]
Old issue https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/671 that stripped the return type.

**Comment by suztomo** [comment]
I like the clarity of using "#". But still I don't like ignoring the return type. How about appending the return type?

@elharo What do you think about this format? >  `com.google.common.base.Verify#verify(boolean, String, Object) (return type: void)`

**Comment by suztomo** [comment]
The recent protobuf problem highlights the need of showing the return type.

![image](https://user-images.githubusercontent.com/28604/91387455-56fa1f80-e803-11ea-95f3-2bacede611e7.png)

**Comment by elharo** [comment]
Is that what we want? or should we change the message from "is not found" to "has the wrong return type" or some such thing?

**Comment by suztomo** [comment]
That enhancement in the message is nice. However, it involves changing the data type that describes which part of MethodSymbol changed.

This issue is about MethodSymbol's toString currently omitting return type information.

**Comment by elharo** [comment]
This strikes me as overly verbose. If the problem is that the method is found but the return type has changed, then that's what we should say. We shouldn't say the method is missing at all.

**Comment by suztomo** [comment]
What do you think of the identity of a method?

1. Its name
1. Its name and argument types
1. Its name, argument types, and return type

(JVM's error message follows the last one. We can be more user-friendly.)
