### ISSUE TITLE
Release requirement for 1.4.4-dependencies

### ISSUE THREAD

**Issue by yangnuoyu** [GoogleCloudPlatform/cloud-opensource-java#1543]
Hi,

We are building a similar dashboard as the one in the repo for google-cloud-bom and we need a method called "buildVerboseDependencyGraph" in com.google.cloud.tools:dependencies. The method is package-protected in current version of dependencies (v1.4.3) so we cannot actually use it right now, but it has been changed to public in v1.4.4-SNAPSHOT. 

Is that possible to release the new version of com.google.cloud.tools:dependencies quickly so we can use the method?

**Comment by suztomo** [comment]
You don't need to use the method. You can use other public methods of DependencyGraphBuilder to a build dependency graph.

**Comment by elharo** [comment]
Whichever method is used, we should think about our release process and commitments if other projects are going to depend on this library. Perhaps at next week's Tuesday 4:00.

**Comment by suztomo** [comment]
An option: we create the BOM content comparison tool as a generic tool (not specific to google-cloud-bom) and place it in cloud-opensource-java repository?

**Comment by suztomo** [comment]
To check: whether the dashboard really need buildVerboseDependencyGraph, rather than other public methods that builds graphs.

**Comment by suztomo** [comment]
Closing in favor of https://github.com/googleapis/java-cloud-bom/pull/748 . The dependencies module 1.5.0 is also released.
