### ISSUE TITLE
Create ClassPathResult instance from Gradle classes

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1556]
Can a Maven project develop a function with Gradle-related classes?

# Some outdated Maven artifacts in Gradle repository

The URL below provides old Gradle API artifacts, but not all.

https://repo.gradle.org/gradle/libs-releases-local/org/gradle/gradle-core-api/

**Comment by elharo** [comment]
Is it possible these are simply in a different repo? I.e. https://repo.spring.io/plugins-release/ instead of Maven Central?

**Comment by suztomo** [comment]
Posted a question. https://discuss.gradle.org/t/developing-gradle-plugin-as-a-maven-project/37185

**Comment by elharo** [comment]
We could copy the jar into our repo and use a local dependency:

https://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-to-a-maven-project

**Comment by suztomo** [comment]
Closing this issue in favor of https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1651.

The original task of "Create ClassPathResult instance from Gradle classes" is already implemented in the Gradle plugin.
