### ISSUE TITLE
Multiple Version dashboard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#158]
The dashboard should work across multiple versions so we can measure and show progress as the cloud-oss-bom evolves.

Maybe figure out how to track metrics of some kind?

**Comment by suztomo** [comment]
Memo:

Dashboard URL https://storage.googleapis.com/cloud-opensource-java-dashboard/dashboard/target/dashboard/dashboard.html "com.google.cloud:libraries-bom:1.2.0-SNAPSHOT"

2 versions: versions of BOM and DashboardMain.

**Comment by elharo** [comment]
fixed
