### ISSUE TITLE
Error for unimplemented method from interface is backwards?

### ISSUE THREAD

**Issue by marquiswang** [GoogleCloudPlatform/cloud-opensource-java#1603]
I think the direction of the reference is backwards when complaining about an unimplemented method.  For example, I got the following error:

```
(cglib:cglib:2.2) net.sf.cglib.transform.ClassVisitorTee's method visitMethod(int, String, String, String[], org.objectweb.asm.Attribute) is not implemented in the class;
  referenced by 1 class file
    org.objectweb.asm.ClassVisitor (asm:asm:1.5.3)
  Cause:
    Unknown
```

However, ClassVisitor is the interface and ClassVisitorTee is the implementation. So I believe the error message should say:

```
(asm:asm:1.5.3) org.objectweb.asm.ClassVisitor's method visitMethod(int, String, String, String[], org.objectweb.asm.Attribute) is not implemented in the class;
  referenced by 1 class file
    net.sf.cglib.transform.ClassVisitorTee (cglib:cglib:2.2)
  Cause:
    Unknown
```

I believe you also need to put the exclusion backwards:

```
    <LinkageError>
        <Target>
            <Class name="net.sf.cglib.transform.ClassVisitorTee"/>
        </Target>
        <Source>
            <Class name="org.objectweb.asm.ClassVisitor"/>
        </Source>
    </LinkageError>
```

which is especially weird since you might need to reverse the Target/Source if ClassVisitorTee is calling a method that doesn't exist in this version of ClassVisitor.

**Comment by suztomo** [comment]
That's a good point. I remember I designed the source and target in the current manner because I had difficulty in formatting error message.

Reading your suggested message, it makes more sense. Let me revisit the design and I'll get back to this issue.

**Comment by elharo** [comment]
As discussed yesterday we should do away with the "referenced by" language for this case. A good message here is something like

net.sf.cglib.transform.ClassVisitorTee does not implement the method visitMethod(int, String, String, String[], org.objectweb.asm.Attribute) from the interface org.objectweb.asm.ClassVisitor
    
We might need to rethink how we create the error messages for different kinds of linkage errors.
