### ISSUE TITLE
Can Linkage Checker detect the bad Java8-incompatible byte code

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1605]
Can Linkage Checker (Linkage Monitor) detect the wrong byte code that does not work with Java 8 (case https://github.com/protocolbuffers/protobuf/issues/7827)

Wrong byte code for Java8 that has reference to `CharBuffer CharBuffer.flip()` (`java.nio.CharBuffer.flip()Ljava/nio/CharBuffer`). In JRE 8, it's `Buffer Buffer.flip()` (the return type is different).

As of now, references to all system classes (including `java.nio.CharBuffer`) are skipped.

**Comment by suztomo** [comment]
For protocolbuffers/protobuf#7827, could Linkage Monitor detect this if Linkage Checker is capable to detect the invalid references?

**Comment by elharo** [comment]
This is a really interesting one. Some take-aways:

1. The compiler doesn't catch all linkage errors, even to classes in the JDK.
2. We should report errors that the project (here Kristen) can't fix so they can understand them and report the errors to the team that can fix them.

**Comment by cpovirk** [comment]
Nice. It sounds like this will check for compatibility against _the JDK that you're using to build_? So, if you want to check for compatibility with JDK 8, then you'll need to build with JDK 8? That makes it helpful for detecting problems in your dependencies but not necessarily helpful for detecting problems in your own code (since you'd already detect/avoid these by building with JDK 8 in the first place). That's fine; I had just been initially hoping for [an improvement on Animal Sniffer](https://github.com/protocolbuffers/protobuf/issues/7827#issuecomment-676563016), too.

**Comment by suztomo** [comment]
> compatibility against the JDK that you're using to build?

Yes, it detect the compatibility with the JDK Linkage Checker is running on. 

If we enhance the check script to build protobuf-java in Java 11 and running Linkage Checker with Java 8, https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1607 should detect the invalid method references.

Memo: script for current check  https://github.com/protocolbuffers/protobuf/blob/master/tests.sh#L252 uses Java 8 for both.

**Comment by cpovirk** [comment]
Thanks.

If you're interested, it is probably possible to detect problems even when building with Java 11: Java 9+ comes bundled with API signatures of not only the current version of Java but also of older versions. See `$JAVA_HOME/lib/ct.sym`, which contains files like `876/java/nio/ByteBuffer.sig`, which I believe is just a classfile that contains the signatures of `ByteBuffer` under Java 6, 7, and 8.

That still requires that users _tell_ the Linkage Checker which version of Java to check against. I don't suppose it possible to guess a sensible default based on the `<source>`, `<target>`, or `<release>` configuration for plugins like `maven-compiler-plugin`??

**Comment by suztomo** [comment]
@cpovirk Thank you for information.
