### ISSUE TITLE
Private subclasses of public classes should not be reported as linkage errors

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1608]
Followup of https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1599#issuecomment-675056070. It was a false positive.

`com.sun.tools.internal.ws.wscompile.WsgenOptions` (source) references `com.sun.xml.internal.ws.api.BindingID$SOAPHTTPImpl` (target). The latter is a private class. Linkage Checker detected it as a linkage error. However, the reference turned out to be not harmful. This is because the source class is not instantiating the private class or declaring a variable with the type.

One of the referencing method is the code below:

```
// in WsgenOptions.java
  BindingID getBindingID(String protocol) {
    if (protocol.equals("soap1.1")) {
      return BindingID.SOAP11_HTTP;
    } else if (protocol.equals("Xsoap1.2")) {
      return BindingID.SOAP12_HTTP;
    } else {
      String lexical = (String)this.nonstdProtocols.get(protocol);
      return lexical != null ? BindingID.parse(lexical) : null;
    }
  }
```

Here, `BindingID.SOAP11_HTTP` has type `com.sun.xml.internal.ws.api.BindingID$SOAPHTTPImpl` (private class), which is a subclass of `BindingID` class. As WsgenOptions is not touching the private class, calling the `getBindingID` method does not cause a `LinkageError` at runtime.

# Simplified Example

Suppose we have the following class `A`, `B`, and `C`:

```
package foo;

public class A {
  public static final B f = new B();

  private static class B extends A {
  }
}
```

```
package foo;

public class C {
  public static void main(String[] arguments) {
    A a = A.f;
    System.out.println(a);
  }

  void f(A.B b) { // This should fail. How?
    System.out.println(b);
  }
}
```

When compiled, `C`'s class file contains a reference to (private) `A$B` class. Linkage Checker would report this reference as a linkage error, simply because `A$B` is not accessible from `C`. However, this is a false positive as the code compiles and run without a problem. 

```
  Compiled from "C.java"
Constant pool:
...
   #3 = Fieldref           #23.#24        // foo/A.f:Lfoo/A$B;
...
  #23 = Class              #32            // foo/A
  #24 = NameAndType        #33:#37        // f:Lfoo/A$B;
...
  #32 = Utf8               foo/A
  #33 = Utf8               f
  #34 = Class              #41            // foo/A$B
  #37 = Utf8               Lfoo/A$B;
...
  #41 = Utf8               foo/A$B
```

Interestingly the field `#34` is not referenced by other constant pool entries or byte code. How about the case of `com.sun.tools.internal.ws.wscompile.WsgenOptions`?

`com.sun.tools.internal.ws.wscompile.WsgenOptions` has the class reference  ([javap output](https://gist.github.com/suztomo/482d33f3f7c56f99ad19cd91cbc4470d)) used in InnerClasses attribute:

```
#392 = Class              #408          // com/sun/xml/internal/ws/api/BindingID$SOAPHTTPImpl
...
InnerClasses:
     private static final #393= #392 of #300; //SOAPHTTPImpl=class com/sun/xml/internal/ws/api/BindingID$SOAPHTTPImpl of class com/sun/xml/internal/ws/api/BindingID
```

https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.6

> If the constant pool of a class or interface C contains at least one CONSTANT_Class_info entry (§4.4.1) which represents a class or interface that is not a member of a package, then there must be exactly one InnerClasses attribute in the attributes table of the ClassFile structure for C.

How about "If a class reference is only used by the InnerClasses annotation, we skip it"?

# Java Language Specification: 12.3.3. Resolution of Symbolic References

https://docs.oracle.com/javase/specs/jls/se7/html/jls-12.html#jls-12.3.3

For constructor, we can check`new`. But it cannot detect wrong access of `A.B`

How about "If a class reference is only used by NameAndType, we ignore it"?

**Comment by elharo** [comment]
Nice analysis. This seems like a high priority to fix. It is not exclusive to JDK classes, and private or non-public subclasses of public types are a common pattern in OO design in general and Java in particular.

**Comment by suztomo** [comment]
@elharo I'm thinking to fix this by reading byte code of the (source) class file. It's a true linkage error only when the class reference is used in
- Calling constructor of the class,
- Accessing the field of the class, or
- Accessing the method of the class

What do you think?

**Comment by suztomo** [comment]
Actually without subclassing, the case still stands.

```
package foo;

public class A {
  public static final B f = new B();

  private static class B {
  }
}
```

```
package foo;

public class C {
  public static void main(String[] arguments) {
    System.out.println(A.f);
  }
}
```

**Comment by elharo** [comment]
Is it? In this case you're relying on on B being a subclass of java.lang.Object and thus having a toString() method that's invoked polymorphically. You're calling PrintStream.toString(Object o).

**Comment by elharo** [comment]
This is a good example though. What we need to be testing here is whether the type of variable passed to the println method is accessible, not whether the actual runtime type of A.f is accessible.

**Comment by elharo** [comment]
This example shows we can't rely on it being a linkage error when accessing the method of the inaccessible class. This case does call the `toString()` method of the class, which is allowed.

**Comment by suztomo** [comment]
Right, being the subclass of java.lang.Object seems important. (Class C's bytecode does not call `Object.toString()`; https://gist.github.com/suztomo/500cbca470aefc2ba74e9d38a30e5cb0)

Explicitly calling toString fails compilation:

<img width="808" alt="Screen Shot 2020-08-19 at 14 45 38" src="https://user-images.githubusercontent.com/28604/90676922-ab613600-e22a-11ea-8a96-9909c9907e7b.png">

**Comment by elharo** [comment]
Yes, the call to toString is in `PrintStream`

**Comment by suztomo** [comment]
The compiler does not complain in that case.

<img width="457" alt="Screen Shot 2020-08-20 at 11 28 04" src="https://user-images.githubusercontent.com/28604/90792269-449a5600-e2d8-11ea-9569-a715e8695b51.png">

**Comment by suztomo** [comment]
Memo: What if the accessor of A.B changes from public to private in below? (public at the time of compile and private at the runtime) Does it create an error? If so, find the specification that states the error.

```
  void f(A.B b) { // This should fail. How?
    System.out.println(b);
  }
```

**Comment by suztomo** [comment]
@elharo @netdpb I appreciate if you can give me feedback on http://go/jdd-class-reference-validation
