### ISSUE TITLE
Make the linkage monitor easier to install

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1620]
One page plan for this

**Comment by suztomo** [comment]
# GitHub Actions

GitHub Actions are free to use in public repositories and suitable for repositories in Google opensource Java libraries.

Example: https://github.com/marketplace/actions/sonarqube-scanner, hosted in https://github.com/ItsEcholot/sonarqube-action. It has instruction to use:

<img width="738" alt="Screen Shot 2020-08-26 at 12 58 32" src="https://user-images.githubusercontent.com/28604/91333695-e79d1500-e79b-11ea-8612-738d5aa0f356.png">


# Questions to myself

- Do we need to create a repository for a new GitHub Action?
- What configuration do we want for Linkage Monitor?
  - BOM URL
  - artifactIDs
  - whether to send data to us

# For non-GitHub repositories

The implementation of Linkage Monitor should be a simple shell script that (somehow) accepts the configuration values.

**Comment by elharo** [comment]
I don't think we need to consider non-GitHub repositories for the moment. If we ever have to use this for Android or some such thing, we'll cross that bridge when we come to it.

**Comment by suztomo** [comment]
Wrote go/jdd-new-linkage-monitor for today's discussion.
