### ISSUE TITLE
Idea: batch job to detect Java8-incompatible class files

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1621]
A daily Kokoro job to check all the Maven artifacts that appear in the BOM dashboard ("Recommended versions" section) for the problematic class references that are not compatible with Java 8.

2nd part of the job checks the latest versions of the artifacts, so that we can work with the owner to fix the issue **before** GCP Java client libraries start depending on it.

Note that since yesterday, Linkage Checker can detect such invalid references.

![image](https://user-images.githubusercontent.com/28604/91388338-156a7400-e805-11ea-8cf3-3f5bc448a018.png)

@elharo What do you think?

**Comment by elharo** [comment]
Better than nothing, but even better would be a build time check on each PR, like CLIRR or animal sniffer.

**Comment by suztomo** [comment]
Compared to this idea, Kokoro release script and animal sniffer installation can detect issues before a release. Good. I don't object to the Kokoro audit and animal sniffer installation. They are good. However this daily job is more effective.

Compared with Kokoro release script audit, this idea has the following advantages

- This checks libraries outside Google
- This checks libraries not using Kokoro

Compared with animal sniffer installation, this idea has the following advantages:

- This is easy to implement (one Java class + job setup) compared to installing PR checks in tens if repository.
- We can see the result in a central place.
- If a release script uses different JDK or setting than PR checks, animal sniffer cannot detect bad config as PR checks.
