### ISSUE TITLE
Remove Java8IncompatibleReferenceCheck

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1632]
As discussed with @elharo @netdpb today, I'm not setting up the Java8IncompatibleReferenceCheck job. I will remove the Java8IncompatibleReferenceCheck class once the bad protobuf version is removed from the GCP Libraries BOM's dependencies.

**Comment by suztomo** [comment]
Current status: lots of artifacts in the BOM still have `com.google.protobuf:protobuf-java:jar:3.13.0` in their dependencies.
https://gist.github.com/suztomo/1ea07fa077ae72b49c902b8c87623c54

**Comment by elharo** [comment]
Most of these should be resolved with the next release of google-cloud-bom. http-java-client needs a little attention, maybe a couple of others
