### ISSUE TITLE
Static Linkage Check: Investigate implication of exclusion of "system" dependency

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#167]
The system exclusion was needed for earlier, existing code. But it might be a problem for static link checking.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/164#discussion_r225888394

**Comment by elharo** [comment]
We need to find some code that links to a system dependency and see what the static linkage checker says about it.

**Comment by suztomo** [comment]
@elharo In my experiment with "jdk:srczip:jar:999" (system scope of guava), the system exclusion didn't plan any role in StaticLinkageChecker or DashboardMain.

### Detail
While running DashboardMain, I only found "jdk:srczip:jar:999" as system dependency. The artifact [com.google.guava:guava:20.0](https://search.maven.org/artifact/com.google.guava/guava/20.0/bundle) has jdk:srczip:jar:999 as system scope.

My interpretation of [the exclusion (at levelOrder)](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java#L230) is "_even when we need complete dependency tree, do not fetch dependencies from artifact marked as system scope_".

When I ran StaticLinkageChecker for com.google.guava:guava:20.0, _including_ system scope at `DependencyGraphBuilder.levelOrder` ([line](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/iterative_dep_check/dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java#L259)) did not change the result, because "jdk:srczip:jar:999" did not have any dependency.

BTW, the Maven documentation about system scope says: 

> Dependencies with the scope system are always available and are not looked up in repository

https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#System_Dependencies

I don't think of a case where an artifact available in JDK requires any artifact in remote Maven repository. I guess the exclusion was implemented to avoid unnecessary repository lookup.

**Comment by elharo** [comment]
@suztomo This is done, right?
