### ISSUE TITLE
Table for class paths for each pair of 2 artifacts from BOM

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#168]
Table for class paths for each pair of 2 artifacts from BOM.

When applying the static linkage check to BOM, it first focuses on each class path generated by all possible pairs of the artifacts specified in BOM. The idea is driven by the following intuitions:

### Intuition 1
When there is a static linkage conflict by a class path [artifact_1, artifact_2,...artifact_n], there exists a pair of (artifact_x, artifact_y) among these artifacts, that can generate the same linkage conflict.

### Intuition 2
When there’s all possible pairs of (artifact_x, artifact_y) among [artifact_1, artifact_2, … artifact_n] do not generate any static linkage conflict, then there will not be a static linkage conflict for any class path made of 2 or more artifacts from the list in any order.

**Comment by elharo** [comment]
Some, perhaps most, static linkage errors are caused by missing classes/methods. It may be the case that two jars together have a static linkage conflict but three jars together do not.
