### ISSUE TITLE
Shut up GSLB logs in the release_bom script

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1738]
They're unactionable noise:

Oct 20, 2020 7:34:59 AM com.google.loadbalancer.rpc.GslbChannelPicker3$Builder build
INFO: Using GSLB fallback channel /mbns/local/loadbalancer/fallback/92C/blade_rapid-api
Oct 20, 2020 7:34:59 AM com.google.prod.machinelocality.HostnameNoLoas gmiHostname
INFO: Unable to load the hostname from go/google-machine-identity.
Oct 20, 2020 7:34:59 AM com.google.prod.machinelocality.HostnameNoLoas gmiHostname
INFO: Unable to load the hostname from go/google-machine-identity.
Oct 20, 2020 7:35:00 AM com.google.prod.machinelocality.HostnameNoLoas gmiHostname
INFO: Unable to load the hostname from go/google-machine-identity.
Oct 20, 2020 7:35:00 AM com.google.loadbalancer.rpc.GslbChannelPicker3 init
INFO: Using Butterknife for service blade:rapid-api
Oct 20, 2020 7:35:00 AM com.google.chubby.svelte.SvelteWatcher attachToWaiterThread
INFO: Using Svelte servers: corp [/lbns/chubby/any/svelte] [svelte-tasks.corp.ls.google.com.:6297] [svelte-corp.prodz.google.com.:6297] [corp.svelte.global.ls.google.com.:6297]
Oct 20, 2020 7:35:00 AM com.google.chubby.svelte.WaiterThread getSvelteStub
INFO: [corp] contacting svelte server at qnea1:6297 (qnea1/2002:ab3:8101:0:0:0:0:0:6297)
Oct 20, 2020 7:35:00 AM com.google.security.authorization.serverauthorization.arbiter.api.ArbiterRegistry arbiter
INFO: No go/server-authorization arbiter is available. This client will be unable to authorize servers. Consider running this program with the envelope to enable the go/server-authorization security checks.
Oct 20, 2020 7:35:00 AM com.google.net.loas.l2.Loas2SecureWrapper checkServerAuthorization
INFO: Skipping go/server-authorization checks because no arbiter is available [CONTEXT ratelimit_period="1 MINUTES" ]
Oct 20, 2020 7:35:01 AM com.google.prod.dependency.outboundacl.PolicyManager lambda$loadPolicyFromDefaultFile$0
INFO: No OutboundACL policy found at default location: /google/obj/workspace/99c3e6f681ee6cc5c693b1fdfb4d85af820279bd13aa029cff56fe8d214759f0/b86def4a-a0eb-42b6-89a7-7d87c9ae7ce2/blaze-out/k8-opt/bin/java/com/google/cloud/java/tools/ReleaseBom.runfiles/google3/java/com/google/prod/dependency/outboundacl/liboutboundacl.jar_default_policy.outboundacl
Oct 20, 2020 7:35:01 AM com.google.chubby.svelte.WaiterThread completeModify
INFO: [corp] client id set to 163fb02d571c5f47
Oct 20, 2020 7:35:04 AM com.google.cloud.java.tools.ReleaseBom main

**Comment by lizthegrey** [comment]
Hi, xoogler here, this has now come up when searching for two codenames I remember from my Google times, this might leak info on codenames you might want to remove from the issue by editing the words away.

**Comment by suztomo** [comment]
Thank you. Removed.
