### ISSUE TITLE
Release libraries-bom 13.3.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1756]
@suztomo or 14.0.0, whichever is appropriate. Since I currently don't have corp access, this feels like a good time for someone to try out the new release process to see if there are any gaps in the documentation: <https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/boms/cloud-oss-bom/RELEASING.md> If you hit any blockers or bugs, file an issue and assign it to me. Thanks.

**Comment by suztomo** [comment]
Sure. Checking the content of google-cloud-bom.

**Comment by suztomo** [comment]
Regarding your dead laptop, do you have access to the meetings for tomorrow? If not, I can reschedule them later in this week.

**Comment by elharo** [comment]
If you can invite my personal GMail account I can attend, otherwise I can't.

**Comment by suztomo** [comment]
Invited for the meetings.

**Comment by suztomo** [comment]
Released the BOM via sonatype staging.

**Comment by elharo** [comment]
I've received no invites.

**Comment by suztomo** [comment]
I sent it to your email with ibiblio.org domain.

**Comment by suztomo** [comment]
https://rework.withgoogle.com/guides/managers-set-and-communicate-a-team-vision/steps/create-a-vision-with-the-team/ is the document David mentioned during the meeting. His team didn't use "Core values" for simplicity.
