### ISSUE TITLE
StaticLinkageChecker: from root artifact, iteratively traverse method references to avoid false positives

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#176]
Currently there're many false positives from com.google.cloud:google-cloud-bigtable:0.66.0-alpha #151 . Many references to java-lzma from grpc-netty-shaded are not used by grpc, and thus it's expected that iteratively form usage class-level (not jar-level) usage graph from the roo classes in google-cloud-bigtable will not encounter LzmaFrameEncoder classes.

This is an implementation of the idea 2 in @garrettjonesgoogle 's comment https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/151#issuecomment-429893017

> Form a usage graph starting from the input library. Only check linkage for classes and methods that are referenced in that graph, and ignore things that aren't referenced.

Let's confirm that.

`StaticLinkageChecker.findUnresolvedReferences` is to iteratively search method references in the usage graph.

**Comment by elharo** [comment]
I'm still not convinced the LZMA issues are false positives. Given our definition of static linkage error, I think these are true positives. Our tool should report them. That's WAI.

Is there anything besides LZMA to look at here?

**Comment by elharo** [comment]
If we want to implement @garrettjonesgoogle idea #2 we need to first go back to our docs and rethink how we define static linkage error and make sure that's what we really want.

**Comment by garrettjonesgoogle** [comment]
From the internal doc:

> **Linkage conflict**: The signature of a non-private method or class in a dependency has changed in an incompatible way between the version supplied at compile time and the version invoked at runtime.

Technically these aren't linkage "conflicts" because it's not that something changed, it's that they are missing :-P They could fit under a larger umbrella of static linkage "error", though.

Another aspect of the definition: "between ... and the version invoked at runtime." This presupposes an actual invocation. If something cannot be invoked because it is orphaned, then it seems that we could technically ignore it according to the presuppositions of this definition. 

Since I wrote this definition, I can clarify that that was indeed my intent. Overall: if something cannot possibly fail when actually built into a real system and run that system, we don't want to worry about it.

Now it might be that we can't restrict our checks to entry points in the top-level jar, because our consumers might reference features in our dependencies that we don't reference. For example, someone using bigtable might reference things in grpc that google-cloud-java & gax never reference. Thus, we should check the surface of grpc. However, what we should strive to ignore are things that are unreachable from the grpc surface, and I suspect that is true for the lzma code.

**Comment by suztomo** [comment]
> Is there anything besides LZMA to look at here?

Not yet. Lzma issue was found when I applied the checker to randomly-choosen cloud-bigtable. There maybe other issues, maybe not. I feel that the tool is currently missing capability to show the reason of result. Let me think a little bit more.

> we need to first go back to our docs and rethink how we define static linkage error and make sure that's what we really want.

I agree. But it wouldn't be too late to decide that after we see the result of the idea; the idea is expected to solve the issue but we haven't confirmed it yet (or there may be side-effect of it). I'll share the result before raising PR, hopefully today.

**Comment by elharo** [comment]
I think "something has changed in an incompatible way" includes being deleted or removed. 

Related: we need to externalize this definition and associated information.

**Comment by elharo** [comment]
sounds good. Maybe terminology.md?

**Comment by garrettjonesgoogle** [comment]
Hmm - what about glossary.md? (Slightly more general than terminology)

**Comment by suztomo** [comment]
I implemented the idea in ([iterative_dep_check](https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/iterative_dep_check) branch), and no longer see linkage error from google-cloud-bigtable-0.66.0-alpha:

> Available method references in jar files: 782
There were no unresolved method references from the first jar file :/Users/suztomo/.m2/repository/com/google/cloud/google-cloud-bigtable/0.66.0-alpha/google-cloud-bigtable-0.66.0-alpha.jar

782 is smaller than I expected. I'll run for other artifacts in the BOM to see anything missed.

**Comment by suztomo** [comment]
The result of initial implementation of the idea of "usage graph from the input (root) artifact". It works for google-cloud-bigtable.

```
Managed Dependency: com.google.cloud:google-cloud-bigtable:0.67.0-alpha
Starting to read 36 files: 
[google-cloud-bigtable-0.67.0-alpha.jar, google-cloud-core-1.49.0.jar, google-cloud-core-grpc-1.49.0.jar, proto-google-cloud-bigtable-v2-0.32.0.jar, proto-google-cloud-bigtable-admin-v2-0.32.0.jar, grpc-netty-shaded-1.13.1.jar, grpc-stub-1.13.1.jar, grpc-auth-1.13.1.jar, guava-20.0.jar, joda-time-2.9.2.jar, google-http-client-1.24.1.jar, jsr305-3.0.2.jar, api-common-1.7.0.jar, gax-1.32.0.jar, protobuf-java-util-3.6.1.jar, proto-google-common-protos-1.12.0.jar, proto-google-iam-v1-0.12.0.jar, google-auth-library-credentials-0.11.0.jar, protobuf-java-3.6.1.jar, grpc-protobuf-1.13.1.jar, grpc-context-1.13.1.jar, gax-grpc-1.32.0.jar, grpc-core-1.13.1.jar, httpclient-4.5.3.jar, threetenbp-1.3.3.jar, google-auth-library-oauth2-http-0.11.0.jar, gson-2.7.jar, grpc-protobuf-lite-1.13.1.jar, error_prone_annotations-2.2.0.jar, opencensus-api-0.15.0.jar, opencensus-contrib-grpc-metrics-0.12.3.jar, httpcore-4.4.6.jar, commons-logging-1.2.jar, commons-codec-1.9.jar, google-http-client-jackson2-1.24.1.jar, jackson-core-2.9.2.jar]
The number of resolved method references during linkage check: 1161
There were no unresolved method references from the first jar file :/Users/suztomo/.m2/repository/com/google/cloud/google-cloud-bigtable/0.67.0-alpha/google-cloud-bigtable-0.67.0-alpha.jar
```

> Is there anything besides LZMA to look at here?

I ran some of members in the BOM : https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/iterative_dep_check/dependencies/static_linkage_check_result.txt

Apart from netty classes, appengine's urlfetch classes (e.g., `com.google.appengine.api.urlfetch.FetchOptions`) and `com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient` caught my eyes.

**Comment by elharo** [comment]
The com.google.appengine.api.urlfetch.FetchOptions probably means we aren't handling provided dependencies correctly. Thus I suspect it's a bug in the checker.

Netty we need to look at more closely to understand what it means. There's some weird stuff there.

**Comment by suztomo** [comment]
You're right; it's provided dependency that's playing something here. To confirm that I added some command-line option to get the usage graph of classes and its jar files.

```
Starting to read 31 files: 
[/Users/suztomo/.m2/repository/com/google/cloud/google-cloud-compute/0.67.0-alpha/google-cloud-compute-0.67.0-alpha.jar, /Users/suztomo/.m2/repository/com/google/cloud/google-cloud-core/1.49.0/google-cloud-core-1.49.0.jar, /Users/suztomo/.m2/repository/com/google/cloud/google-cloud-core-http/1.49.0/google-cloud-core-http-1.49.0.jar, /Users/suztomo/.m2/repository/com/google/apis/google-api-services-compute/v1-rev193-1.24.1/google-api-services-compute-v1-rev193-1.24.1.jar, /Users/suztomo/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar, /Users/suztomo/.m2/repository/joda-time/joda-time/2.9.2/joda-time-2.9.2.jar, /Users/suztomo/.m2/repository/com/google/http-client/google-http-client/1.24.1/google-http-client-1.24.1.jar, /Users/suztomo/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar, /Users/suztomo/.m2/repository/com/google/api/api-common/1.7.0/api-common-1.7.0.jar, /Users/suztomo/.m2/repository/com/google/api/gax/1.32.0/gax-1.32.0.jar, /Users/suztomo/.m2/repository/com/google/protobuf/protobuf-java-util/3.6.1/protobuf-java-util-3.6.1.jar, /Users/suztomo/.m2/repository/com/google/api/grpc/proto-google-common-protos/1.12.0/proto-google-common-protos-1.12.0.jar, /Users/suztomo/.m2/repository/com/google/api/grpc/proto-google-iam-v1/0.12.0/proto-google-iam-v1-0.12.0.jar, /Users/suztomo/.m2/repository/com/google/auth/google-auth-library-credentials/0.11.0/google-auth-library-credentials-0.11.0.jar, /Users/suztomo/.m2/repository/com/google/auth/google-auth-library-oauth2-http/0.11.0/google-auth-library-oauth2-http-0.11.0.jar, /Users/suztomo/.m2/repository/com/google/oauth-client/google-oauth-client/1.24.1/google-oauth-client-1.24.1.jar, /Users/suztomo/.m2/repository/com/google/api-client/google-api-client/1.24.1/google-api-client-1.24.1.jar, /Users/suztomo/.m2/repository/com/google/http-client/google-http-client-appengine/1.24.1/google-http-client-appengine-1.24.1.jar, /Users/suztomo/.m2/repository/com/google/http-client/google-http-client-jackson2/1.24.1/google-http-client-jackson2-1.24.1.jar, /Users/suztomo/.m2/repository/com/google/api/gax-httpjson/0.49.0/gax-httpjson-0.49.0.jar, /Users/suztomo/.m2/repository/io/opencensus/opencensus-api/0.15.0/opencensus-api-0.15.0.jar, /Users/suztomo/.m2/repository/io/opencensus/opencensus-contrib-http-util/0.15.0/opencensus-contrib-http-util-0.15.0.jar, /Users/suztomo/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar, /Users/suztomo/.m2/repository/org/threeten/threetenbp/1.3.3/threetenbp-1.3.3.jar, /Users/suztomo/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar, /Users/suztomo/.m2/repository/com/google/code/gson/gson/2.7/gson-2.7.jar, /Users/suztomo/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.2/jackson-core-2.9.2.jar, /Users/suztomo/.m2/repository/io/grpc/grpc-context/1.13.1/grpc-context-1.13.1.jar, /Users/suztomo/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar, /Users/suztomo/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar, /Users/suztomo/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar]
The number of resolved method references during linkage check: 1560

com.google.appengine.api.urlfetch.FetchOptions <- com.google.api.client.extensions.appengine.http.UrlFetchTransport in google-http-client-appengine-1.24.1.jar
    com.google.api.client.extensions.appengine.http.UrlFetchTransport <- com.google.cloud.http.HttpTransportOptions$DefaultHttpTransportFactory in google-cloud-core-http-1.49.0.jar
        com.google.cloud.http.HttpTransportOptions$DefaultHttpTransportFactory <- com.google.cloud.http.HttpTransportOptions in google-cloud-core-http-1.49.0.jar
            com.google.cloud.http.HttpTransportOptions <- com.google.cloud.http.HttpTransportOptions$1 in google-cloud-core-http-1.49.0.jar
                com.google.cloud.http.HttpTransportOptions$1 <- com.google.cloud.http.HttpTransportOptions in google-cloud-core-http-1.49.0.jar
                    (Cyclic dependency of com.google.cloud.http.HttpTransportOptions)
            com.google.cloud.http.HttpTransportOptions <- com.google.cloud.compute.deprecated.testing.RemoteComputeHelper in google-cloud-compute-0.67.0-alpha.jar
                com.google.cloud.compute.deprecated.testing.RemoteComputeHelper <- com.google.cloud.compute.deprecated.testing.RemoteComputeHelper in google-cloud-compute-0.67.0-alpha.jar
                    (Cyclic dependency of com.google.cloud.compute.deprecated.testing.RemoteComputeHelper)
            com.google.cloud.http.HttpTransportOptions <- com.google.cloud.http.HttpTransportOptions in google-cloud-core-http-1.49.0.jar
                (Cyclic dependency of com.google.cloud.http.HttpTransportOptions)
            com.google.cloud.http.HttpTransportOptions <- com.google.cloud.compute.deprecated.spi.v1.HttpComputeRpc in google-cloud-compute-0.67.0-alpha.jar
                com.google.cloud.compute.deprecated.spi.v1.HttpComputeRpc <- com.google.cloud.compute.deprecated.spi.v1.HttpComputeRpc in google-cloud-compute-0.67.0-alpha.jar
                    (Cyclic dependency of com.google.cloud.compute.deprecated.spi.v1.HttpComputeRpc)
            com.google.cloud.http.HttpTransportOptions <- com.google.cloud.compute.deprecated.ComputeOptions in google-cloud-compute-0.67.0-alpha.jar
                com.google.cloud.compute.deprecated.ComputeOptions <- com.google.cloud.compute.deprecated.Image in google-cloud-compute-0.67.0-alpha.jar
                    com.google.cloud.compute.deprecated.Image <- com.google.cloud.compute.deprecated.ComputeImpl in google-cloud-compute-0.67.0-alpha.jar
                        com.google.cloud.compute.deprecated.ComputeImpl <- com.google.cloud.compute.deprecated.ComputeImpl in google-cloud-compute-0.67.0-alpha.jar
                            (Cyclic dependency of com.google.cloud.compute.deprecated.ComputeImpl)
                    com.google.cloud.compute.deprecated.Image <- com.google.cloud.compute.deprecated.Image in google-cloud-compute-0.67.0-alpha.jar

```

[google-http-client-appengine-1.24.1.jar](https://search.maven.org/artifact/com.google.http-client/google-http-client-appengine/1.24.1/jar) has 

```
    <dependency>
      <groupId>com.google.appengine</groupId>
      <artifactId>appengine-api-1.0-sdk</artifactId>
      <scope>provided</scope>
    </dependency>
```

and the appengine-api-1.0-sdk is not included the 31 files. I'm going to fix the tool to ignore missing classes in provided scope.

**Comment by elharo** [comment]
No, we don't want to ignore it. We need to include it.

**Comment by suztomo** [comment]
Right. #183 is to include it.

**Comment by garrettjonesgoogle** [comment]
This general approach makes sense to me.

**Comment by suztomo** [comment]
@garrettjonesgoogle Thank you.

A diagram is added to the document (go/jdd-static-linkage-checker) to explain the concept of the traversal on the graph.

<img width="601" alt="screen shot 2018-10-23 at 13 02 08" src="https://user-images.githubusercontent.com/28604/47377661-e8f2e780-d6c3-11e8-91aa-8bad0d7fe5e4.png">
