### ISSUE TITLE
New title for JLBP-5?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1764]
Currently the title is "Avoid dependencies that overlap classes with other dependencies". We then immediately have to define "overlap". Should we rephrase this? Either:

"Do not include a class in more than one classpath entry."

or

"Each class belongs in exactly one class file in the classpath."

**Comment by suztomo** [comment]
The latter is not imperative.

Memo: "class path entry" appears in https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html (So it's not our own term. Good)
