### ISSUE TITLE
Notify folks that @elharo is locked out of corp again

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1794]
FYI, apparently someone marked the replacement laptop as needing repair instead of the old, busted laptop. Consequently I am again locked out of corp until Techstop straightens this out. This time I can't even get a temporary exemption to use a personal device. 

@suztomo please let relevant folks know. I'll do what I can here, but I'm mostly blocked until this is resolved.

**Comment by suztomo** [comment]
Sure. Done for the chat.

I sent our 11:00 meeting invitation to your ibiblio.org email address.

**Comment by elharo** [comment]
Got back in quicker this time.
