### ISSUE TITLE
LinkageCheckerTest.testFindLinkageProblems_referenceToJava11Method fails in Java 11

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1822]
Towards #1821 .

```
suztomo-macbookpro44% which java
/Library/Java/JavaVirtualMachines/jdk-11-latest/Contents/Home/bin/java
suztomo-macbookpro44% pwd        
/Users/suztomo/cloud-opensource-java/dependencies
suztomo-macbookpro44% mvn test -Dtest=LinkageCheckerTest#testFindLinkageProblems_referenceToJava11Method 
...
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.154 s <<< FAILURE! - in com.google.cloud.tools.opensource.classpath.LinkageCheckerTest
[ERROR] testFindLinkageProblems_referenceToJava11Method(com.google.cloud.tools.opensource.classpath.LinkageCheckerTest)  Time elapsed: 1.081 s  <<< FAILURE!
com.google.common.truth.AssertionErrorWithFacts: 
value of           : findLinkageProblems()
expected to contain: java.nio.CharBuffer's method flip() is expected to return java.nio.CharBuffer but instead returns java.nio.Buffer referenced by ClassFile{location=com.google.protobuf:protobuf-java:3.12.4, className=com.google.protobuf.TextFormat}
but was            : []
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerTest.testFindLinkageProblems_referenceToJava11Method(LinkageCheckerTest.java:1150)

```

The problem of `java.nio.CharBuffer`'s invalid return type is only applicable to Java 8 runtime.

Should Linkage Checker have a mode to switch Java runtime version?

What's user's experience? In a certain scenario, should a user only care about Java 8? Or Just Java 11?

What about a user who currently uses Java 11 in their builds but wants to ensure their library runs well on Java 8?

**Comment by elharo** [comment]
This looks like the problem protobuf hit.

**Comment by elharo** [comment]
In fact, this might be a very useful case to surface. We know it bit protobuf users.

**Comment by suztomo** [comment]
This test case is ensures Linkage Checker detects the protobuf case. The test case succeeds in Java 8. But Linkage Checker cannot detect the failure if it runs on Java 11 (Because Java 11 runtime does not encounter the problem)

**Comment by suztomo** [comment]
1. Run test only when specific runtime. Can JUnit has functionality:[Assume](https://junit.org/junit4/javadoc/4.12/org/junit/Assume.html)

2. Have 2 Linkage Monitor for Java 8 and Java 11. Document this.

3. Linkage Monitor to take parameters to specify targeting environment (Java 8/Java 11).
   Big change: we could provide Java 8 / Java 11 symbols.



We go for 1 and 2.
