### ISSUE TITLE
Implement a more deliberate release strategy for linkage monitor

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1843]

**Comment by suztomo** [comment]
Ideas

# Checks

- Smoke test in front of deployments (the nightly builds). Better to test a JAR file after shading.
- CI in this repository to ensure Linkage Monitor works fine in
  - dummy projects
  - some of the downstream repositories. (the latest status of the repo is unknown)

# Release Process

**Comment by suztomo** [comment]
Created "Linkage Monitor and GitHub Actions Versioning" http://go/jdd-github-actions . If we maintain the version through Github Actions, we need a new Github repository.

**Comment by suztomo** [comment]
This has been implemented.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/RELEASING.md#release
