### ISSUE TITLE
Shall we stop the Circle CI build?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1862]
Shall we remove Circle CI build, for the following reasons?

1. This repository has used Circle CI for Linux (Java 8) build. With the recently-introduced Github Actions that run for Java 8 (and Java 11) on Linux, I don't think we need Circle CI build.

2. Circle CI requires permission to see logs.

<img width="1345" alt="Screen Shot 2020-12-04 at 15 11 08" src="https://user-images.githubusercontent.com/28604/101221098-fcb7f880-3654-11eb-8c37-9fa2f67552c4.png">

3. CI with Github Actions is in line with other Google Cloud Java repositories maintained by Yoshi team.

# Memo on disabling Circle CI

https://support.circleci.com/hc/en-us/articles/360021666393-How-to-stop-building-by-manually-removing-the-CircleCI-webhook-and-deploy-key-from-your-GitHub-repository

- Updated https://circleci.com/hooks/github webhook as inactive.
- Updated protected branch
  - not to require Circle CI
  - added "units (8)" as required check.

**Comment by elharo** [comment]
Makes sense.

**Comment by suztomo** [comment]
Thank you for response. I'll work on it.

**Comment by suztomo** [comment]
Marked Java 11 as "Required" pull request check.

**Comment by suztomo** [comment]
Deleted https://circleci.com/hooks/github and Circle CI deploy key.
