### ISSUE TITLE
Shall we do something for the BOM dashboard showing red in the linkage error column?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1863]
Every time I show the dashboard to somebody (Stephanie, Ray, Alan, and Ronald), they say "What's the red in the linkage error column? Are we fixing them?". I answer that I don't do anything to fix them as it won't cause problems to GCP users because I checked the dependency graphs and confirmed that these linkage errors (ones from commons-logging, grpc-netty-shaded, etc.) are not referenced. However, I recognize that their points make sense. If something is not causing the problem, we should not show them as red. The current BOM dashboard obscures the real problem that may arise in users' environment in the forest of other non-harmful linkage errors.

How can improve the BOM dashboard?

<img width="1440" alt="Screen Shot 2020-12-07 at 11 51 27" src="https://user-images.githubusercontent.com/28604/101379734-99131280-3882-11eb-9be8-a44ce311b95c.png">

> I checked the dependency graphs and confirmed that these linkage errors

I wrote this but the dashboard should be clear for first-time readers, not just for me.

**Comment by elharo** [comment]
Is it unclear? It seems people are correctly interpreting that as broken.

**Comment by suztomo** [comment]
Yes, they are broken in terms of our definition of linkage errors and dashboard implementation.

If they are broken to GCP customers, then I think we should pay effort to fix them. However, we are currently not trying to fix them because we know that the linkage errors currently shown there don't cause issues to our customers.

**Comment by elharo** [comment]
Let's discuss offline. I don't think that's what's happening.

**Comment by suztomo** [comment]
To double-check the logging errors and decide whether improve code or exclusion rules.
