### ISSUE TITLE
Investigate Linkage Errors in io.netty:netty-common:4.1.51.Final

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1872]
Even if we run the linkage checker to filter only reachable linkage errors, they are shown in the dashboard:

```
io.netty:netty-common:4.1.51.Final
13 target classes causing linkage errors referenced from 15 source classes.

Class org.apache.log4j.Logger is not found, referenced from 2 classes ▼

io.netty.util.internal.logging.Log4JLogger
io.netty.util.internal.logging.Log4JLoggerFactory
Class org.apache.log4j.Level is not found, referenced from io.netty.util.internal.logging.Log4JLogger

Class org.slf4j.Logger is not found, referenced from io.netty.util.internal.logging.Slf4JLogger

Class org.apache.logging.log4j.LogManager is not found, referenced from io.netty.util.internal.logging.Log4J2LoggerFactory

Class org.apache.logging.log4j.spi.ExtendedLoggerWrapper is not found, referenced from io.netty.util.internal.logging.Log4J2Logger

Class org.apache.logging.log4j.spi.ExtendedLogger is not found, referenced from io.netty.util.internal.logging.Log4J2Logger

Class org.apache.logging.log4j.Logger is not found, referenced from io.netty.util.internal.logging.Log4J2Logger

Class org.apache.logging.log4j.Level is not found, referenced from io.netty.util.internal.logging.Log4J2Logger

Class org.slf4j.spi.LocationAwareLogger is not found, referenced from 2 classes ▼

io.netty.util.internal.logging.LocationAwareSlf4JLogger
io.netty.util.internal.logging.Slf4JLoggerFactory
Class org.slf4j.helpers.FormattingTuple is not found, referenced from io.netty.util.internal.logging.LocationAwareSlf4JLogger

Class org.slf4j.helpers.MessageFormatter is not found, referenced from io.netty.util.internal.logging.LocationAwareSlf4JLogger

Class org.slf4j.LoggerFactory is not found, referenced from io.netty.util.internal.logging.Slf4JLoggerFactory

Class org.slf4j.helpers.NOPLoggerFactory is not found, referenced from io.netty.util.internal.logging.Slf4JLoggerFactory
```

Find out whether they are real problem or not.

[netty-common:4.1.51.Final](https://search.maven.org/artifact/io.netty/netty-common/4.1.51.Final/jar) declares the logging libraries as optional. 

`io.netty.util.internal.logging.InternalLoggerFactory` says:

> Creates an InternalLogger or changes the default factory implementation. This factory allows you to choose what logging framework Netty should use. The default factory is Slf4JLoggerFactory. If SLF4J is not available, Log4JLoggerFactory is used. If Log4J is not available, JdkLoggerFactory is used.

Implementation-wise, the InternalLogger examines the presence of the logger implementations.

```
    private static InternalLoggerFactory newDefaultFactory(String name) {
        InternalLoggerFactory f;
        try {
            f = new Slf4JLoggerFactory(true);
            f.newInstance(name).debug("Using SLF4J as the default logging framework");
        } catch (Throwable ignore1) {
            try {
                f = Log4J2LoggerFactory.INSTANCE;
                f.newInstance(name).debug("Using Log4J2 as the default logging framework");
            } catch (Throwable ignore2) {
                try {
                    f = Log4JLoggerFactory.INSTANCE;
                    f.newInstance(name).debug("Using Log4J as the default logging framework");
                } catch (Throwable ignore3) {
                    f = JdkLoggerFactory.INSTANCE;
                    f.newInstance(name).debug("Using java.util.logging as the default logging framework");
                }
            }
        }
        return f;
    }
```

Note that Linkage Checker can suppress classes that detect try-catch clause for LinkageError, NoClassDefFoundError, and ClassNotFoundException. The try-catch clauses in the InternalLoggerFactory are catching `Throwable`. Even if they do catch concrete exceptions, Linkage Checker could only suppress linkage errors on InternalLoggerFactory. Not `io.netty.util.internal.logging.Log4JLogger` or `io.netty.util.internal.logging.Slf4JLoggerFactory`.

<img width="391" alt="Screen Shot 2020-12-10 at 11 32 56" src="https://user-images.githubusercontent.com/28604/101800600-7596d480-3adb-11eb-86ee-7ae230fd4b13.png">

**Comment by elharo** [comment]
Catching Throwable is bad and Netty should feel bad. That said, they do guard and thus this is a false positive. 

Can we try submitting an issue and patch to Netty for more specific catch clauses?

**Comment by elharo** [comment]
https://github.com/netty/netty/issues/10857

**Comment by elharo** [comment]
I wonder if Linkage Checker should also suppress classes that detect try-catch clause for Throwable. Catching Throwable isn't very common. Alternatively, could we tighten up the suppression to make sure that the linkage error is covered by the try-catch, and not just that a try-catch appears somewhere in the same class.

**Comment by suztomo** [comment]
> netty/netty#10857

That's a nice idea. Thank you.

> Alternatively, we tighten up the suppression to make sure that the linkage error is covered by the try-catch, and not just that a try-catch appears somewhere in the same class.

Nice. That's would reduce false negatives. (Although I haven't seen much false negative of Linkage Checker yet)

**Comment by elharo** [comment]
FYI https://github.com/netty/netty/pull/10866 has been merged and should eventually make the sepcial casing unnecessary.

**Comment by suztomo** [comment]
(I forgot to mention during the call) The netty change will suppress linkage errors from the `InternalLoggerFactory`. Nice. However the logger implementations in the same package (`io.netty.util.internal.logging.Log4JLogger` or `io.netty.util.internal.logging.Slf4JLoggerFactory`) still need the special casing. (Linkage Checker is not smart enough to recognize InternalLoggerFactory's try-catch is for the loggers.)
