### ISSUE TITLE
Detect/enforce single thread with Linkage-Checker-Enforcer-Rule

### ISSUE THREAD

**Issue by delanym** [GoogleCloudPlatform/cloud-opensource-java#1892]
The Linkage-Checker-Enforcer-Rule requires a single threaded build when building a multi-module project to the install phase. I would like to enforce this, either by making a separate rule to enforce a single thread build, and/or 
have the requirement built into this rule.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/Linkage-Checker-Enforcer-Rule

Is this possible?

**Comment by elharo** [comment]
Not sure if it's possible or not, but feel free to try. Assuming this is accurate, I think building the requirement into the rule is probably the way to go.

**Comment by suztomo** [comment]
@delanym Thank you for inquiry. Unfortunately I didn't find a way to allow multi-thread execution of the Linkage Checker enforcer rule with `mvn install`. When I encountered a problem with multi-thread `mvn install`:

https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1593#issuecomment-674907932

> It's a race condition where a JAR file is modified (maybe deleted and recreated) during Linkage Checker execution.

The JAR file Linkage Checker was reading was recreated by another thread installing the module. I ended up running `install` (without linkage checker) and then `verify` for linkage checker (`--activate-profiles linkage-check` in [spring-cloud-gcp#56](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/56/files#diff-d2d6c5307d7a48f410750482bb220b236269b668715b83d1e0a791cca40870d3R165)).

**Comment by delanym** [comment]
@suztomo, did you try with http://takari.io/book/30-team-maven.html#concurrent-safe-local-repository ?

**Comment by suztomo** [comment]
No, my first time to see that. The problem description seems matching the problem I faced. Let me check further. Thank you!

**Comment by suztomo** [comment]
I tried to reproduce the issue with spring-cloud-gcp today but I get timeout from spring repository "repo.spring.io:443 timed out". I'll try next week.

**Comment by delanym** [comment]
Best wait for Maven 4. See https://issues.apache.org/jira/browse/MNG-4706

**Comment by suztomo** [comment]
Will do. Thank you for the information.

**Comment by elharo** [comment]
closing in anticipation of maven 4
