### ISSUE TITLE
On JLBP-11, it's ok not to upgrade to the major version change if the newer version is a completely different artifact

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1900]
[JLBP-11: Keep dependencies up to date](https://jlbp.dev/JLBP-11) 

Shall we add an exception of apache http client version 4 and 5? As long as the new major version has different maven coordinates and Java package, we don't need to worry about dependency conflict. It's ok to keep the old major version.

**Comment by elharo** [comment]
If the package has changed and the Maven coordinates have changed, is it even the same dependency?

**Comment by elharo** [comment]
Keeping the old major version also requires that the old one be at least minimally supported with security patches.
