### ISSUE TITLE
Rapid Build might need an update

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#1966]
This project allows UI configuration and must be switched to blueprint-only configuration.
Please read go/rapid-blueprint-only-migration and then run the migration command for google3/cloud/java/tools/cloud-opensource-java/bom/rapid/kokoro_release.blueprint.
Starting on 2021-04-05, the Rapid UI will forbid modifying UI configuration.
On 2021-04-19, all remaining Rapid UI configuration will be deleted.

**Comment by suztomo** [comment]
# My Memo

The cloud-java-tools-cloud-opensource-java-linkage-monitor-kokoro-release (I recently setup this) does not show the warning. I vaguely remember I fixed some warning in CL when I setup. Other 5 Rapid projects show the warning.

Continuing.

**Comment by elharo** [comment]
I saw this with libraries-bom

**Comment by suztomo** [comment]
Yes, I saw the warning in the libraries BOM project too. I'll create a CL to migrate these 5 Rapid projects.

**Comment by elharo** [comment]
fixed in cl/363492853
