### ISSUE TITLE
Linkage Checker showed false positive for Beam's vendoring

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#1976]
(I'm helping Beam's vendored gRPC 1.36 upgrade)

Beam's vendored gRPC 1.26 (created 1 year ago) may have unnecessary dependencies included in the JAR. **The developer did it because Linkage Checker showed (false positive) errors and they resolved the errors by adding (unnecessary) dependencies in it**.

<img width="1401" alt="Screen Shot 2021-03-10 at 11 25 35" src="https://user-images.githubusercontent.com/28604/110662987-0c833380-8194-11eb-94ef-ec5b90284424.png">

- The dependencies of vendored gRPC 1.21: https://github.com/apache/beam/pull/10578/files#diff-5f748d8edfd5d6943e97569b3bc2b8f050be6bfc4eba8d5af61b34a9462a7811
- The dependencies of vendored gRPC 1.26: https://github.com/apache/beam/pull/10463/files#diff-f4b254ad7919c73e6e04335a11e1d2c5c24a786e9a85d7dbfe472deccb683ba3R48

Having unnecessary dependencies in vendored artifacts is bad, because unused dependencies trigger CVE alerts that are not actually relevant (example: https://issues.apache.org/jira/browse/BEAM-11227).

Note that the reachability analysis does not help the analyzing the vendored JAR file, because all the classes in the JAR are considered as entry point classes.

**Comment by suztomo** [comment]
Current direction: to remove unnecessary classes from netty when shading.

**Comment by elharo** [comment]
Hmm, sounds like we might need to dig into whether this was a false positive. I suspect the problem is the vendoring tool  created a jar with linkage errors. We've seen similar issues with the appengine-api-ssk.

**Comment by suztomo** [comment]
Most of the linkage errors caused by netty also appears in the BOM dashboard https://storage.googleapis.com/cloud-opensource-java-dashboard/com.google.cloud/libraries-bom/snapshot/io.grpc_grpc-netty_1.36.0.html 

I think I'll need to check the code to see whether the uses of the missing classes are surrounded by try-catch clauses. Then enrich the [default exclusion rule](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/dependencies/src/main/resources/linkage-checker-exclusion-default.xml).

**Comment by suztomo** [comment]
The default exclusion file includes netty classes now. I also added to Beam's document about why the linkage errors are not harmful.
https://github.com/apache/beam/tree/master/vendor#known-linkage-errors-in-the-vendored-grpc-dependencies
