### ISSUE TITLE
The package com.google.cloud.kms.v1 is accessible from more than one module

### ISSUE THREAD

**Issue by danielventulieri** [GoogleCloudPlatform/cloud-opensource-java#1998]
I am trying to follow the `SignAsymmetric` sample, however Eclipse continues to give me the following error when trying to import the required classes:

```
The package com.google.cloud.kms.v1 is accessible from more than one module: google.cloud.kms, proto.google.cloud.kms.v1
```

I took a look at the Maven dependencies, and `com.google.cloud.kms.v1` package is in fact accessible by those two modules:

<img width="247" alt="Screen Shot 2021-03-30 at 3 20 11 PM" src="https://user-images.githubusercontent.com/5070157/113044245-6e1f3800-916b-11eb-8dd6-2eb23f3386c2.png">

<img width="255" alt="Screen Shot 2021-03-30 at 3 20 35 PM" src="https://user-images.githubusercontent.com/5070157/113044318-7bd4bd80-916b-11eb-80b8-b578710749fb.png">

Everything I need is in the `proto-google-cloud-kms-v1` module except for `KeyManagementServiceClient`.

I've setup my POM file as explained in the README:

```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.google.cloud</groupId>
				<artifactId>libraries-bom</artifactId>
				<version>19.2.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
       <dependencies>
                 <dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-kms</artifactId>
		</dependency>
       </dependencies>
```

**Comment by suztomo** [comment]
@danielventulieri (I'm not familiar with the error message) Which Java version do you use?

Memo for myself:


https://search.maven.org/artifact/com.google.cloud/google-cloud-kms/1.41.1/jar has 

```
    <dependency>
      <groupId>com.google.api.grpc</groupId>
      <artifactId>proto-google-cloud-kms-v1</artifactId>
      <version>0.88.1</version>
      <scope>compile</scope>
...
    </dependency>
```

**Comment by danielventulieri** [comment]
@suztomo Using java 14.0.2

@elharo ahhh yes I see that you opened [an issue ](https://github.com/googleapis/java-kms/issues/84) about the split package problem back in Feb 2020
