### ISSUE TITLE
Tree control for Dependencies

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#202]
Turn the Dependencies section on the individual component pages into a collapsing tree widget (expanded by default) so it's easier to navigate.

**Comment by suztomo** [comment]
looking into this.

**Comment by elharo** [comment]
Thanks. Let me know what you find out. Let's discuss plans before implementation.

**Comment by suztomo** [comment]
Thanks to `DependencyTreeFormatter.buildDependencyPathTree`, which returns `ListMultimap<DependencyPath, DependencyPath> dependencyTree`, and Freemarker (recursive) macro, it was straightforward to create nested `<ul>` tags in dashboard.

<img width="889" alt="screen shot 2018-11-02 at 09 56 33" src="https://user-images.githubusercontent.com/28604/47919387-9ebcf380-de85-11e8-8b51-4d3a0cc72a9b.png">

I stop here for now. Talk to you later.
