### ISSUE TITLE
Classes for the result of StaticLinkageChecker

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#207]
To prepare Java class to represent the output of static linkage check.

### StaticLinkageCheckReport class
This holds list of `JarLinkageReport`s

### JarLinkageReport class
This holds the lists of following 3 classes

### MissingMethod class

I'm thinking to use Google AutoValue to implement them

**Comment by elharo** [comment]
I would prefer not to depend on autovalue.

**Comment by suztomo** [comment]
As I read more about AutoValue, I feel it suits our need for the classes. I expect AutoValue will give us great benefit especially when definition of value classes evolve as we discuss further; with AutoValue, we don't need to _manually amend_ the implementation of `equals`, `hashcode` and `toString` methods, or _code-review_ the boilerplate.

In terms of pom.xml, AutoValue works without configuration (it just needs [2 dependencies in pom.xml](https://github.com/google/auto/blob/master/value/userguide/index.md#in-pomxml)). No need to introduce a Maven plugin for AutoValue.

Let's talk on Monday.
