### ISSUE TITLE
Expand definition of static linkage errors

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#212]
During the development of the static linkage checker, we uncovered a lot of detail about what exactly qualifies as a static linkage error and why or why not. This includes

* Provided, optional, and system dependencies. 
* How reachability determines whether a particular issue is or is not an error. 

Probably some other tings I'm not thinking of right now.

We need to capture all this knowledge in the repo, perhaps in the API docs,  the glossary, and/or a separate more detail doc about linkage errors.

**Comment by suztomo** [comment]
@elharo @garrettjonesgoogle 

I'm thinking to create cloud-opensource-java/dependencies/README.md with title:StaticLinkageChecker. 

Something like:

---

### Static Linkage Checker
(to fill in README.md. Copy from go/jdd-static-linkage-checker)

### How Static Linkage Checker helps Java developers

For organizations that provide multiple libraries developed by different teams, the tool helps to ensure that there is no [static linkage conflicts](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/glossary.md#types-of-conflicts-and-compatibility) among the libraries and their dependencies.

For library developers, the tool ensures that the users of the library will not suffer the static linkage conflicts caused solely by the dependencies of the library.

(future plan) For application developers relying on 3rd-party libraries, the tool will assess the risk of  static linkage conflicts among the application's dependencies, and will help to use appropriate versions of libraries to avoid runtime errors.

### Approach

(to fill in README.md by documenting #203 )

### Class Usage Graph and Reachability
(to fill in README.md)
