### ISSUE TITLE
Rewrite JLBP 6 title as command

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#213]
Most JLPBs are titled imperatively: Do this. Don't do that. JLBP-6 is, however,

JLBP-6: Package and artifact renaming rules

Figure out if we can rewrite this as a command.

**Comment by garrettjonesgoogle** [comment]
Since there are multiple rules, it's hard to rewrite as a command. The only thing I can think of is splitting it up so that the commands can fit into a single line each, but then we lose the ability to discuss the topic at a high level.
