### ISSUE TITLE
guava version mismatch

### ISSUE THREAD

**Issue by ganireddy** [GoogleCloudPlatform/cloud-opensource-java#2161]
guava version have 2 flavours as mentioned in docs, -jre for java 8 or later versions and -android for java 7 version.
But guava version is including -andriod flavour irrespective of java version, please fix this

**Comment by suztomo** [comment]
Please refer to https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM#guava-versions--jre-or--android to set Guava flavor that match your use.

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>30.1.1-jre</version>  <!-- "-jre" for Java 8 or higher -->
      </dependency>
    </dependencies>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>libraries-bom</artifactId>
        ...
  </dependencyManagement>
```
