### ISSUE TITLE
Re-order BOM: lowest to highest

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/cloud-opensource-java#218]
Suggested order:

- protobuf
- grpc
- google-cloud-bom

**Comment by elharo** [comment]
With regard to suggesting order, does internal order such as the order of all the grpc modules matter? I'm thinking not.

**Comment by garrettjonesgoogle** [comment]
I don't think it does, since they should all be released together and should all use the same versions of dependencies.
