### ISSUE TITLE
Add grpc-alts (and any other missing grpc modules) to cloud-oss-bom

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/cloud-opensource-java#219]

**Comment by elharo** [comment]
The gRPC docs do not mention this as something users should add:

https://github.com/grpc/grpc-java

Are we sure this isn't an internal artifact users should not depend on?

**Comment by elharo** [comment]
We definitely do need:

compile 'io.grpc:grpc-okhttp:1.16.1'
compile 'io.grpc:grpc-protobuf-lite:1.16.1'

**Comment by garrettjonesgoogle** [comment]
If it is an internal artifact that other grpc modules depend on, then it definitely needs to be in the BOM, in order to ensure compatibility of all grpc modules when used together. I think we should just use the general rule of "if it appears in Maven Central, include it in the BOM."
