### ISSUE TITLE
No System.out in StaticLinkageChecker

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#227]
since we shouldn't be talking directly to the user from a library method. This will be important if we build this into tooling, especially maven and Gradle plugins. 

```
    Formatter formatter = new Formatter();
    formatter.format(
        "The number of resolved method references during linkage check: %,d",
        availableMethodsInJars.size());
    System.out.println(formatter);
    return unresolvedMethods;
```

Also Formatter is overkill here. This could more simply be:

```
"The number of resolved method references during linkage check: " + availableMethodsInJars.size()
```

**Comment by suztomo** [comment]
Right, it's overkill and now these println are unnecessary. I removed the formatter part.

For the use of command-line tool `printStaticLinkageErrors` is ok to have println, right?

**Comment by elharo** [comment]
Sure, if the purpose of the class is to output to the console, then that's OK. It shouldn't be a side effect though. We really do need to start using loggers instead of System.err.println though.
