### ISSUE TITLE
Add GSON to the BOM

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#2278]
Right now it gets pulled in transitively, but not necessarily in the latest version. 

This would address a minor issue encountered by protobuf customers.

Current version is 2.8.9.

**Comment by suztomo** [comment]
Investigating the problem. (The addition sounds feasible)

**Comment by suztomo** [comment]
This idea also helps when we need to quickly upgrade the patched version of gson (without waiting for other Cloud librareis' releases).

**Comment by elharo** [comment]
Any progress on this? If you're comfortable with the addition, I can send a PR.

**Comment by suztomo** [comment]
Let me do that today, for the upcoming release next week.
