### ISSUE TITLE
mvn --ntp

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#2279]
Starting with Maven 3.6.1 (released 2019-04-04) you can use --no-transfer-progress to suppress the output of downloading messages  like these:

[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/3.0.0-M4/surefire-3.0.0-M4.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/3.0.0-M4/surefire-3.0.0-M4.pom (27 KB at 1543.8 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-api/3.0.0-M5/surefire-extensions-api-3.0.0-M5.pom
[INFO] Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-extensions-api/3.0.0-M5/surefire-extensions-api-3.0.0-M5.pom (4 KB at 207.7 KB/sec)
[INFO] Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-booter/3.0.0-M5/surefire-booter-3.0.0-M5.pom

This would eliminiate a lot of log junk in the linkage moniotor and thus make the real issues more apparent.

**Comment by suztomo** [comment]
I thought we use the option already but I'll check anyplace missed.
