### ISSUE TITLE
Check google-oauth-client and google-api-client not being part of the Libraries BOM

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#2307]
CC: @claudio4j. Google HTTP Client is part of the Libraries BOM. How about the following two libraries?

- google-oauth-client
- google-api-client

(To dig dependencies)

**Comment by claudio4j** [comment]
Adding these libraries would be exactly what I need. Thanks.

**Comment by suztomo** [comment]
The artifacts with google-cloud-XXX usually do not depend on google-oauth-client and google-api-client. Even when some of them depend on the two libraries, I don't expect users need to touch classes from google-oauth-client or google-api-client.

For my learning, would you share where you do you see the need of declaring the two libraries?

**Comment by claudio4j** [comment]
https://github.com/apache/camel/blob/main/components/camel-google/camel-google-mail/src/main/java/org/apache/camel/component/google/mail/BatchGoogleMailClientFactory.java#L51

We use to process authentication, where we require the user to supply `clientId, clientSecret, refreshToken, accessToken`

**Comment by suztomo** [comment]
The BOM has moved to https://github.com/googleapis/java-cloud-bom repository.
