### ISSUE TITLE
Move the static linkage checker to a more transparent directory name

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/cloud-opensource-java#234]
The static linkage checker is currently located under https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/master/dependencies , which reveals very little about the tool. I think `/linkage-checker/` is a good candidate. I'm also thinking we don't want to paint ourselves into a corner with respect to checking static vs reflective errors; should we just call it the "Linkage Checker"? (Or maybe "Jar Linkage Checker" or "Classpath Linkage Checker"?)

**Comment by suztomo** [comment]
diamond-analyzer

**Comment by garrettjonesgoogle** [comment]
Ahh, I actually knew that previously, but forgot because the readme makes it look like this directory is only the static linkage checker.

In that case, I would suggest `dependency-tools`. The name `dependencies` makes it sound like it contains dependencies inside of it, and is very unintuitive.

I would also suggest renaming the current readme to `linkage-checker.md` and making a new readme which links to it, and describes the other tools too.
