### ISSUE TITLE
enforce-linkage-checker not compatible anymore with recent maven-enforcer-plugin

### ISSUE THREAD

**Issue by rfscholte** [GoogleCloudPlatform/cloud-opensource-java#2378]
The plugin fails with the following message:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce-linkage-checker) on XXX: Execution enforce-linkage-checker of goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce failed: A required class was missing while executing org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce: org/apache/maven/plugins/enforcer/AbstractNonCacheableEnforcerRule

**Comment by rfscholte** [comment]
@suztomo @zhumin8 are you maintaining this project and do you want a PR with a fix. The critical change was made between https://github.com/apache/maven-enforcer/compare/enforcer-3.1.0...enforcer-3.2.0
So the question is as well: which enforcer version should this rule support at least?

**Comment by suztomo** [comment]
Let me look into this.

**Comment by rfscholte** [comment]
You can have a look at https://github.com/GoogleCloudPlatform/cloud-opensource-java/compare/master...rfscholte:cloud-opensource-java:2378_update_enforcer_api although it is a bit bigger than just this fix.
