### ISSUE TITLE
Refactor StaticLinkageCheckOption

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#254]
It's only really used in one place. The purpose is to produce an `ImmutableList<Path>`:

```
  @VisibleForTesting
  static ImmutableList<Path> generateInputClasspathFromLinkageCheckOption(
      StaticLinkageCheckOption linkageCheckOption) throws RepositoryException {
    ImmutableList.Builder<Path> jarFileBuilder = ImmutableList.builder();

    // TODO(suztomo): add logic to convert Maven BOM to list of Maven coordinates as per README.md
    jarFileBuilder.addAll(linkageCheckOption.getJarFiles());
    for (String mavenCoordinates : linkageCheckOption.getArtifacts()) {
      jarFileBuilder.addAll(coordinatesToClasspath(mavenCoordinates));
    }
    return jarFileBuilder.build();
  }
```

What we may need is three static methods that take as input a BOM, list of maven coordinates, or list of jar files respectively and return an `ImmutableList<Path>` for each case.

**Comment by suztomo** [comment]
> have StaticLinkageCheckOption.parseArguments() return an ImmutableList<Path>

Initially it was similar design. Then having a class to represent a command line option makes easy to handle more options (e.g., report-only-reachable or entry points).
