### ISSUE TITLE
Is "linking"/"linkage" the best terminology?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/cloud-opensource-java#321]
(This is largely a personal perspective and just for a thought. You may well disregard if you think the status quo is good.)

About this repo, I've heard the words "static linkage" a lot of times in our team meetings, and because we are in the Java world, I've always wondered how this "static linking" translates in the Java context. I've looked into the Glossary today and finally got to understand what it is.

IMO, "linking", "linker", "static/dynamic linking", etc. are too ominipresent in computing where they specially refer to [_the_ linking stuff](https://kb.iu.edu/d/akqn) that everyone immediately thinks about, ominipresent to the point that people just can't use the word "linking" to refer to something else than _the_ linking in general computing. Even if we constrain the scope only to Java, I think the usual "linking" notion prevails, and for example, "linking" or "static linking" in this sense would refer to http://openjdk.java.net/jeps/178 and things like [`UnsatisfiedLinkError`](https://docs.oracle.com/javase/7/docs/api/java/lang/UnsatisfiedLinkError.html) (which, interestingly, extends `LinkageError`, where the "link" in the two exceptions refer to two different things, the usual "linking" and the "linking" from the JVM spec if I must be pedantic). And I find people do talk with the usual notion of "linking" in the Java space, e.g., [here](https://stackoverflow.com/questions/34084913/why-does-java-allow-only-dynamic-linking), [here](https://stackoverflow.com/a/39842811/1701388),  [here](https://stackoverflow.com/questions/42834707/how-to-statically-link-library-with-jvm), and [here](https://stackoverflow.com/questions/9558411/is-there-such-a-thing-as-static-jar-linking-in-java).

That said, I did realize [the JVM spec defines the term "linking"](https://docs.oracle.com/javase/specs/jls/se11/html/jls-12.html#jls-12.3), but I think the term is defined inside the scope of the spec and dies there. When not talking specifically about JVM spec, the other ominipresent "linking" takes over, IMO.

However, I do get that, if we expand the notion of the usual "linking" to "the act of making a program being able to locate/use/run reusable piece of binary code when running the program" and then stretch that further to "the act of locating/using/running some code when running a program", the gap between the usual "linking" and the "linking" from the JVM spec may be somewhat closed in a very general sense, but even in this sense, people will say [there is no such thing like "static linking" in Java, since JVM always does "dynamic linking"](https://stackoverflow.com/questions/26246875/is-linking-in-java-runtime-always-done-dynamically), if they must mention either "static" or "dynamic". (Funnily, the OP was actually talking about the omnipresent "linking", but the accepted answer made a reference to the "linking" from the JVM spec.) "Static linking" in Java doesn't exist at all, so no one will ever bother to say "dynamic". The point is, even in the sense of the JVM spec, what people conceive when hearing "static linkage" or "dynamic linkage" is even different from what "static linkage" and "dynamic linkage" mean in this repo. Because "static linking" and "dynamic linking" are also too omnipresent, just like that the usual "linking" takes over the the "linking" from the JVM spec, "static" and "dynamic" (when attached to the term "linking") take over what "static" and "dynamic" mean in this repo as well.

So for these reasons, I personally don't like "linking" used throughout in this repo. I wonder if "resolution" or "reference resolution" instead could work better. But to be fair, I'm not so strong on this. Just wanted to throw a chance to give a thought.

**Comment by suztomo** [comment]
Thank you for input. I feel "linkage" is a good fit for our purpose. Here is my thought.

# "Static Linkage"?

In the [glossary](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/2516f8bc2ccca113ea5031f7ba9266ad6eab7253/library-best-practices/glossary.md), "static linkage" does not exist (sorry if I mentioned this term verbally). The term "static" is to describe "linkage error" and "linkage conflict".

# "Static Linkage Checker"

I think this is the cause of confusion. It can read "checker for static linkage", implying the term "static linkage" (which I just denied above).

However, StaticLinkageChecker's [README](https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/57e0fa9bfacb131f4b1c92cb0ff9952266af386d/dependencies
) says

> Static Linkage Checker is a tool that finds static linkage errors on a class path 

So it's a shorthand for longer name "StaticLinkageErrorChecker".

# "Linking" in JVM

That JVM spec on ["linking"](https://docs.oracle.com/javase/specs/jls/se11/html/jls-12.html#jls-12.3) explains

> Three different activities are involved in linking: verification, preparation, and resolution of symbolic references.

- **Verification** identifies invalid of class hierarchy, e.g., a class extending a `final` class ([Binary Compatibility: 13.4.2. final Classes](https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html#jls-13.4.2))
- preparation is irrelevant to us
- **Resolution of symbolic references** identifies missing class or members of classes, e.g., accessing private field outside its class. ([Binary Compatibility: 13.4.7. Access to Members and Constructors](https://docs.oracle.com/javase/specs/jls/se11/html/jls-13.html#jls-13.4.7))

Both of the example cases of binary compatibility are mentioned in "linkage conflict" in the [glossary](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/2516f8bc2ccca113ea5031f7ba9266ad6eab7253/library-best-practices/glossary.md). So setting scope to "linking", not just "reference resolution", makes sense to me.

**Comment by elharo** [comment]
It's worth thinking about this further. I'm surprised no one noticed until now. "Static linking" normally refers to C-style linking when all the code is moved into a single binary. Java doesn't do that. It's always dynamic linking.

**Comment by suztomo** [comment]
The tool is going to be named as "Classpath Checker".
