### ISSUE TITLE
Document gRPC vs google-api-client

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#327]
Guava inconsistency if google-api-client 1.27.0 precedes grpc 1.17.0 (both latest releases as I type this)

io.grpc:grpc-core:0.17.1 and com.google.api-client:google-api-client:1.27.0  re Guava Verify

see Tomo's example

**Comment by suztomo** [comment]
I'll create a sample project directory as a showcase of the error.
