### ISSUE TITLE
Profile DashboardTest

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#352]
This takes far too long to run. I suspect the issue is network loading of the dependency graph. Anything we can do to speed this up, e.g. by caching artifacts or not loading them at all, should make generating the dashboard faster as well. 

Then again, the reason this has gotten slower may well be that we're doing static linkage checking as part of dashboard generation, and that does take a while. 

JProfiler session attached

[DashboardTest.jps.zip](https://github.com/GoogleCloudPlatform/cloud-opensource-java/files/2773982/DashboardTest.jps.zip)

**Comment by elharo** [comment]
Still trying to getJProfiler configured, but my initial measurements indeed show a little over half the time is going into `findStaticLinkageErrors1

**Comment by elharo** [comment]
More details: Fully 92 % of our time is spent inside 

org.apache.bcel.util.MemorySensitiveClassPathRepository.loadClass | 1,250 s (92 %) | n/a | n/a

which is called from

com.google.cloud.tools.opensource.classpath.ClassDumper.loadJavaClass

**Comment by suztomo** [comment]
Thank you for looking into this.

I’ve noticed that the DashboardTest takes longer than “exec:java”, although I expect they take almost same amount of time.
