### ISSUE TITLE
Library should produce pom.xml that reflects the actual versions of the library used for build

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-opensource-java#361]
If a library project with built w/ a BOM and/or dependency management section to manage the version of direct and/or transitive dependency, the resulting published `pom` will not reflect the versions used during the build nor unit tests.  Hence, runtime behavior may differ, and dependency versions become inconsistent.

Propose to investigate a way to produce a published `pom` that actually reflects the actual dependency version used during build.

**Comment by elharo** [comment]
Can you elaborate on what you mean by a "published pom" and exactly how it's created?
