### ISSUE TITLE
Proposal: every JLBP to have a paragraph at the beginning

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#372]
While most of JLBPs start with paragraphs, some JLBP ([JLBP-3](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-3.md) and [JLBP-14](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-14.md), for example) have a list immediately after their title, without a paragraph. Some of them are using lists as paragraphs. But they are unnecessarily inconsistent and sometimes I felt the background is missing.

So, I'm thinking to enhance their structure so that every JLBP starts with a paragraph, not a list. 

BTW, I like the way [JLBP-18](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-18.md) is written using the storytelling's pattern Ands -> However -> Therefore ([ABT](http://ian.umces.edu/blog/2016/09/20/story-telling-tools-the-history-of-communicating-well/))

@elharo @garrettjonesgoogle . What do you think?

**Comment by garrettjonesgoogle** [comment]
Seems reasonable. This would probably make them more approachable.

**Comment by elharo** [comment]
14 is done. 3 still needs to be done.
