### ISSUE TITLE
Consider documenting the difference between a Maven dependency tree and a Maven dependency graph

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#385]

**Comment by suztomo** [comment]
I'll work on that. The document should clarify

- Comparison with existing concept of a Maven dependency tree and a Maven Dependency Graph
- If we're introducing a new definition of a graph, then define it
  The new definition of a graph should have
  - explanation of nodes and edges.
  - difference from the existing concepts
  - the reason why it's introduced. How it helps Classpath Checker.

**Comment by elharo** [comment]
duplicate to #364  and see https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/Dependency-Graph-Design
