### ISSUE TITLE
Changing a method's signature so that its new return type is a subtype of its old return type

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#388]
Repeating internal discussion:

Changing a method's signature so that its new return type is a subtype of its old return type is API compatible, i.e. calling code written against library version N will compile against library version N+1. But it's not ABI compatible, i.e. calling code compiled against library version N will not run with library version N+1 on the class-path — because the return type is part of the method name in the bytecode, so the calling code will be referencing the version N name of the method and it won't be found in the version N+1 library jar. 

Make sure static linkage checker correctly reports this case.

**Comment by suztomo** [comment]
Yes, the tool handles such cases. When return type changes, then it shows error with `SYMBOL_NOT_FOUND`, because method lookup uses descriptor that includes return type.

https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/116#issuecomment-451583384
