### ISSUE TITLE
better display large chains of errors on dashboard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#395]
That is no need to show 2613 lines of output here; maybe combine cases where same class is missing.

```
appengine-api-1.0-sdk-1.9.64.jar (2613 errors):
  ClassSymbolReference{sourceClassName=com.google.appengine.api.appidentity.AppIdentityServicePb$SigningService$1, targetClassName=com.google.net.rpc3.client.RpcStubDescriptor, subclass=true}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=com.google.appengine.api.appidentity.AppIdentityServicePb$SigningService$BaseBlockingServerImpl, targetClassName=com.google.net.rpc3.RpcException, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=com.google.appengine.api.appidentity.AppIdentityServicePb$SigningService$BaseBlockingServerImpl, targetClassName=com.google.net.rpc3.impl.RpcUtil, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=com.google.appengine.api.appidentity.AppIdentityServicePb$SigningService$BaseServerImpl, targetClassName=com.google.net.rpc3.impl.RpcUtil, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=com.google.appengine.api.appidentity.AppIdentityServicePb$SigningService$BlockingServerInterface, targetClassName=com.google.net.rpc3.RpcException, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=com.google.appengine.api.appidentity.AppIdentityServicePb$SigningService$ClientInterface, targetClassName=com.google.net.rpc3.RpcException, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
 ```

**Comment by suztomo** [comment]
Now they are grouped to 101 lines.

![image](https://user-images.githubusercontent.com/28604/52098004-2efcf880-259b-11e9-976d-edaba2b3af43.png)

The scrolling got much better. Do you want to shorten them further?

**Comment by elharo** [comment]
possibly, but we can do this in stages

**Comment by suztomo** [comment]
Started thinking about the enhancement.

# Problems

After grouping them by classes, now the width is very big.
![image](https://user-images.githubusercontent.com/28604/52438500-66156180-2ae7-11e9-841f-5b062ab5d76b.png)

Too many paths to log4j.

![image](https://user-images.githubusercontent.com/28604/52438684-db813200-2ae7-11e9-9ef7-2a7772948520.png)

## Option 1

Only show first 5 items and remove others with "_, and more 989 items_", without providing way to show them all.

## Option 2

Add JavaScript (without framework) to shrink/expand items, via the message "_, and more 989 items_".

## Option 3

Generate new set of html pages that have detailed items.
Add links to the pages from the message "_, and more 989 items_".

**Comment by elharo** [comment]
For the width problems, maybe we need to not use a pre block, and perhaps format it on multiple lines

**Comment by elharo** [comment]
On the height issue I think we have an opportunity to do something beyond simply HTML. In particular, we should be able to recognize that all of these are essentially caused by

com.google.http-client:google-http-client:1.27.0 / com.google.android:android:1.5_r4 / commons-logging:commons-logging:1.1.1 / log4j:log4j:1.2.12

and report that. In other words. figure out that the real issue here is in com.google.http-client:google-http-client:1.27.0

**Comment by suztomo** [comment]
For removing `<pre>` in favor of multiple lines makes the list vertically long. I would say It just moves horizontal problem to vertical one.

For figuring out that `com.google.http-client:google-http-client:1.27.0` is the real issue. That's great finding. My naive implementation would be building __graph of Maven dependencies and find [disjoint sets](https://en.wikipedia.org/wiki/Disjoint-set_data_structure)__, which I feel  overkill for this issue.

For example, given dependency paths to artifact X
```
A -> B -> X
B -> X
C -> X
D -> B -> X
```
implementation would return
```
B -> X
C -> X
```

Let's discuss tomorrow.
