### ISSUE TITLE
Dashboard error message

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#42]
figure out why this happens:

First question: when does this happen? Is this the output of our app, or something that happens on writes to GCS, or on reads from GCS?

{"error":{"errors":[{"domain":"global","reason":"badLockedDomainRequest","message":"Bad Locked Domain Request","debugInfo":"Error extracting locked domain from query string\ncom.google.api.server.core.Fault: ImmutableErrorDefinition{base=BAD_LOCKED_DOMAIN_REQUEST, category=USER_ERROR, cause=null, debugInfo=Error extracting locked domain from query string, domain=global, extendedHelp=null, httpHeaders={}, httpStatus=badRequest, internalReason=Reason{arguments={}, cause=null, code=null, createdByBackend=false, debugMessage=null, errorProtoCode=null, errorProtoDomain=null, filteredMessage=null, location=null, message=null, unnamedArguments=[]}, location=null, message=Bad Locked Domain Request, reason=badLockedDomainRequest, rpcCode=400} Bad Locked Domain Request: Error extracting locked domain from query string\n\tat com.google.api.server.responsesafety.ApiRequestUriCrypter.getEncryptedApiRequest(ApiRequestUriCrypter.java:197)\n\tat com.google.api.server.responsesafety.ApiRequestUriCrypter.unlock(ApiRequestUriCrypter.java:107)\n\tat com.google.api.server.responsesafety.LockedStrategy.lockedDomainInterceptorRequest(LockedStrategy.java:81)\n\tat com.google.api.server.responsesafety.LockedDomainInterceptor.processRequest(LockedDomainInterceptor.java:59)\n\tat com.google.api.server.core.intercept.AroundInterceptorWrapper.processRequest(AroundInterceptorWrapper.java:20)\n\tat com.google.api.server.stats.StatsBootstrap$InterceptorStatsRecorder.processRequest(StatsBootstrap.java:278)\n\tat com.google.api.server.core.intercept.Interceptions$AroundInterception.processRequest(Interceptions.java:159)\n\tat com.google.api.server.core.intercept.Interceptions$AroundInterception.invoke(Interceptions.java:135)\n\tat com.google.api.server.media.AbstractMediaClosure.continueRequest(AbstractMediaClosure.java:64)\n\tat com.google.api.server.media.batch.BatchAgent.continueRequest(BatchAgent.java:141)\n\tat com.google.api.server.media.batch.BatchAgent.onRequestReceived(BatchAgent.java:74)\n\tat com.google.uploader.agent.ScottyBatchAgent$ServiceParameters$1.handleRequest(ScottyBatchAgent.java:418)\n\tat com.google.net.rpc3.impl.server.RpcServerInternalContext.runRpcInApplication(RpcServerInternalContext.java:577)\n\tat com.google.net.rpc3.impl.server.RpcServerChannel$1.apply(RpcServerChannel.java:879)\n\tat com.google.net.rpc3.impl.server.RpcServerChannel$1.apply(RpcServerChannel.java:867)\n\tat com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:240)\n\tat com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:230)\n\tat com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:117)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)\n\tat com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:323)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)\n\tat com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:1056)\n\tat com.google.api.server.thread.ThreadTrackers$ThreadTrackingRunnable.run(ThreadTrackers.java:126)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)\n\tat com.google.api.server.server.CommonModule$ContextCarryingExecutorService$1.runInContext(CommonModule.java:846)\n\tat com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)\n\tat com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)\n\tat com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)\n\tat com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)\n\tat com.google.gse.internal.DispatchQueueImpl$WorkerThread.run(DispatchQueueImpl.java:403)\n"}],"code":400,"message":"Bad Locked Domain Request"}}

**Comment by elharo** [comment]
Made bucket public and public link should work:

https://storage.googleapis.com/cloud-opensource-java-dashboard/prod/cloud-opensource-java/ubuntu/periodic/7/20180715-103104/dashboard/target/dashboard/dashboard.html

**Comment by briandealwis** [comment]
You can get rid of the progress information by running Maven in _batch mode_ with `mvn -B`.
