### ISSUE TITLE
Investigate inner classes

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#432]
This and others look suspicious:

com.google.appengine.repackaged.com.google.common.net.InetAddresses$TeredoInfo is not found, referenced from

com.google.appengine.repackaged.com.google.common.net.InetAddresses

Is it possible the linkage checker has a bug in finding inner classes?

**Comment by elharo** [comment]
It does appear that com.google.appengine.repackaged.com.google.common.net.InetAddresses$TeredoInfo is genuinely not present in the jar. I wonder if the repackaging tool that produces this jar does not automatically include inner classes when it includes a class?

**Comment by elharo** [comment]
Need to look at the source code of com.google.common.net.InetAddresses to see if it actually uses the  TeredoInfo class or just defines it. If it only defines it, this is a false positive.

**Comment by elharo** [comment]
`InetAddresses.getTeredoInfo` does return this type so this is a true positive.

**Comment by suztomo** [comment]
@elharo
Shall we close this?
