### ISSUE TITLE
Clarify end-of-life of Java version in JLBP-3

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#434]
Is Java 7 end-of-life?
https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

JLBP-3 says
> Special case: Maintainers do not have to increment a library's major version when a release is only to drop the support of an end-of-life Java version that is not widely used by the consumers of the library.

This is written implicitly thinking about Java 7, but today Ronald pointed that due to recent Oracle support policy change, Java 7 may not be officially "end-of-life".

This ticket is to clarify the gap in JLBP.

**Comment by elharo** [comment]
Can you elaborate? What are you asking for?

**Comment by suztomo** [comment]
Enriched the ticket.

**Comment by saturnism** [comment]
More precisely I think the original meaning was end of public updates.
