### ISSUE TITLE
Check appengine-api-1.0-sdk

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#441]
@suztomo Can we run a linkage check on appngine-api-1.0-sdk using everything in com.google.appengine as the entry points? That is, use a package as an entry point instead of a jar? I'd like to see  what's reachable from there.

We might want to enhance the reachability to consider methods too. Let's talk later.

**Comment by suztomo** [comment]
Memo:

Run `com.google.cloud.tools.opensource.classpath.ClasspathChecker` with

`-a com.google.appengine:appengine-api-1.0-sdk:1.9.64`

**Comment by suztomo** [comment]
Investigation done
