### ISSUE TITLE
Create latest public link to dashboard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#45]
That is instead of 

https://storage.googleapis.com/cloud-opensource-java-dashboard/prod/cloud-opensource-java/ubuntu/periodic/7/20180715-103104/dashboard/target/dashboard/dashboard.html

where the path components "7/20180715-103104/" change with every build, we need a stable URL such as 

https://storage.googleapis.com/cloud-opensource-java-dashboard/dashboard/dashboard.html

**Comment by elharo** [comment]
https://storage.googleapis.com/cloud-opensource-java-dashboard/dashboard/target/dashboard/dashboard.html works for the moment.

**Comment by chanseokoh** [comment]
I'm curious. How did you set the fixed URL, stripping out the build no./timestamp components? Is this automated?

**Comment by elharo** [comment]
cl/207902790

**Comment by chanseokoh** [comment]
Thanks! From its doc, looks like there is a caveat that it doesn't clean up the destination bucket.
