### ISSUE TITLE
DashboardTest is brittle against versions

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#466]
Easy enough to fix once we push a release BOM but we may be able to pin a snapshot too. 

https://stackoverflow.com/questions/1368625/maven-specific-version-of-a-snapshot-dependency

**Comment by suztomo** [comment]
Let me check this week.

**Comment by suztomo** [comment]
If the approach of #485 is good (and merged to master), then solution of this issue would be simple: just create a directory with a (fixed) pom.xml, and run DashboardTest with the file.
