### ISSUE TITLE
Investigate new linkage error in google-api-client-1.27.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#468]
google-api-client-1.27.0.jar
1 target class causing linkage errors referenced from 1 source class.

com.google.api.client.http.apache.ApacheHttpTransport$Builder is not found, referenced from 1 source class  ▼

com.google.api.client.googleapis.apache.GoogleApacheHttpTransport
The following paths to the jar file from BOM are found in the dependency tree.

com.google.cloud:google-cloud-translate:1.63.0 / com.google.cloud:google-cloud-core-http:1.63.0 / com.google.api-client:google-api-client:1.27.0
com.google.cloud:google-cloud-translate:1.63.0 / com.google.apis:google-api-services-translate:v2-rev20170525-1.27.0 / com.google.api-client:google-api-client:1.27.0

**Comment by elharo** [comment]
This is the code: https://github.com/googleapis/google-http-java-client/blob/master/google-http-client-apache/src/main/java/com/google/api/client/http/apache/ApacheHttpTransport.java

This PR may be relevant:

https://github.com/googleapis/google-http-java-client/commit/bf4a8dad3f44772504f0223544ab7b92c9bea3be#diff-a2171533e9e559802ade0026c92d3bdf

Problem may no longer exists at HEAD.

**Comment by suztomo** [comment]
Memo:

![image](https://user-images.githubusercontent.com/28604/53383231-e7bd1a00-3944-11e9-8c78-0451b9513481.png)

**Comment by suztomo** [comment]
I'm going to file an issue and create an exmaple project to produce an issue.

**Comment by suztomo** [comment]
https://github.com/googleapis/google-cloud-java/issues/4579 is filed and recorded in fixlog

**Comment by suztomo** [comment]
Investigation is done.
