### ISSUE TITLE
MacOS and Windows Continuous builds

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#475]
We recently committed a bug that only appeared on Macs. 

Probably use kokoro.

**Comment by suztomo** [comment]
I'll take a look

**Comment by suztomo** [comment]
The test fails with Windows. We haven't paid attention to Windows OS.

```
[ERROR] Failures: 
[ERROR]   LinkageCheckerTest.testFindClassReferences_privateClass:619 When the superclass is unavailable, it should report the location of InnerService
expected to end with: testdata/api-common-1.7.0.jar
but was             : T:\src\github\cloud-opensource-java\dependencies\target\test-classes\testdata\api-common-1.7.0.jar
```

**Comment by suztomo** [comment]
Kokoro works good. A build failure is recorded in Github correctly:

![image](https://user-images.githubusercontent.com/28604/53650735-31428900-3c13-11e9-9ae2-6dc2ea48a1f1.png)
