### ISSUE TITLE
LinkageCheckerRule: "opensource" is not a good identifier in groupId and package name.

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#497]
(feedback from Patrick)
https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/master/enforcer-rules

![image](https://user-images.githubusercontent.com/28604/54001631-f44a2b00-4119-11e9-9e4b-f3b6aa5fc11f.png)

These identifier "opensource" does not make sense from users' perspective. Let's pick up good one.

C.f. [appengine-maven-plugin](https://github.com/GoogleCloudPlatform/app-maven-plugin) has following groupId:

```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>appengine-maven-plugin</artifactId>
    <version>1.3.2</version>
</plugin>
```

[appengine-gradle-plugin](https://github.com/GoogleCloudPlatform/app-gradle-plugin#how-to-use):

```
  dependencies {
    classpath 'com.google.cloud.tools:appengine-gradle-plugin:1.3.3'
  }
```

[google-cloud-intellij](https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/build.gradle#L50):

```
    group = 'com.google.cloud.tools.intellij'
```

[google-cloud-eclipse](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/pom.xml#L7):

```
  <groupId>com.google.cloud.tools.eclipse</groupId>
```

**Comment by suztomo** [comment]
groupID: opensource -> maven
package: opensource -> maven

dependency-lister -> dependency

**Comment by elharo** [comment]
I think "dependencies" (plural) sounds a bit better for the artifact ID.

**Comment by netdpb** [comment]
Why are we using "maven" as part of the group ID? Are all our artifacts Maven-specific? The dashboard isn't, and neither is the linkage checker, right?

**Comment by patflynn** [comment]
That was what I was wondering as well.  If we want to specify a
'group/package root' for all the work in this project I'd suggest something
more descriptive of the use-case.

**Comment by elharo** [comment]
It **sort of** is Maven specific. More precisely, it's specific to the Maven repository system that extends beyond the Maven build tool and is also used by Ivy, Bazel, Gradle, and other systems. Open to other names that make this clearer.

**Comment by netdpb** [comment]
The dashboard and the linkage checker aren't. The dashboard checks things that are available in Maven, but that seems incidental. The linkage checker has options to check Maven dependency graphs, but it also works with non-Maven class paths, right?

If the world suddenly switched from Maven to some other repository system, we'd still want to solve the diamond dependencies problem, right?

Maybe "dependencies" is the right group word?

**Comment by patflynn** [comment]
I'd also be fine with analyzers.dependencies since we probably want to
build more of these project specific checkers.
dashboard could go in analyazers.dashboard.

**Comment by elharo** [comment]
We are very tied to the Maven repository system. The whole architecture of pom.xml files that we read to form dependency tress and graphs is straight from Maven. We load artifacts from Maven repos. BOMs come from Maven, and are only just beginning to be supported by Gradle. I'm not sure whether they help Ivy or bazel at all. 

If the world suddenly switched from Maven to some other repository system, we'd have to rewrite everything from scratch. The dashboard and the linkage checker are absolutely dependent on the Maven repository system. We could not easily port them to blaze and google3, for example.

Also, right now we only support the Maven dependency mediation algorithm. We do have a goal to support gradle dependency mediation too, but we haven't done so yet.

**Comment by suztomo** [comment]
(I'm still for "maven" for now)
Gradle also interacts with Maven artifacts in Maven repos. Still thinking something better.

**Comment by suztomo** [comment]
Listing my thought on group ID/package name as the root of our Java Diamond Dependency effort.

# com.google.cloud.tools.maven
- Sounds specific to Maven users although Maven artifacts and repository are dominant dependency management in Java.

# com.google.cloud.tools.dependencies
- Generic. Applicable even when we switch to another dependency system than Maven.

# com.google.cloud.tools.javadiamonddependencies
- too long
- Memo: [Google Style package name](https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names)

# com.google.cloud.tools.dependencies.analyzers
- com.google.cloud.tools.dependencies.analyzers
- com.google.cloud.tools.dependencies.dashboard

# com.google.cloud.tools.analyzers.dependencies
- com.google.cloud.tools.analyzers.dependencies
- com.google.cloud.tools.analyzers.dashboard

# com.google.cloud.tools

- This follows appengine-maven-plugin and appengine-gradle-plugin.
- Missing _'group/package root' for all the work in this project_

**Comment by suztomo** [comment]
Proposal with "dependencies". "Dependencies" is to reflect our Java Diamond _Dependency_ effort. (javadiamonddependency is too long word)

### /pom.xml (parent pom for subprojects except /boms)
  `com.google.cloud.tools.dependencies:cloud-tools-dependencies-parent`

### /dependencies/pom.xml   (library for analyzing Maven artifact dependency graphs)
  `com.google.cloud.tools.dependencies:dependency-analyzers`

### /enforcer-rules/pom.xml  (enforcer rule)
  `com.google.cloud.tools.dependencies:linkage-checker-enforcer-rules`

### /dashboard/pom.xml  (BOM dashboard)
  `com.google.cloud.tools.dependencies:bom-dashboard`

### /boms    (Cloud OSS BOM)
  This directory is out of scope of this change.

**Comment by suztomo** [comment]
Hygiene? (The top-level pom has "Cloud Tools Open Source Code Hygiene Tooling" already)

### /pom.xml (parent pom for subprojects except /boms)
  `com.google.cloud.tools.hygiene:cloud-tools-hygiene-parent`

### /hygiene/pom.xml   (library for analyzing Maven artifact dependency graphs)
  `com.google.cloud.tools.hygiene:dependency-analyzers`

### /enforcer-rules/pom.xml  (enforcer rule)
  `com.google.cloud.tools.hygiene:linkage-checker-enforcer-rules`

### /dashboard/pom.xml  (BOM dashboard)
  `com.google.cloud.tools.hygiene:bom-dashboard`

### /boms    (Cloud OSS BOM)
  This directory is out of scope of this change.

**Comment by suztomo** [comment]
Proposal "com.google.cloud.tools" as groupId, in the same manner as Maven and Gradle plugins.

### /pom.xml (parent pom for subprojects except /boms)
  `com.google.cloud.tools:cloud-tools-dependencies-parent`

### /dependencies/pom.xml   (library for analyzing Maven artifact dependency graphs)
  `com.google.cloud.tools:dependencies`

### /enforcer-rules/pom.xml  (enforcer rule)
  `com.google.cloud.tools:linkage-checker-enforcer-rules`

### /dashboard/pom.xml  (BOM dashboard)
  `com.google.cloud.tools:bom-dashboard`

### /boms    (Cloud OSS BOM)
  This directory is out of scope of this change.

**Comment by elharo** [comment]
I think just dashboard, not bom-dashboard

**Comment by suztomo** [comment]
Closing this with the proposal of "com.google.cloud.tools" as groupId with "dependencies" as artifactId of the library. (No "maven" as identifier)

@netdpb @patflynn When you are back with better names. Let's discuss further.
