### ISSUE TITLE
AutoValue is causing problems in Eclipse

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#508]
Consider removing it. 

![image](https://user-images.githubusercontent.com/1005544/54286033-72bf2680-4579-11e9-927d-a63fe77286fe.png)

**Comment by suztomo** [comment]
I'm happy to spend some time to investigate this issue (rather than start writing/reviewing `equals`, `hashCode`, `toString` by ourselves)
