### ISSUE TITLE
Shared release scripts for cloud-java-tool team

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#514]
Followup of https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/513 . Maybe helpful to learn from other teams who release Github projects in automated manner.

# Consideration

- Weakest link between builds (finding an artifact of previous step)
- Uploading multiple artifacts at once?
- Where to build (internet access), where to sign, and where to run publish script
- A failure on grep command immediately stops [release_publish.sh](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/kokoro/release_publish.sh#L33)

**Comment by elharo** [comment]
I think this is mostly done and/or covered by #1777
