### ISSUE TITLE
Circle CI does not need to install Cloud OSS BOM

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#521]
Once #485 is merged to master.

> If this works, we should be able to update .circleci/config.yml so it no longer manually installs the BOM before running tests.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/485

LinkageCheckerTest depends on the locally-installed BOM:

```
  @Test
  public void testGenerateInputClasspathFromLinkageCheckOption_mavenBom()
      throws RepositoryException, ParseException {
    String bomCoordinates = "com.google.cloud:cloud-oss-bom:pom:1.0.0-SNAPSHOT";

    LinkageCheckerArguments parsedArguments =
        LinkageCheckerArguments.readCommandLine("-b", bomCoordinates);
```

**Comment by elharo** [comment]
I think this should be done in the same PR #485. That will let us know that #485 works. Is there some reason we have to do it in two PRs?

**Comment by suztomo** [comment]
As discussed few tests depend on cloud-oss-bom. Let me update 485 to use another BOM.
