### ISSUE TITLE
Maven tool to check linkage errors involving user's project

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#528]
Enforcer-rules (that runs validate lifecycle) cannot depend on class files or artifact of users' projects.

We may want a Maven-integrated tool to check linkage errors involving users class.

This [maven-duplicate-finder-plugin](https://github.com/basepom/duplicate-finder-maven-plugin) reads class files in users project at "verify" phase (that requires the config below):

```
<plugin>
  <groupId>com.ning.maven.plugins</groupId>
  <artifactId>duplicate-finder-maven-plugin</artifactId>
  <executions>
    <execution>
      <phase>verify</phase>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

# But do we need to check linkage errors in users project?

If there are linkage errors whose source class is in user's project, the project wouldn't compile.

There can be rare cases where a class in a user's project shadows one in its dependency. But do we want to build the tool for such rare case?

**Comment by elharo** [comment]
"If there are linkage errors whose source class is in user's project, the project wouldn't compile."

True enough, but the user's project can change which linkage errors are and are not reachable.

**Comment by elharo** [comment]
We might be able to simply bind the enforcer plugin to a different phase. Let's experiment.

**Comment by elharo** [comment]
We can definitely bind a built-in enforcer rule to a different phase. Need to verify with this enforcer rule.

**Comment by elharo** [comment]
Cab bind the enforcer rule to that phase too. Debugging a NullPointerException. May be just #524 again.

**Comment by elharo** [comment]
I think the diagnosis of the problem wasn't quite right. Even after compile there's still a null pointer exception because there's no jar file. There is a classes directory and we need to use it.

**Comment by suztomo** [comment]
> reachability
Right. Side-effect on the reachabity part was missed. The current enforcer rule (with validate phase) implementation would unexpectedly mark linkage errors “unreachable” when user’s code references non-direct dependencies. These cases are “used and undeclared” in [dependency:analyze](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html)

Note that with current implementation, all classes in direct dependencies are reachable.


> Maven phase
Current LinkageChecker takes a list of jar files (not directory containing class files). If we want to analyze user’s classes, I think it’s easier to perform the check in a phase after “package” phase. (“verify” sounds right)
