### ISSUE TITLE
JLBP for Dependency Convergence

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-opensource-java#530]
I'm trying to find the verbiage where within a single project, all sub-modules should export the same versions of direct & transitive dependencies.  This discussion again came up during JavaLand w/ Maven committers on dealing dependency issues. 

For consumers, they are able to use upperBound. But for a single project with multiple modules, all modules must align.

**Comment by elharo** [comment]
what do you mean by "export dependencies"?

**Comment by saturnism** [comment]
i.e., if project P has modules A & B, their dependencies (direct & transitive) versions all agree.

**Comment by elharo** [comment]
With transitive, that's quite hard and last time we talked about this there was a lot of opposition to shooting for full dependency convergence. I can put this on the agenda for the team meeting if you'd like to make a case for this one.

**Comment by garrettjonesgoogle** [comment]
I think the only way to fully solve this is having support for output POM generation that includes transitive dependencies, making use of the dependency management of the library. 

https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-16.md captures the best practice for direct dependencies.

**Comment by elharo** [comment]
I think JLBP-16 covers this.

**Comment by garrettjonesgoogle** [comment]
1. I don't think JLBP-16 covers this
2. I'm happy this issue is closed anyway because I disagree with pursuing dependency convergence

**Comment by saturnism** [comment]
Dependency convergence within the same module and multi-module project is 100% achievable and the best practice.
