### ISSUE TITLE
Dependency Conflict: duplicate classes "org.apache.commons.logging.LogFactory" in different JARs, have different implementations

### ISSUE THREAD

**Issue by HelloCoCooo** [GoogleCloudPlatform/cloud-opensource-java#559]
Hi, in **cloud-opensource-java-0.1.2** (**\dependencies** module), duplicate classes with the same fully-qualified name _**org.apache.commons.logging.LogFactory**_ are included in two different libraries, i.e., **org.slf4j:jcl-over-slf4j:1.7.25** and **commons-logging:commons-logging:1.2**.

According to _"first declaration wins"_ class loading strategy, only this class in **_org.slf4j:jcl-over-slf4j:1.7.25_** can be loaded, and that in _**commons-logging:commons-logging:1.2**_ will be shadowed.

By further analyzing, your project expects to invoke method **_<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>_**  in _**commons-logging:commons-logging:1.2**_. As it has been shadowed, so that this method defined in **_org.slf4j:jcl-over-slf4j:1.7.25_** are actually forced to be referenced via the following invocation path:

```
<com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder: java.util.List getDirectDependencies(org.eclipse.aether.artifact.Artifact)> D:\testcase\TestProject\cloud-opensource-java-master\dependencies\target\classes
<com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder: org.eclipse.aether.graph.DependencyNode resolveCompileTimeDependencies(org.eclipse.aether.artifact.Artifact)> D:\testcase\TestProject\cloud-opensource-java-master\dependencies\target\classes
<org.eclipse.aether.internal.impl.DefaultRepositorySystem: org.eclipse.aether.resolution.DependencyResult resolveDependencies(org.eclipse.aether.RepositorySystemSession,org.eclipse.aether.resolution.DependencyRequest)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.internal.impl.DefaultArtifactResolver: java.util.List resolveArtifacts(org.eclipse.aether.RepositorySystemSession,java.util.Collection)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.internal.impl.DefaultArtifactResolver: java.util.List resolve(org.eclipse.aether.RepositorySystemSession,java.util.Collection)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.internal.impl.DefaultArtifactResolver: void performDownloads(org.eclipse.aether.RepositorySystemSession,org.eclipse.aether.internal.impl.DefaultArtifactResolver$ResolutionGroup)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-impl\1.1.1\maven-resolver-impl-1.1.1.jar
<org.eclipse.aether.connector.basic.BasicRepositoryConnector: void get(java.util.Collection,java.util.Collection)> D:\cEnvironment\repository\org\apache\maven\resolver\maven-resolver-connector-basic\1.3.1\maven-resolver-connector-basic-1.3.1.jar
<org.apache.http.impl.bootstrap.Worker: void run()> D:\cEnvironment\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar
<org.apache.http.protocol.HttpService: void handleRequest(org.apache.http.HttpServerConnection,org.apache.http.protocol.HttpContext)> D:\cEnvironment\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar
<org.apache.http.protocol.BasicHttpProcessor: void process(org.apache.http.HttpResponse,org.apache.http.protocol.HttpContext)> D:\cEnvironment\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar
<org.apache.http.client.protocol.ResponseAuthCache: void process(org.apache.http.HttpResponse,org.apache.http.protocol.HttpContext)> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient\4.5.6\httpclient-4.5.6.jar
<org.apache.http.impl.client.BasicAuthCache: void <init>()> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient\4.5.6\httpclient-4.5.6.jar
<org.apache.http.impl.client.BasicAuthCache: void <init>(org.apache.http.conn.SchemePortResolver)> D:\cEnvironment\repository\org\apache\httpcomponents\httpclient\4.5.6\httpclient-4.5.6.jar
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.Log getLog(java.lang.Class)> 
<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>

```
Although both of these two conflicting classes contain the referenced methods (with the same signature), they have different implementations. This issue will not lead to runtime crashes, but it can introduce inconsistent semantic hehavior by changing the control flows and data flows.

**_Workaround solution:_**
An easy way to workaround the problem is **_reversing the declaration order_** of these two libraries (i.e., reverse the declaration order of httpclient and maven-resolver-transport-http) in pom file. 
Then, according to **_"first declaration wins"_** class loading strategy, class _**org.apache.commons.logging.LogFactory**_ in _**commons-logging:commons-logging:1.2**_ can be loaded (the version that **cloud-opensource-java** expects to reference by static analysis).
This fix will not affect other libraries or class, except the above duplicate class.

### Dependency tree---
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ dependencies ---
[INFO] com.google.cloud.tools:dependencies:jar:0.1.2
[INFO] +- com.google.auto.value:auto-value-annotations:jar:1.6.2:compile
[INFO] +- org.apache.bcel:bcel:jar:6.2:compile
[INFO] +- org.apache.maven:maven-core:jar:3.6.0:compile
[INFO] |  +- org.apache.maven:maven-model:jar:3.6.0:compile
[INFO] |  +- org.apache.maven:maven-settings:jar:3.6.0:compile
[INFO] |  +- org.apache.maven:maven-settings-builder:jar:3.6.0:compile
[INFO] |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:compile
[INFO] |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[INFO] |  +- org.apache.maven:maven-builder-support:jar:3.6.0:compile
[INFO] |  +- org.apache.maven:maven-repository-metadata:jar:3.6.0:compile
[INFO] |  +- org.apache.maven:maven-artifact:jar:3.6.0:compile
[INFO] |  +- org.apache.maven:maven-plugin-api:jar:3.6.0:compile
[INFO] |  +- org.apache.maven:maven-model-builder:jar:3.6.0:compile
[INFO] |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.3.1:compile
[INFO] |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.3.3:compile
[INFO] |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.3.1:compile
[INFO] |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.3.1:compile
[INFO] |  +- org.apache.maven.shared:maven-shared-utils:jar:3.2.1:compile
[INFO] |  |  \- commons-io:commons-io:jar:2.5:compile
[INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3:compile
[INFO] |  |  \- javax.enterprise:cdi-api:jar:1.0:compile
[INFO] |  |     \- javax.annotation:jsr250-api:jar:1.0:compile
[INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:compile
[INFO] |  +- com.google.inject:guice:jar:no_aop:4.2.1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- org.codehaus.plexus:plexus-utils:jar:3.1.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[INFO] |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] +- org.apache.maven:maven-compat:jar:3.6.0:compile
[INFO] |  +- org.codehaus.plexus:plexus-interpolation:jar:1.25:compile
[INFO] |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.2.0:compile
[INFO] +- org.apache.maven:maven-resolver-provider:jar:3.6.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] +- org.apache.maven.resolver:maven-resolver-transport-http:jar:1.3.3:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.10:compile
[INFO] |  \- _**org.slf4j:jcl-over-slf4j:jar:1.7.25:runtime**_
[INFO] +- org.apache.maven.resolver:maven-resolver-transport-file:jar:1.3.3:compile
[INFO] +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.3.3:compile
[INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.6:compile
[INFO] |  +- _**commons-logging:commons-logging:jar:1.2:compile**_
[INFO] |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- commons-cli:commons-cli:jar:1.4:compile
[INFO] +- com.google.guava:guava:jar:27.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:2.5.2:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO] |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.google.truth:truth:jar:0.42:test
[INFO] |  +- org.checkerframework:checker-compat-qual:jar:2.5.3:test
[INFO] |  \- com.googlecode.java-diff-utils:diffutils:jar:1.3.0:test
[INFO] +- com.google.truth.extensions:truth-java8-extension:jar:0.42:test
[INFO] \- com.google.guava:guava-testlib:jar:27.1-jre:test

Thank you very much.
Best,
Coco

**Comment by HelloCoCooo** [comment]
Code snippet of **_<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>_** in _**org.slf4j:jcl-over-slf4j:jar:1.7.25:compile**_ (loaded version):
![01](https://user-images.githubusercontent.com/46306510/55683799-534bcb80-5976-11e9-800a-a3b00a00cafa.png)

Code snippet of **_<org.apache.commons.logging.LogFactory: org.apache.commons.logging.LogFactory getFactory()>_** in _**commons-logging:commons-logging:jar:1.2:compile**_ 
 (shadowed but expected to invoke method):
![02](https://user-images.githubusercontent.com/46306510/55683800-5777e900-5976-11e9-82f0-3e7a8e44bff2.png)
**.......**


As a result, these conflicting method included in **commons-logging:commons-logging:jar:1.2:compile** deals with different cases, which changes the control flows and data flows. So being forced to use these methods in **org.slf4j:jcl-over-slf4j:jar:1.7.25:compile** may lead to inconsisitent semantic behaviors.

**Comment by HelloCoCooo** [comment]
May I pull a request to fix it?
Thanks for your attention.

**Comment by elharo** [comment]
From the graph it looks like this should be addressed in org.apache.httpcomponents
