### ISSUE TITLE
Database table organization for linkage problems

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#574]
Moving @netdpb's comments from a PR:

I feel like there's a bigger refactoring that could clarify a lot of names and concepts. Right now SymbolReference combines the (target) symbol being referred to with the (source) class that is referring to it. That means you have to later separate out the "cause" (which I think is the symbol being referred to and the problem with it, what I would call the "error") and the source of that "cause".

Rather than that, would it be simpler to have the following?

*    a Symbol type (subtypes MethodSymbol, FieldSymbol, ClassSymbol): basically SymbolReference without the source class
 *   a ClassInJar type (JAR + class)
 *   a SymbolProblem type (symbol + reason + optional ClassInJar for anything other than top-level class not found): replaces SymbolNotResolvable
 *   a multimap from source ClassInJar to SymbolProblem

Then you don't have a notion of a "cause": you have SymbolProblems representing erroneous references from source ClassInJars. You can invert that multimap to show all source classes for a given error. You can also show all errors in a target class, separated by error type and source class.

Food for thought for a future CL.

Other notes:

SymbolError --> SymbolProblem or ProblemSymbol

On discussion we would have 

 *   a multimap from ClassInJar to Symbols (defined in that ClassInJar) 
 *   a multimap from Symbol to SymbolProblem

In SQL terms this prduces a four column queryable table like this:

ClassInJar | ProblemReason | ErrorClassInJar | Symbol

ErrorClassInJar is an optional location for where a method/field is but has the wrong access.

**Comment by suztomo** [comment]
Started writing go/linkage-check-database .

**Comment by suztomo** [comment]
- Define value classes (#595)
- Extract symbol references from jar files using value classes  (#597 )
- (In)validate the symbol references against the class path
- Populate the invalidated to the dashboard
- Populate the invalidated to the enforcer rule

**Comment by suztomo** [comment]
Finished the refactoring (detail in previous comment)
