### ISSUE TITLE
spring-cloud-gcp memory issue

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#653]
Thanks to ConstantUtf8 cache (my local modification with `MAX_CACHE_ENTRIES=2000000` and `bcel.maxcached.size=200`), "Spring Cloud GCP Autoconfigure Module" in spring-cloud-gcp does not fail with "OutOfMemoryError: GC overhead limit exceeded".

However, even with the ConstantUtf8 cache , the enforcer rule applied on [spring-cloud-gcp project](https://github.com/spring-cloud/spring-cloud-gcp/tree/linkage-checker) fails at spring-cloud-gcp-kotlin-app-sample (the last module in spring-cloud-gcp):

![image](https://user-images.githubusercontent.com/28604/58901856-f6e3fe80-86cf-11e9-80f0-a805733ccb30.png)

JProfiler shows 606 MB is used for `LinkedHashMap$Entry` instances. The biggest entries are held by `SymbolReferenceMaps`' `ImmutableSetMultimap.Builder`.

![image](https://user-images.githubusercontent.com/28604/58901606-889f3c00-86cf-11e9-9e45-d5e2a687c628.png)

# Memo

Maven option to let a debugger attach the process:
```
export MAVEN_OPTS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
```

Maven option to heapdump upon OutOfMemoryError:
```
 export MAVEN_OPTS='-XX:+HeapDumpOnOutOfMemoryError'
```

**Comment by elharo** [comment]
That's strange. I'd expect builders to be short-lived objects. Maybe we have a memory leak somewhere?

**Comment by suztomo** [comment]
Yes something is memory-leaking because an enforcer rule single invocation at the kotlin-sample-app directory passes.

I think the Builder is behaving as expected though. It’s scanning many class files in many jar files until JVM encounters OutOfMemoryError.

**Comment by suztomo** [comment]
Linkage Checker performs two steps:
- Step 1: Build `SymbolReferenceMaps`
- Step 2: Verify the references in the `SymbolReferenceMaps`.



**Failed case** (OutOfMemoryException at the end of mvn verify in the root directory, at the end of Step 1 of spring-cloud-gcp-kotlin-app-sample module):
- `java.util.LinkedHashMap$Entry` deep size 606 MB
   - `SymbolReferenceMaps$Builder` deep size 270 MB
- `ClassPathRepository` deep size 426 MB
  - `_loadedClasses`: 42195
- `ConstantUtf8$CACHE_HOLDER$1` deep size 157 MB

**Successful case** (mvn verify in `spring-cloud-gcp-kotlin-sample/spring-cloud-gcp-kotlin-app-sample`,  paused at the end of Step 1):
- `java.util.LinkedHashMap$Entry` deep size 460 MB
  - `SymbolReferenceMaps$Builder` deep size 298 MB
- `ClassPathRepository` deep size 471 MB
  - `_loadedClasses`: 46256
- `ConstantUtf8$CACHE_HOLDER$1` deep size 114 MB

**Comment by suztomo** [comment]
Using this unit test to analyze spring-cloud-gcp jar files:

```
  @Test
  public void testMemoryUsage() throws Exception {
    List<Path> paths = new ArrayList<>();
    for (String jar : jars) {
      paths.add(Paths.get(new URI("file://" + jar)).toAbsolutePath());
    }

    LinkageChecker linkageChecker = LinkageChecker.create(paths, paths);
    linkageChecker.findSymbolProblems();
  }
```

The following table compares three implementations with 1G/2G heap size:

Repository Implementation | Heap Size | Result
------------ | ------------- | --------
ClassPathRepository|1G| OutOfMemoryError: gc overhead limit exceeded
ClassPathRepository|2G|10.957 s
MemorySensitiveClassPathRepository|1G|OutOfMemoryError: gc overhead limit exceeded
MemorySensitiveClassPathRepository|2G|10.859 s
NoCachingClassPathRepository|1G|134.823 s
NoCachingClassPathRepository|2G|135.752 s

**Comment by suztomo** [comment]
Performance evaluation of new `FixedSizeClassPathRepository`:

![image](https://user-images.githubusercontent.com/28604/59130235-d9679c80-893c-11e9-968e-6a405979e5b2.png)

Maximum cache size 500-1000 gives the best performance.
