### ISSUE TITLE
com.google.guava:guava-jdk5:13.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#699]
This is in the BOM tree. WTF?!

Figure out where it's coming from and remove it at the source.

**Comment by suztomo** [comment]
![image](https://user-images.githubusercontent.com/28604/60107743-6c724600-9735-11e9-821c-76484cd08da4.png)

Let me see.

**Comment by suztomo** [comment]
It's this.

- com.google.cloud:google-cloud-datastore:1.73.0
  - com.google.cloud.datastore:datastore-v1-proto-client:1.6.0
    - com.google.api-client:google-api-client:1.20.0
      - com.google.guava:guava-jdk5:13.0`

![image](https://user-images.githubusercontent.com/28604/60109068-af351d80-9737-11e9-94b0-c33f2f637e18.png)

 The latest google-api-client does not depend on guava-jdk5.


datastore-v1-proto-client is available in https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/master/java/datastore/pom.xml. It's parent pom defines google-api-client version 1.28.0 ([source](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/master/java/pom.xml)). But it has not yet released?

**Comment by elharo** [comment]
seem to be fixed
