### ISSUE TITLE
Truth output in MaximumLinkageErrorsTest is unreadable

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#700]
when there's a failure. Need to format this much better and probably not depend on Truth here. 

This continues for many pages. We need to carefully format and list each new error.

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MaximumLinkageErrorsTest.textMaximumLinkageErrors:54 Not true that <{Class com.google.net.rpc3.client.RpcStubDescriptor is not found=[ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.appidentity.AppIdentityServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.blobstore.BlobstoreServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.capabilities.CapabilityServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.files.FileServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.images.ImagesServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.mail.MailServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.mail.MailStubServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.memcache.MemcacheServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.modules.ModulesServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.prospectivesearch.ProspectiveSearchPb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.socket.SocketServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.taskqueue.TaskQueuePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.urlfetch.URLFetchServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.api.xmpp.XMPPServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.repackaged.com.google.appengine.api.search.SearchServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.repackaged.com.google.datastore.v1.Datastore}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.appengine.repackaged.com.google.protos.gdata.proto2api.Core}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.apphosting.api.UserServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.apphosting.api.logservice.LogServicePb}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.apphosting.datastore.DatastoreV4}, ClassFile{jar=/home/elharo/.m2/repository/com/google/appengine/appengine-api-1.0-sdk/1.9.71/appengine-api-1.0-sdk-1.9.71.jar, className=com.google.protos.cloud.sql.SqlService}], Class com.google.net.rpc3.RpcExcepti

**Comment by cpovirk** [comment]
Sorry :( Fixing the Truth message is on our list for the next time we dedicate some time to Truth after release 1.0 (see internal bug "Migrate old failWithRawMessage calls to the new message format and APIs"), but working around it is definitely the way to go now.
