### ISSUE TITLE
LinkageMonitor: create uber jar

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#712]
LinkageMonitor: create uber jar with dependencies. Learn from google-java-format tool.
https://github.com/google/google-java-format/blob/master/core/pom.xml

**Comment by elharo** [comment]
What's the purpose of this?

**Comment by suztomo** [comment]
To create a JAR file containing all dependencies so that the a presubmit Kokoro job can run linkage monitor as:

```
curl http://.../linkage-monitor-X.Y.Z-all-deps.jar
java -jar linkage-monitor-X.Y.Z-all-deps.jar
```

https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/master/linkage-monitor#usage
