### ISSUE TITLE
Kokoro Job for google-http-java-client

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#718]
This is my note about how Kokoro job for Linkage Monitor is setup.

One of existing jobs: "cloud-devrel/client-libraries/java/google-http-java-client/presubmit/java8".

![image](https://user-images.githubusercontent.com/28604/59463120-36f36180-8df3-11e9-816c-5e15ef8d6b0c.png)

Proposal: create the following files in Piper and google-http-java-client GitHub repository:

## Kokoro job config linkage-monitor.cfg
A new Kokoro job config file as a sibling of the `java8.cfg` in Piper.

## Kokoro build config .kokoro/presubmit/linkage-monitor.cfg

A new Kokoro build config file as a sibling of `.kokoro/java8.cfg`

Similar to [.kokoro/presubmit/java8.cfg](https://github.com/googleapis/google-http-java-client/blob/master/.kokoro/presubmit/java8.cfg) but having "linkage-monitor.sh" for [TRAMPOLINE_BUILD_FILE](https://github.com/googleapis/google-http-java-client/blob/master/.kokoro/presubmit/common.cfg#L18)

## .kokoro/linkage-monitor.sh

A new shell script to install snapshot google-http-java-client locally and run linkage monitor.

Similar to [.kokoro/build.sh](https://github.com/googleapis/google-http-java-client/blob/master/.kokoro/build.sh) but not running test but running LinkageMonitor.

```
mvn install -DskipTests

curl http://... linkage-monitor-all-deps.jar   # A GCS URL which suztomo will create
java -jar linkage-monitor-all-deps.jar "com.google.cloud:libraries-bom"
```

Todo: talk this to Elliotte, and then Jeff.

**Comment by suztomo** [comment]
Elliotte ok-ed about the design.

@chingor13 What do you think? If you're ok, I'll make CL and PR for the these files.

**Comment by chingor13** [comment]
Sounds good to me. Long term, we could possibly package this in a docker image which could have the linkage-monitor and the shell script already included for maximum portability.

**Comment by elharo** [comment]
Can kokoro run a docker image? That would be great if so. Heck, we could even use jib to build the image if we want to be ultra-cool. :-)

**Comment by chingor13** [comment]
Yep, all of our Java versioned tests for google-cloud-java and related libraries run on Kokoro via docker. We maintain our test images here: https://github.com/googleapis/testing-infra-docker/tree/master/java

**Comment by suztomo** [comment]
It works!

![image](https://user-images.githubusercontent.com/28604/59629512-040dde00-9111-11e9-82e8-4e03efb8030f.png)
