### ISSUE TITLE
Test artifacts exist

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#72]
The BOM needs a test that all the artifacts referenced are in Maven Central.

Just realized I incorrectly hyphenated one. Found it in another test but there should be a direct test for this. The libraries.json tests in appengine-plugins-core have code like this.

**Comment by vgrankina** [comment]
Can I work on this one?

**Comment by elharo** [comment]
Sure, happy to have you. You need to sign the [Google Individual Contributor License Agreement](https://cla.developers.google.com/about/google-individual?csw=1) before we can merge. The presubmit checks will take care of that.
