### ISSUE TITLE
LinkageMonitor.findHighestVersion needs to use RemoteRepository?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#723]
Does LinkageMonitor.findHighestVersion need to use RemoteRepository?

LinkageMonitor only needs to check local repository but Aether's [VersionRangeRequest](https://maven.apache.org/resolver/apidocs/org/eclipse/aether/resolution/VersionRangeRequest.html) takes remote repository.

**Comment by elharo** [comment]
Why wouldn't LinkageMonitor need the remnote repository? At this level, I'd expect the repository locaiton to be hidden.

**Comment by suztomo** [comment]
findHighestVersion has been removed from Linkage Monitor already.

BTW, this is a tool to look at local repository: https://maven.apache.org/maven-indexer/
