### ISSUE TITLE
Should RepositoryUtility respect mirror in user's settings.xml?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#734]
Users can set mirror via https://maven.apache.org/settings.html for normal maven invocation.

Even after #733 , our RepsitoryUtility.createDefaultRepositorySystemSession does not respect the setting currently.

I think I'll need something like this by reading settings.xml via [DefaultSettingsBuilderFactory](https://maven.apache.org/ref/3.6.0/apidocs/org/apache/maven/settings/building/DefaultSettingsBuilderFactory.html).
```
  private static DefaultRepositorySystemSession createDefaultRepositorySystemSession(
      RepositorySystem system) {
    DefaultRepositorySystemSession session = MavenRepositorySystemUtils.newSession();
    LocalRepository localRepository = new LocalRepository(findLocalRepository().getAbsolutePath());
    session.setLocalRepositoryManager(system.newLocalRepositoryManager(session, localRepository));

    session.setMirrorSelector(
        new MirrorSelector() {
          @Override
          public RemoteRepository getMirror(RemoteRepository repository) {
            System.out.println("Getting mirror for " + repository);
            if ("central".equals(repository.getId())) {
              System.out.println("Returning Google Mirror");
              return RepositoryUtility.GOOGLE_MIRROR;
            }
            return null;
          }
        });
    return session;
  }

```

In Kokoro Windows, it's `user.home=C:\Users\builder` = `env.USERPROFILE=C:\Users\builder`

**Comment by elharo** [comment]
I'm not sure about this. Our code should not depend on which user runs it or what they have in their home directory.

**Comment by suztomo** [comment]
Our code will not depend on user's settings.xml. This idea is to respect users' mirror configuration in settings.xml. Users (including our Kokoro jobs) will benefit from this idea when connection to Maven Central is not stable.

**Comment by elharo** [comment]
I still think this is confusing code and external configuration. We do not want this code to depend on what some file outside the project says. It should be complete in the API.

**Comment by suztomo** [comment]
This should be explicit if we want.
