### ISSUE TITLE
DashboardMain to have option to run all versions of a BOM

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#737]
DashboardMain to take a parameter `-a <groupId>:<artifactId>`. For example

```
DashboardMain -f ../bom/pom.xml
DashboardMain -c com.google.cloud:libraries-bom:1.2.2
DashboardMain -a com.google.cloud:libraries-bom  # New!
```

It will

- fetch versions via [VersionRangeRequest](https://maven.apache.org/resolver/apidocs/org/eclipse/aether/resolution/VersionRangeRequest.html)
- run `DashboardMain.generate(String bomCoodinates)` for each version

This does not touch index page: #702 yet.

**Comment by netdpb** [comment]
Why do we want to run on _all_ versions of a BOM?

**Comment by suztomo** [comment]
It’s because we want to run the check for all versions using the latest implementation of dashboard and Linkage Checker. It helps to see the evolution of the BOM.

**Comment by netdpb** [comment]
OK. Might be better to specify a version range.

**Comment by netdpb** [comment]
At the very least, rather than a new option, just allow users to specify `*` as the version, or an actual Maven version range.

```
DashboardMain -c 'com.google.cloud:libraries-bom:*'
DashboardMain -c 'com.google.cloud:libraries-bom:[0,)'
```

**Comment by suztomo** [comment]
That’s a nice idea. I like leveraging the version range. Let me incorporate that.

**Comment by elharo** [comment]
I don't think we need to complicate this with version ranges. It's not like doing all of them is more expensive than doing some, and the code will be simpler. YAGNI.

**Comment by netdpb** [comment]
You don't need to support version ranges. I think it's simpler to have `-c` take either _artifact_:_group_:_version_ or _artifact_:_group_:* than to have a separate `-a` option.
