### ISSUE TITLE
dependencies of a provided dependency

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#748]
Given that A depends on B.
B is provided.
B depends on C.

Is the environment expected to provide C as well?

**Comment by elharo** [comment]
short answer: yes

see https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

**Comment by suztomo** [comment]
Memo.

Q. If dependency conflict happens far from the root project via provided dependency. Is it unactionable message for root project's owner?

A. It's actionable by upgrading the version of the direct dependency that has the conflict. Even though the dependency tree may contain "provided" nodes in the path to the conflicting leaf, we can think of this _as same as normal (non-optional) dependency_. The container of runtime (which has newer version) may not have conflicts; then upgrade the dependency to that version.
