### ISSUE TITLE
LinkageMonitor to respect maven.repo.local

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#754]
Protobuf uses maven.repo.local to install the artifacts. Linakge Monitor does not look at the place.

http://sponge2/6dd9c8e1-a949-4010-9079-467d47109288

**Comment by elharo** [comment]
Why does this matter? Shouldn't everything come from Maven Central?

**Comment by suztomo** [comment]
Linkage Monitor uses "SNAPSHOT" version installed locally.

**Comment by elharo** [comment]
Why does it do that? It seems we shouldn't be checking against snapshots.

**Comment by elharo** [comment]
Wait, this is just for checking protobuf itself, right? That is, we're not depending on a snapshot version, we're checking a snapshot version?

**Comment by elharo** [comment]
And in that case why does it matter where it's installed? We can put it anywhere we like.

**Comment by suztomo** [comment]
As per discussion, if https://github.com/protocolbuffers/protobuf/pull/6318 is ok not to use `-Dmaven.repo.local=$MAVEN_LOCAL_REPOSITORY`, then this issue can be closed.

Another option would be to explicitly specify location of a JAR file for a pair of groupId and artifactId.

```
java -jar linkage-monitor-all-deps.jar -a <groupId>:<artifactId>:xyz/target/xyz.jar -a <groupId>:<artifactId>:abc/target/abc.jar
```

**Comment by suztomo** [comment]
protocolbuffers/protobuf#6318 was ok. Not taking this further.
