### ISSUE TITLE
Enforcer Rule to use Repository Session that accepts all scopes but tests

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#762]
Enforcer Rule to use Repository Session that accepts all scopes but tests.

Alternate way to address the false positive #757 .

# Does this implementation reads exclusion?

No, it does not.

![image](https://user-images.githubusercontent.com/28604/60600757-c9e24480-9d7e-11e9-93d4-07e5c9bbb1d8.png)

So NonTestDependencySelector needs to be combined with ExclusionDependencySelector

**Comment by suztomo** [comment]
The number of JAR files in the class path:
It was 81
Now 38

Previously all direct dependencies including `test` are in the class path for the linkage checker. With this change, `test` scope are excluded even if it's direct dependencies, and thus we no longer see the error of byte-buddy-agent (which came from mockito test library)

**Comment by elharo** [comment]
Neat. That's a big improvement and a huge bug ifx we didn't know we needed.
