### ISSUE TITLE
Problem after aborting a release

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#791]
Looks like we can't create two release candidates on the same day. 

Rapid could not generate a new release name. The release naming pattern may be too restrictive.

**Comment by suztomo** [comment]
You can type any value for Rapid RC name. It just does not fill it automatically for 2nd RC in a day.

**Comment by elharo** [comment]
Yes, we should f8igure out how to make it autofill.

**Comment by suztomo** [comment]
I updated naming pattern for the release `${project}_${date|fmt=yyyyMMdd}_${counter|start=1|pad=2}`. I'll close this issue once you confirm the effect.

**Comment by suztomo** [comment]
Example:
https://rapid.corp.google.com/#/project/cloud-java-tools-cloud-opensource-java-parent-kokoro-release?showInactive=false
