### ISSUE TITLE
DependencyGraphBuilder ignoring exclusions

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#799]
![image](https://user-images.githubusercontent.com/28604/61961761-17c12580-af96-11e9-88ba-2a4885bf560f.png)

Running `DependencyTreePrinter` with `com.google.cloud.tools:jib-maven-plugin:1.4.1-SNAPSHOT` fails:

```
com.google.cloud.tools:jib-maven-plugin:1.4.1-SNAPSHOT : Failed to retrieve dependency information:There were failure(s) in dependency resolution
com.google.cloud.tools:jib-maven-plugin:jar:1.4.1-SNAPSHOT (compile) / org.apache.maven:maven-plugin-api:jar:3.6.1 (compile) / org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3 (compile) / javax.enterprise:cdi-api:jar:1.0 (compile) / org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 (compile?) / org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 (compile): org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 in central (http://repo1.maven.org/maven2/)
com.google.cloud.tools:jib-maven-plugin:jar:1.4.1-SNAPSHOT (compile) / org.apache.maven:maven-core:jar:3.6.1 (compile) / org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3 (compile) / javax.enterprise:cdi-api:jar:1.0 (compile) / org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 (compile?) / org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 (compile): org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 in central (http://repo1.maven.org/maven2/)
com.google.cloud.tools:jib-maven-plugin:jar:1.4.1-SNAPSHOT (compile) / org.apache.maven:maven-core:jar:3.6.1 (compile) / org.apache.maven:maven-plugin-api:jar:3.6.1 (compile) / org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3 (compile) / javax.enterprise:cdi-api:jar:1.0 (compile) / org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 (compile?) / org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 (compile): org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0 in central (http://repo1.maven.org/maven2/)
```

[`org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3`](https://search.maven.org/artifact/org.eclipse.sisu/org.eclipse.sisu.plexus/0.3.3/eclipse-plugin) dependency with exclusions:

```
    <dependency>
      <groupId>javax.enterprise</groupId>
      <artifactId>cdi-api</artifactId>
      <version>1.0</version>
      <exclusions>
        <exclusion>
          <groupId>javax.el</groupId>
          <artifactId>el-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.ejb3</groupId>
          <artifactId>jboss-ejb3-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jboss.interceptor</groupId>
          <artifactId>jboss-interceptor-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

DependencyGraphBuilder does not take the exclusion element into account, and thus `DependencyTreePrinter` fails due to missing artifacts (`org.jboss.ejb3:jboss-ejb3-api:jar:3.1.0`).

This is not a problem in the enforcer rule because the enforcer rule does not use DependencyGraphBuilder. But problematic for #795 as I was thinking to use DependencyGraphBuilder to get the path information.

# Example: io.grpc:grpc-core

`io.grpc:grpc-core:1.13.1` excludes guava in opencensus-api. Should dashboard's linkage check and dependency convergence respect the exclusions?

![image](https://user-images.githubusercontent.com/28604/61960336-425daf00-af93-11e9-8788-9c34be97a818.png)

**Comment by suztomo** [comment]
It turns out that #795 does not need to use DependencyGraphBuilder to get dependency tree. But I keep this issue open.

**Comment by suztomo** [comment]
Discussed with Elliotte.

Given this setup:
```
Project A
+ Project B
|   exclusion: guava
+ guava:20

Project B
+ guava:19
```

Dashboard's Dependency Convergence should report the different versions of guava. Based on this, the tree used by Dependency Convergence should ignore exclusions.

**Comment by elharo** [comment]
1. Verify what maven enforcer dependency convergence rule does in this circumstance
2. Add docs about this to Maven enforcer rule docs if needed
3. Make dashboard sync up with Maven convergence rule behavior
4. Is there a superconvergence that does not respect exclusions?

**Comment by suztomo** [comment]
>  maven enforcer dependency convergence rule 

Dependency convergence rule respects exclusion elements. Example: https://stackoverflow.com/questions/36725439/dependency-convergence-error .
