### ISSUE TITLE
Cloud Endpoints Frameworks in Google Cloud BOM?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#841]
During the troubleshooting on [NoSuchMethodError when using Spring Spanner starter](https://github.com/spring-cloud/spring-cloud-gcp/issues/1815), I found `com.google.endpoints:endpoints-management-control-appengine-all:1.0.11` contains old class `io.opencensus.tags.TagContextBuilder`, which is overlapping with the one defined in `io.opencensus:opencensus-api:0.21.0`.

`com.google.endpoints:endpoints-management-control-appengine-all:1.0.11` is not under the Google Cloud BOM. Shall we add this to the bom?

Document referring endpoints-management-control-appengine-all:
https://cloud.google.com/endpoints/docs/frameworks/java/adding-api-management

**Comment by meltsufin** [comment]
Also see: https://github.com/cloudendpoints/endpoints-management-java/issues/51

**Comment by elharo** [comment]
This is the sort of thing the enforcer rule can find. I don't think we should add libraries to the BOM just to catch this sort of thing.

**Comment by suztomo** [comment]
> I don't think we should add libraries to the BOM just to catch this sort of thing

I agree.

I still think `com.google.endpoints:endpoints-management-control-appengine` (not "-all") should be added to the BOM after a compatible version with other artifacts is released.
