### ISSUE TITLE
Cloud Libraries BOM to have opencensus-exporter-stats-stackdriver?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#862]
A problem was observed by @igorbernstein2 among the versions of stackdriver, opencensus, grpc, google-cloud-java.

Can our BOM help this by including stackdriver java libraries?

Stackdriver artifacts he wants to use with google-cloud-java:

- io.opencensus:opencensus-exporter-stats-stackdriver:0.23.0
- io.opencensus:opencensus-exporter-trace-stackdriver:0.23.0

(Opencensus 0.24.0 is the latest as of August 30th)

His pom: http://gpaste/5889814891069440

**Comment by igorbernstein2** [comment]
To clarify I don't actually want to use a specific version: I just want to enable opencensus, which requires adding 2~3 artifacts: opencensus-impl and the stackdriver deps. The reason I chose 0.23.0 because google-cloud-java uses opencensus-api and I wanted to align the opencensus modules

**Comment by suztomo** [comment]
@igorbernstein2  Another way to control transitive dependencies is to import grpc BOM. Example: https://paste.googleplex.com/5168510231642112

```
  <dependencyManagement>
    <dependencies>
     ...
      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-bom</artifactId>
        <version>1.23.0</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
```

This is simpler than exclusion elements.


My memo:
Without exclusion of grpc in the pom, Maven complains incompatible grpc-core version:

```
[ERROR] Failed to execute goal on project spike-metrics: Could not resolve dependencies for project com.google.igorbernstein:spike-metrics:jar:1.0-SNAPSHOT: Failed to collect dependencies for com.google.igorbernstein:spike-metrics:jar:1.0-SNAPSHOT:
Could not resolve version conflict among
 [com.google.cloud:google-cloud-bigtable:jar:0.107.0
 -> com.google.cloud:google-cloud-core-grpc:jar:1.89.0
 -> com.google.api:gax-grpc:jar:1.48.0
 -> io.grpc:grpc-netty-shaded:jar:1.23.0
 -> io.grpc:grpc-core:jar:[1.23.0,1.23.0],

  com.google.cloud:google-cloud-bigtable:jar:0.107.0
 -> com.google.cloud:google-cloud-core-grpc:jar:1.89.0
 -> com.google.api:gax-grpc:jar:1.48.0
 -> io.grpc:grpc-alts:jar:1.23.0
 -> io.grpc:grpc-grpclb:jar:1.23.0
 -> io.grpc:grpc-core:jar:[1.23.0,1.23.0],

  com.google.cloud:google-cloud-bigtable:jar:0.107.0
 -> com.google.cloud:google-cloud-core-grpc:jar:1.89.0
 -> com.google.api:gax-grpc:jar:1.48.0
 -> io.grpc:grpc-alts:jar:1.23.0
 -> io.grpc:grpc-core:jar:[1.23.0,1.23.0],

  io.opencensus:opencensus-exporter-stats-stackdriver:jar:0.23.0
 -> io.grpc:grpc-auth:jar:1.19.0
 -> io.grpc:grpc-core:jar:[1.19.0,1.19.0],

  io.opencensus:opencensus-exporter-stats-stackdriver:jar:0.23.0
 -> io.grpc:grpc-core:jar:1.19.0,

  io.opencensus:opencensus-exporter-stats-stackdriver:jar:0.23.0
 -> io.grpc:grpc-stub:jar:1.19.0
 -> io.grpc:grpc-core:jar:1.19.0,

  io.opencensus:opencensus-exporter-trace-stackdriver:jar:0.23.0
 -> io.grpc:grpc-core:jar:1.19.0]
```

Latest [`opencensus-exporter-stats-stackdriver:0.24.0`](https://search.maven.org/artifact/io.opencensus/opencensus-exporter-stats-stackdriver/0.24.0/jar) has still old grpc version 1.22.0.

**Comment by igorbernstein2** [comment]
That is better, thanks!
However it's still not great because customers will still have to keep the grpc version in sync with google-cloud-java manually

**Comment by suztomo** [comment]
That's very goal of our "Google Libraries BOM" that declares set of compatible Google library versions.
https://github.com/GoogleCloudPlatform/cloud-opensource-java#google-libraries-bom 
and why I created this ticket.

**Comment by elharo** [comment]
I don't think this is in scope. If we can get the BOM closer to head with google-cloud-java that should help resolve this. Arguably we could add opencensus but I don't think stackdriver belongs here.

**Comment by suztomo** [comment]
Opencensus-exporter-stats-stackdriver is part of opencensus, not stackdriver. So adding Opencensus BOM would be nice once it's ready (https://github.com/census-instrumentation/opencensus-java/issues/1117).

However, Opencensus is going to close in favor of OpenTelemetry in late 2019:

> The migration for each language involves building a production-ready SDK, instrumentation for popular libraries, documentation, CI, a backwards compatibility bridge, and closing down the associated OpenCensus and OpenTracing projects (“sunsetting”).

from [Merging OpenTracing and OpenCensus: A Roadmap to Convergence](https://medium.com/opentracing/a-roadmap-to-convergence-b074e5815289). We might not want to put effort for opencensus now.
