### ISSUE TITLE
Linkage error with gRPC 1.23.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#890]
This showed up when I tried updating the BOM to gRPC 1.23.0:

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 62.666 s <<< FAILURE! - in com.google.cloud.MaximumLinkageErrorsTest
[ERROR] textMaximumLinkageErrors(com.google.cloud.MaximumLinkageErrorsTest)  Time elapsed: 62.628 s  <<< ERROR!
com.google.common.base.VerifyException: When checking a class reference from org.graalvm.libgraal.LibGraal to jdk.vm.ci.services.Services, the reference to the target class is no longer found in the source class's constant pool.
	at com.google.cloud.MaximumLinkageErrorsTest.textMaximumLinkageErrors(MaximumLinkageErrorsTest.java:51)

**Comment by elharo** [comment]
https://stackoverflow.com/questions/57211453/how-to-use-graalvm-in-java-class-not-found-exception

**Comment by suztomo** [comment]
Let me see.

**Comment by suztomo** [comment]
GraalVM needs a special JDK containing jdk.vm.ci package #929
