### ISSUE TITLE
com.google.auth:google-auth-library-oauth2-http:0.17.0 conflict

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#891]
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
The next protobuf release will let us push google-cloud-java to 107. At 108 this problem shows up:

Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.auth:google-auth-library-oauth2-http:0.17.0 paths to dependency are:
+-com.google.cloud.tools.opensource:upper-bounds-check:2.0.0-SNAPSHOT
  +-com.google.cloud:google-cloud-core:1.89.0
    +-com.google.api:gax:1.48.0
      +-com.google.auth:google-auth-library-oauth2-http:0.17.0
and
+-com.google.cloud.tools.opensource:upper-bounds-check:2.0.0-SNAPSHOT
  +-com.google.cloud:google-cloud-storage:1.89.0
    +-com.google.cloud:google-cloud-core-http:1.89.0
      +-com.google.auth:google-auth-library-oauth2-http:0.17.1
and
+-com.google.cloud.tools.opensource:upper-bounds-check:2.0.0-SNAPSHOT
  +-com.google.cloud:google-cloud-storage:1.89.0
    +-com.google.cloud:google-cloud-core-http:1.89.0
      +-com.google.api:gax-httpjson:0.65.0
        +-com.google.auth:google-auth-library-oauth2-http:0.17.0
]

**Comment by elharo** [comment]
should be fixed in 109 by https://github.com/googleapis/google-cloud-java/pull/6221

**Comment by suztomo** [comment]
ok to close this?
