### ISSUE TITLE
Linkage Checker to exclude classes in multi-release JAR

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#895]
Linkage Checker to exclude classes in multi-release JAR

#890 's error `com.google.common.base.VerifyException: When checking a class reference from org.graalvm.libgraal.LibGraal to jdk.vm.ci.services.Services, the reference to the target class is no longer found in the source class's constant pool.` is caused by ClassRepository's incorrect handling of  classes in multi-release JAR. Classes in `META-INF.versions.9` or `META-INF.versions.11` have the same name as normal classes and thus the cache in `ClassRepository` was not working as expected; it returned different instances than the one used in extracting symbol references.

Currently Linkage Checker supports Java 8 or earlier (as documented in [isCompatibleClassFileVersion](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java#L169)). And thus there's no need to read classes in `META-INF.versions.`.

**Comment by elharo** [comment]
Do we have an issue for supporting Java 9+?

**Comment by suztomo** [comment]
Yes, current design has an issue. Java9+’s multi-release JAR allows different class implementations (files) to have the same class name. The current Linkage Checker assumes one class name for one class implementation.

I think we’ll need an option to specify Java version to support multi release JAR.

**Comment by elharo** [comment]
Can you open an issue in the bug tracker? 
The current PR simply picks the Java 8 implementation, right? 
We need to figure out which to pick when. Or maybe we need to consider linkage errors against any version and report accordingly.

**Comment by suztomo** [comment]
#897 is for Java 9+ support.
