### ISSUE TITLE
General Tool for printing dependency tree

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#92]
That is, something much like `mvn dependency:tree` except:

1. Project may not be checked out or have source code available.
2. Project may be built with gradle, ant, or bazel instead of maven.

That is, reads metadata from central repo instead of local filesystem.

**Comment by elharo** [comment]
see https://stackoverflow.com/questions/3342908/how-to-get-a-dependency-tree-for-an-artifact

**Comment by elharo** [comment]
a shell script to convert coords to this might be a quick hack:

$ mvn -f ~/.m2/repository/io/grpc/grpc-auth/1.15.0/grpc-auth-1.15.0.pom   dependency:tree

**Comment by suztomo** [comment]
Hi @elharo 

What do you think about the design below?

- To create "deptree" directory under cloud-opensource-java
- its pom.xml to have a main class specified. `com.google.cloud.tools.opensource.deptree.DependencyTreeMain`
- the main class takes argument of an artifact e.g., io.grpc:grpc-auth:1.15.0

The example command would look like the below:

    suztomo-macbookpro44:cloud-opensource-java suztomo$ mvn -f deptree/pom.xml exec:java -Dexec.args="io.grpc:grpc-auth:1.15.0"
    [INFO] Scanning for projects...
    ...
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
      io.grpc:grpc-auth:jar:1.15.0
        io.grpc:grpc-core:jar:1.15.0
          io.grpc:grpc-context:jar:1.15.0
          com.google.code.gson:gson:jar:2.7
          com.google.guava:guava:jar:20.0
            com.google.code.findbugs:jsr305:jar:1.3.9
    ....
                com.google.code.findbugs:jsr305:jar:1.3.9
                com.google.errorprone:error_prone_annotations:jar:2.0.2
                com.google.j2objc:j2objc-annotations:jar:0.1
                org.codehaus.mojo:animal-sniffer-annotations:jar:1.14
        com.google.auth:google-auth-library-credentials:jar:0.9.0

**Comment by elharo** [comment]
Looks good. Don't worry too much about how the main method is invoked. Perhaps keep it small and mostly pass arguments to another method that returns the tree and can be used by other code.
