### ISSUE TITLE
Netty-handler's dependency to netty-tcnative fails without os-maven-plugin

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#925]
My example project (https://github.com/suztomo/troubleshooting-firestore-protobuf) fails.

```
~/firestore-protobuf$ mvn clean install
...
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-linkage-checker) @ firestore-protobuf ---
[ERROR] Could not find artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.22.Final
[ERROR] Paths to the missing artifact: suztomo:firestore-protobuf:jar:1.0-SNAPSHOT > com.google.firebase:firebase-admin:jar:6.9.0 (compile) > io.netty:netty-handler:jar:4.1.34.Final (compile) > io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.22.Final (compile?)
[WARNING] Rule 0: com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule failed with message:
Unable to build a dependency graph: Could not resolve dependencies for project suztomo:firestore-protobuf:jar:1.0-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.22.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

If I add the following to the troubleshooting-firestore-protobuf project, the extension solves the error:

```
  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.2.3.Final</version>
      </extension>
    </extensions>
```

# netty-handler's pom.xml

[io.netty:netty-handler:jar:4.1.34.Final](
https://search.maven.org/artifact/io.netty/netty-handler/4.1.34.Final/jar) has the following dependency:

```
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>${tcnative.artifactId}</artifactId>
      <classifier>${tcnative.classifier}</classifier>
      <optional>true</optional>
    </dependency>
```

The error won't happen in normal use of netty-handler because the dependency is optional.

`${tcnative.classifier}` is defined in [netty-parent](https://search.maven.org/artifact/io.netty/netty-parent/4.1.34.Final/pom):

```
    <tcnative.classifier>${os.detected.classifier}</tcnative.classifier>
```

**Comment by elharo** [comment]
I don't have time to hunt it down ATM but I vaguely recall I out code in the library somewhere to handle this case with os.detected.classifier. Maybe it's the tcnative.classifier that also needs to be handled in a similar way?

**Comment by suztomo** [comment]
Yes, this is similar to https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/809.

Memo:
Set breakpoint at `org.eclipse.aether.graph.Dependency` line 90 for `netty-tcnative`. This comes from managed dependency of netty-codec-http.
