### ISSUE TITLE
 jdk.vm.ci. not found

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#929]
This is in a branch with some updates to the BOM via MaximumLinkageErrors test. Looks like something we might want to special case. Need to research further. 

Class jdk.vm.ci.meta.ResolvedJavaMethod is not found
Class jdk.vm.ci.services.Services is not found
Class jdk.vm.ci.meta.ResolvedJavaType is not found
Class jdk.vm.ci.meta.Signature is not found
Class jdk.vm.ci.meta.JavaType is not found
Class jdk.vm.ci.meta.JavaConstant is not found
Class jdk.vm.ci.meta.JavaKind is not found
Class jdk.vm.ci.code.TargetDescription is not found
Class jdk.vm.ci.amd64.AMD64$Flag is not found
Class jdk.vm.ci.aarch64.AArch64 is not found
Class jdk.vm.ci.code.Architecture is not found
Class jdk.vm.ci.meta.JavaKind$FormatWithToString is not found
Class jdk.vm.ci.meta.ResolvedJavaField is not found
Class jdk.vm.ci.meta.VMConstant is not found
Class jdk.vm.ci.meta.Constant is not found
Class jdk.vm.ci.meta.ConstantReflectionProvider is not found
Class jdk.vm.ci.meta.Assumptions$AssumptionResult is not found
Class jdk.vm.ci.meta.PlatformKind is not found
Class jdk.vm.ci.code.CodeUtil is not found
Class jdk.vm.ci.meta.MetaAccessProvider is not found
Class jdk.vm.ci.amd64.AMD64$CPUFeature is not found
Class jdk.vm.ci.amd64.AMD64 is not found
Class jdk.vm.ci.code.stack.StackIntrospection is not found
Class jdk.vm.ci.runtime.JVMCI is not found
Class jdk.vm.ci.runtime.JVMCIRuntime is not found
Class jdk.vm.ci.runtime.JVMCIBackend is not found
Class jdk.vm.ci.code.stack.InspectedFrame is not found
Class jdk.vm.ci.code.stack.InspectedFrameVisitor is not found
Class jdk.vm.ci.code.site.Infopoint is not found
Class jdk.vm.ci.code.site.InfopointReason is not found
Class jdk.vm.ci.meta.SpeculationLog$SpeculationReason is not found
Class jdk.vm.ci.meta.SpeculationLog is not found
Class jdk.vm.ci.meta.SpeculationLog$Speculation is not found
Class jdk.vm.ci.meta.DeoptimizationAction is not found
Class jdk.vm.ci.meta.DeoptimizationReason is not found
Class jdk.vm.ci.code.VirtualObject is not found
Class jdk.vm.ci.code.StackSlot is not found
Class jdk.vm.ci.code.DebugInfo is not found
Class jdk.vm.ci.code.BytecodeFrame is not found
Class jdk.vm.ci.meta.JavaValue is not found
Class jdk.vm.ci.code.ValueUtil is not found
Class jdk.vm.ci.meta.AllocatableValue is not found
Class jdk.vm.ci.code.site.Call is not found
Class jdk.vm.ci.code.site.ExceptionHandler is not found
Class jdk.vm.ci.meta.LocalVariableTable is not found
Class jdk.vm.ci.meta.Local is not found
Class jdk.vm.ci.aarch64.AArch64$CPUFeature is not found
Class jdk.vm.ci.meta.Value is not found
Class jdk.vm.ci.common.JVMCIError is not found
Class jdk.vm.ci.code.Register is not found
Class jdk.vm.ci.code.ReferenceMap is not found
Class jdk.vm.ci.code.site.DataPatch is not found
Class jdk.vm.ci.code.site.DataSectionReference is not found
Class jdk.vm.ci.code.site.ConstantReference is not found
Class jdk.vm.ci.meta.MemoryAccessProvider is not found
Class jdk.vm.ci.code.RegisterConfig is not found
Class jdk.vm.ci.code.CodeCacheProvider is not found
Class jdk.vm.ci.code.CallingConvention is not found
Class jdk.vm.ci.code.ValueKindFactory is not found
Class jdk.vm.ci.code.CallingConvention$Type is not found
Class jdk.vm.ci.meta.ValueKind is not found
Class jdk.vm.ci.meta.SerializableConstant is not found
Class jdk.vm.ci.code.CompiledCode is not found
Class jdk.vm.ci.code.site.Reference is not found
Class jdk.vm.ci.aarch64.AArch64Kind is not found
Class jdk.vm.ci.hotspot.aarch64.AArch64HotSpotRegisterConfig is not found
Class jdk.vm.ci.code.RegisterArray is not found
Class jdk.vm.ci.code.RegisterAttributes is not found
Class jdk.vm.ci.code.RegisterValue is not found
Class jdk.vm.ci.aarch64.AArch64$Flag is not found
Class jdk.vm.ci.hotspot.HotSpotJVMCIRuntime is not found
Class jdk.vm.ci.meta.JavaField is not found
Class jdk.vm.ci.meta.JavaMethod is not found
Class jdk.vm.ci.meta.ExceptionHandler is not found
Class jdk.vm.ci.meta.UnresolvedJavaType is not found
Class jdk.vm.ci.meta.ConstantPool is not found
Class jdk.vm.ci.common.NativeImageReinitialize is not found
Class jdk.vm.ci.meta.MetaUtil is not found
Class jdk.vm.ci.meta.JavaTypeProfile$ProfiledType is not found
Class jdk.vm.ci.meta.JavaTypeProfile is not found
Class jdk.vm.ci.meta.TriState is not found
Class jdk.vm.ci.meta.ResolvedJavaMethod$Parameter is not found
Class jdk.vm.ci.meta.LineNumberTable is not found
Class jdk.vm.ci.meta.JavaMethodProfile is not found
Class jdk.vm.ci.meta.JavaMethodProfile$ProfiledMethod is not found
Class jdk.vm.ci.hotspot.HotSpotResolvedJavaMethod is not found
Class jdk.vm.ci.hotspot.HotSpotResolvedJavaField is not found
Class jdk.vm.ci.hotspot.HotSpotResolvedJavaType is not found
Class jdk.vm.ci.hotspot.HotSpotSignature is not found
Class jdk.vm.ci.meta.DefaultProfilingInfo is not found
Class jdk.vm.ci.meta.PrimitiveConstant is not found
Class jdk.vm.ci.code.InstalledCode is not found
Class jdk.vm.ci.code.InvalidInstalledCodeException is not found
Class jdk.vm.ci.amd64.AMD64Kind is not found
Class jdk.vm.ci.code.Register$RegisterCategory is not found
Class jdk.vm.ci.meta.ProfilingInfo is not found
Class jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory$CompilationLevelAdjustment is not found
Class jdk.vm.ci.hotspot.HotSpotSpeculationLog is not found
Class jdk.vm.ci.code.BytecodePosition is not found
Class jdk.vm.ci.runtime.JVMCICompiler is not found
Class jdk.vm.ci.code.BailoutException is not found
Class jdk.vm.ci.meta.Assumptions is not found
Class jdk.vm.ci.meta.InvokeTarget is not found
Class jdk.vm.ci.code.CodeUtil$DefaultRefMapFormatter is not found
Class jdk.vm.ci.code.site.Mark is not found
Class jdk.vm.ci.code.StackLockValue is not found
Class jdk.vm.ci.code.CompilationRequest is not found
Class jdk.vm.ci.meta.RawConstant is not found
Class jdk.vm.ci.meta.MethodHandleAccessProvider is not found
Class jdk.vm.ci.meta.MethodHandleAccessProvider$IntrinsicMethod is not found
Class jdk.vm.ci.code.RegisterSaveLayout is not found
Class jdk.vm.ci.sparc.SPARC is not found
Class jdk.vm.ci.sparc.SPARC$CPUFeature is not found
Class jdk.vm.ci.sparc.SPARCKind is not found
Class jdk.vm.ci.hotspot.HotSpotVMConfigAccess is not found
Class jdk.vm.ci.hotspot.HotSpotResolvedObjectType is not found
Class jdk.vm.ci.hotspot.HotSpotInstalledCode is not found
Class jdk.vm.ci.hotspot.HotSpotCompilationRequestResult is not found
Class jdk.vm.ci.hotspot.HotSpotCompilationRequest is not found
Class jdk.vm.ci.services.JVMCIServiceLocator is not found
Class jdk.vm.ci.runtime.JVMCICompilerFactory is not found
Class jdk.vm.ci.hotspot.HotSpotVMEventListener is not found
Class jdk.vm.ci.common.InitTimer is not found
Class jdk.vm.ci.hotspot.HotSpotCallingConventionType is not found
Class jdk.vm.ci.hotspot.HotSpotCodeCacheProvider is not found
Class jdk.vm.ci.hotspot.HotSpotCompiledCode$Comment is not found
Class jdk.vm.ci.hotspot.HotSpotCompiledNmethod is not found
Class jdk.vm.ci.hotspot.HotSpotCompiledCode is not found
Class jdk.vm.ci.code.site.Site is not found
Class jdk.vm.ci.hotspot.HotSpotVMConfigStore is not found
Class jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory is not found
Class jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory$CompilationLevel is not found
Class jdk.vm.ci.hotspot.HotSpotConstant is not found
Class jdk.vm.ci.hotspot.HotSpotCompressedNullConstant is not found
Class jdk.vm.ci.code.CompilationRequestResult is not found
Class jdk.vm.ci.hotspot.HotSpotForeignCallTarget is not found
Class jdk.vm.ci.code.Location is not found
Class jdk.vm.ci.hotspot.HotSpotReferenceMap is not found
Class jdk.vm.ci.hotspot.HotSpotMetaspaceConstant is not found
Class jdk.vm.ci.hotspot.HotSpotObjectConstant is not found
Class jdk.vm.ci.hotspot.HotSpotConstantReflectionProvider is not found
Class jdk.vm.ci.hotspot.HotSpotConstantPool is not found
Class jdk.vm.ci.hotspot.HotSpotResolvedPrimitiveType is not found
Class jdk.vm.ci.hotspot.HotSpotMemoryAccessProvider is not found
Class jdk.vm.ci.hotspot.HotSpotMetaAccessProvider is not found
Class jdk.vm.ci.hotspot.HotSpotSentinelConstant is not found
Class jdk.vm.ci.meta.Assumptions$Assumption is not found
Class jdk.vm.ci.hotspot.HotSpotNmethod is not found

**Comment by elharo** [comment]
Looks like this is part of GraalVM.

**Comment by elharo** [comment]
This is from gRPC 1.23.0, same as #890

**Comment by suztomo** [comment]
Memo:
They are from grpc-netty > netty-codec-http2 > netty-common


# svm-19.0.0.jar
118 target classes causing linkage errors referenced from 1,141 source classes.
The following paths to the jar file from the BOM are found in the dependency tree:
Artifacts 'io.grpc:grpc-netty > io.netty:netty-common > com.oracle.substratevm:svm' exist in all 80 dependency paths. Example path: io.grpc:grpc-netty:1.23.0 / io.netty:netty-codec-http2:4.1.38.Final / io.netty:netty-common:4.1.38.Final / com.oracle.substratevm:svm:19.0.0

# pointsto-19.0.0.jar
24 target classes causing linkage errors referenced from 88 source classes.

Artifacts 'io.grpc:grpc-netty > io.netty:netty-common > com.oracle.substratevm:svm > com.oracle.substratevm:pointsto' exist in all 80 dependency paths. Example path: io.grpc:grpc-netty:1.23.0 / io.netty:netty-codec-http2:4.1.38.Final / io.netty:netty-common:4.1.38.Final / com.oracle.substratevm:svm:19.0.0 / com.oracle.substratevm:pointsto:19.0.0

# compiler-19.0.0.jar
141 target classes causing linkage errors referenced from 3,106 source classes.

Artifacts 'io.grpc:grpc-netty > io.netty:netty-common > com.oracle.substratevm:svm > org.graalvm.compiler:compiler' exist in all 160 dependency paths. Example path: io.grpc:grpc-netty:1.23.0 / io.netty:netty-codec-http2:4.1.38.Final / io.netty:netty-common:4.1.38.Final / com.oracle.substratevm:svm:19.0.0 / org.graalvm.compiler:compiler:19.0.0


(Continuing on how netty-common uses com.oracle.substratevm and graalvm...)

**Comment by elharo** [comment]
Makes sense. We shoudl find out if there's a specific reason gRPC upgraded netty or if they'd be ameanble to a downgrade.

**Comment by suztomo** [comment]
Netty has adapted the convention of GraalVM's native image generation by adding 5 classes in [internal/svm package](https://github.com/netty/netty/tree/f1495e19459eb4e961b1c078e7692680f88a0803/common/src/main/java/io/netty/util/internal/svm) (https://github.com/netty/netty/pull/8963).

[netty-common](https://search.maven.org/artifact/io.netty/netty-common/4.1.38.Final/jar)'s "provided" declaration to `com.oracle.substratevm:svn`:

```
    <dependency>
      <groupId>com.oracle.substratevm</groupId>
      <artifactId>svm</artifactId>
      <version>${graalvm.version}</version>
      <!-- Provided scope as it is only needed for compiling the SVM substitution classes -->
      <scope>provided</scope>
    </dependency>
```

**Comment by elharo** [comment]
Hmm, so it sounds like these might be true positives?

**Comment by suztomo** [comment]
It seems true positive on `com.oracle.substratevm:svm:19.0.0`.

```
Class jdk.vm.ci.meta.ResolvedJavaMethod is not found, referenced from 94 classes ▼

com.oracle.svm.core.SubstrateUtil
...
```


Checking further.

**Comment by suztomo** [comment]
## Specialcase classes in the GraalVM-related packages

To suppress errors from `jdk.vm.ci`, `com.oracle.graal`, and `org.graalvm`
