### ISSUE TITLE
JLBP-1: no compile-only scope

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#950]
In JLBP-1 we say:

Use the smallest scope possible. For example, AutoValue doesn't need to use compile scope, and can instead use compile-only, since it doesn't need to appear on the classpath of consumers.

However Maven doesn't have a compile-only scope and in Gradle it's compileOnly. 

We should either fix this here, or perhaps write a completely new JLBP to "Use the smallest scope possible" that covers this as well as provided and optional.

**Comment by garrettjonesgoogle** [comment]
I don't see "scope" or "compile-only" mentioned on JLBP-2...

**Comment by elharo** [comment]
My mistakel. This is in JLBP-1.

**Comment by garrettjonesgoogle** [comment]
I think the topic of scopes fits very neatly within the JLBP-1 title "Minimize dependencies"...

**Comment by elharo** [comment]
OK, I'll try adding an expanded section on this point then. There's a lot we're not yet saying here.
