### ISSUE TITLE
Can LinkageMonitorTest be independent from developers' local Maven repository?

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#967]
Follow up of https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/960#issuecomment-543847313 .

> [ERROR] Failures:
> [ERROR] LinkageMonitorTest.testBomSnapshot:164 Artifacts other than protobuf-java should have the original version: com.google.api.grpc:grpc-google-cloud-asset-v1beta1:jar:0.49.0 != com.google.api.grpc:grpc-google-cloud-asset-v1beta1:jar:0.79.1-SNAPSHOT expected:<0.[49.0]> but was:<0.[79.1-SNAPSHOT]>

My diagnosis:

> I think the error occurred because Elliotte's local maven repository had 0.79.1-SNAPSHOT of the artifact, and Linkage Monitor tries to pick up highest "SNAPSHOT" versions of the artifacts in the BOM. Normally, such "SNAPSHOT" versions are not in local repositories unless developers build master branch of GitHub projects.
> 
> Removing ~/.m2/repository/com/google/api/grpc/grpc-google-cloud-asset-v1beta1 should fix the issue.

This behavior is not ideal, as we (developers) occasionally build snapshot versions of some libraries, which are saved to local Maven repository.

# Solutions

## Specify a temporary directory as local maven repository

When running LinkageMonitorTest, use a temporary directory different from users' local maven repo.

## Mock Maven repository in the test

LinkageMonitorTest to have an abstraction on local Maven repository.

Other ideas?

# How to confirm the enhancement

- Run LinkageMonitorTest. This should succeed normally.
- Install google-cloud-bom through google-cloud-java's master branch. This has a higher snapshot version 
- Run LinkageMonitorTest. Without the enhancement, `LinkageMonitorTest.testBomSnapshot` fails.

**Comment by elharo** [comment]
I wonder if it's possible for the tests to specify a different directory for the local repo? e.g. `Files.createTempDirectory()`

**Comment by suztomo** [comment]
The `testBomSnapshot` tests `copyWithSnapshot` with a spy RepositorySystem.

```
    system = RepositoryUtility.newRepositorySystem();

    // If possible, spy object should be avoided. But Maven is tightly coupled with RepositorySystem
    // and thus normal mock objects on RepositorySystem would make the test even complicated.
    // https://static.javadoc.io/org.mockito/mockito-core/3.0.0/org/mockito/Mockito.html#spy-T-
    spySystem = spy(system);

...
  @Test
  public void testBomSnapshot()
...
    Bom snapshotBom = LinkageMonitor.copyWithSnapshot(spySystem, bom);
```

`RepositoryUtility.newSession` is the function to associate RepositorySystem with `~/.m2` directory.

```
  @VisibleForTesting
  static Bom copyWithSnapshot(RepositorySystem repositorySystem, Bom bom)
      throws MavenRepositoryException, ModelBuildingException, ArtifactResolutionException {
    ImmutableList.Builder<Artifact> managedDependencies = ImmutableList.builder();
    RepositorySystemSession session = RepositoryUtility.newSession(repositorySystem);
```

# Attempt 1

The spy repository system to have only `    locator.addService(TransporterFactory.class, HttpTransporterFactory.class);`.

# Attempt 2

copyWithSnapshot to take RepositorySystemSession so that the session does not have this setting:

```
LocalRepository localRepository = new LocalRepository(findLocalRepository().getAbsolutePath());
session.setLocalRepositoryManager(system.newLocalRepositoryManager(session, localRepository));
```

**Comment by suztomo** [comment]
## Attempt 1 result
The same error.

## Attempt 2 result

Simply skipping localRepositoryManager setup causes the error:

```
java.lang.NullPointerException: repository system session's local repository manager cannot be null

	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.invalidSession(DefaultRepositorySystem.java:440)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.validateSession(DefaultRepositorySystem.java:427)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:256)
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitorTest.resolveArtifact(LinkageMonitorTest.java:100)
	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitorTest.testBomSnapshot(LinkageMonitorTest.java:151)
```

# Attempt 3

Elliotte's idea of `Files.createTempDirectory()`.
