### ISSUE TITLE
BOM release instructions need to specify doc updates

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/cloud-opensource-java#977]
There are a number of docs that need to be manually updated following a BOM release. These include:

https://github.com/googleapis/google-http-java-client/blob/master/docs/setup.md
https://developers.google.com/api-client-library/java/google-http-java-client/setup
https://github.com/googleapis/google-cloud-java/blob/master/TROUBLESHOOTING.md

and probably a few others. 

These should be added to the release instructions.

**Comment by suztomo** [comment]
Also shall we start adding release note to Git tags?
