### ISSUE TITLE
Linkage Checker invalidates Truth library using gwt-user (provided)

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#980]
Linkage Monitor detecting gwt-user problem: https://github.com/googleapis/google-cloud-java/pull/6531.

Linkage Checker invalidates Truth library using gwt-user (provided):

- Google-cloud-firestore 1.27.0 does not use Truth (`com.google.truth:truth:1.0`).
- Google-cloud-firestore 1.28.1-SNAPSHOT (Ben's migrate-conformance-tests) uses Truth.
- Truth depends on gwt-user (scope: provided)
- gwt-user has shaded classes that have invalid references.

This means Linkage Checker invalidates all projects that use Truth. Can we handle (whitelist) this case (or is this genuine error)?

# Why Truth needs gwt-user?

Truth (https://search.maven.org/artifact/com.google.truth/truth/1.0/jar) has a sub-artifact for GWT.

```
    <!-- Required only to build the -gwt sub-artifact. -->
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-user</artifactId>
      <scope>provided</scope>
    </dependency>
```

I don't see truth-gwt in Maven central: https://search.maven.org/search?q=g:com.google.truth

**Comment by elharo** [comment]
Good detective work. I wonder if we can remove/exclude this dependency from Google-cloud-firestore?

**Comment by suztomo** [comment]
It turned out that googleapis/google-cloud-java#6531 was not correctly settting `scope:test` for Truth. Linkage Checker excludes test scope artifacts.

As long as Truth is used as `scope:test`, there should not be a problem.

**Comment by elharo** [comment]
So this was another true positive and a good outcome. We detected an issue the developer was otherwise unaware of. 

We still have some work to do on both documenting the linkage monitor and improving its reports. The root cause should have been obvious from the report, and it definitely wasn't. We can't rely on the linkage monitor team man ually investigating each reported issue.

**Comment by suztomo** [comment]
Yes, this event demonstrated the power of checking dependency tree at presubmit check. #981 is to improve the error message.
