### ISSUE TITLE
User-friendly Linkage Monitor error message

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/cloud-opensource-java#981]
When investigating #980, the user could not find where gwt-user is coming from. So he was not able to take action upon the error message.

# Options 

## Option 1: Show Dependency Tree

The output would become too much to digest.

## Option 2: Show Path to the Problematic Artifact

This sounds reasonable.

## Option 3: Run Dashboard

This is what I usually do to investigate errors from Linkage Monitor.

# Scope of Dependency

It's important to add scope information to the nodes. As of now, the dashboard only shows artifacts:

```
The following paths to the jar file from the BOM are found in the dependency tree:
  com.google.cloud:google-cloud-firestore:1.28.1-SNAPSHOT / com.google.truth:truth:1.0 / com.google.gwt:gwt-user:2.8.2
```

**Comment by elharo** [comment]
I don't like option 3. It's extra work and not really something we can ask the user of this tool to do. When we uncover a problem we should immediately show all the information the user needs to understand it.

In cases like yesterday's it will probably be important to notice that all 20+ errors are really the same thing and not show 20 separate copies of the same basic info. That should keep the output short enough to read.

**Comment by suztomo** [comment]
Starting to explore option 2. Yes, the paths should only use unique Maven artifacts.

Memo:



```
  public static LinkageChecker create(Bom bom) throws RepositoryException, IOException {
    // duplicate code from DashboardMain follows. We need to refactor to extract this.
    ImmutableList<Artifact> managedDependencies = bom.getManagedDependencies();

    LinkedListMultimap<Path, DependencyPath> jarToDependencyPaths =
        ClassPathBuilder.artifactsToDependencyPaths(managedDependencies);
    // LinkedListMultimap preserves the key order
    ImmutableList<Path> classpath = ImmutableList.copyOf(jarToDependencyPaths.keySet());

    // When checking a BOM, entry point classes are the ones in the artifacts listed in the BOM
    List<Path> artifactJarsInBom = classpath.subList(0, managedDependencies.size());
    ImmutableSet<Path> entryPoints = ImmutableSet.copyOf(artifactJarsInBom);

    return LinkageChecker.create(classpath, entryPoints);
  }
```
