### ISSUE TITLE
JLBP to recommend separating annotationProcessorPaths from dependencies / compile classpath?

### ISSUE THREAD

**Issue by cpovirk** [GoogleCloudPlatform/cloud-opensource-java#986]
Dagger users sometimes run into trouble because that they put the Dagger annotation processor on the compile-time classpath (generally as a `provided` or `optional` dependency), only to find that its dependencies conflict with their project's actual compile dependencies. This apparently was [required before `maven-compiler-plugin` 3.5](https://github.com/google/dagger/blob/master/README.md#maven), but with newer versions, it's better to [use `annotationProcessorPaths`](https://github.com/google/dagger/blob/master/README.md#maven) (or the equivalent in Gradle, etc., also shown [in the Dagger docs](https://github.com/google/dagger/blob/master/README.md#gradle)).

We've updated docs for [AutoService](https://github.com/google/auto/tree/master/service#getting-started) and [AutoValue](https://github.com/google/auto/blob/master/value/userguide/index.md#with-maven) accordingly, but likely we have other projects to update, and this advice might make a useful JLBP for others?

**Comment by elharo** [comment]
This might be an instance of a more general principle on separating environment classpath from user classpath. This has recently come up in Hadoop, and in the long distant past I've seen it in servlet containers and jre/lib/ext directories too.

**Comment by saturnism** [comment]
I feel this is more aligned w/ minimizing dependencies - http://jlbp.dev/JLBP-1.html

I.e., annotation processors should never have been a direct dependency that was transitively exposed to consumers.
